### ISSUE TITLE
SAML duplicated accounts

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#1003]
### Steps to reproduce
1. Add a SAML account
2. Add a new SAML account
3. Switch from the second one to the first one

### Expected behaviour
Account switched correctly

### Actual behaviour
Accounts duplicated

Tested with iOS10/iOS11

**Comment by nasli** [comment]
Related https://github.com/owncloud/ios/issues/923, https://github.com/owncloud/ios/pull/976
Currently is not reproducible because this other bug https://github.com/owncloud/ios/issues/747 that need to be fixed before

**Comment by jesmrec** [comment]
Not reproducible in latest checks. Closing, if it becomes reproducible anywhare, reopen please.
