### ISSUE TITLE
SAML session expires by switching account

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#1004]
### Steps to reproduce
1. Add a SAML account with 5 minutes of expiration (for example)
2. After 2 minutes, add other account with the same expiration time
3. After 5 minutes, first account has expired, enter credentials
4. Switch account to 2.

### Expected behaviour
Session is alive

### Actual behaviour
Session is expired although time is not expired

iOS10/11.x iPhoine6SPlus, iPhone6S

**Comment by nasli** [comment]
could we re open this maybe https://github.com/owncloud/ios/issues/1004

**Comment by jesmrec** [comment]
Right. Closing this.
