### ISSUE TITLE
No preview for notes (*.txt) anymore

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios#1007]
### Steps to reproduce
1. Click on a .TXT file

### Expected behaviour
Preview of text content should appear. You only see a icon instead.

### Actual behaviour
There’s no preview of notes anymore. You have to edit a note to see its contents.

### Server configuration

**ownCloud version:**
10.0.3

### Client
**iOS version:**
n/a, Tested with 10.3.3
**ownCloud app version:**
3.7.2
**Device model:**
iPad 2

**Comment by michaelstingl** [comment]
I've seen this on iPhone too.

**Comment by nasli** [comment]
It was working within 3.7.0, maybe is due some changes in layouts for iOS11 support within 3.7.2.

Johan Lindstrom Thank you for your feedback.

**Comment by Kassiematis** [comment]
Looks like #1011 is the same issue

**Comment by michaelstingl** [comment]
More files seem affected:

> After update ios and owncloud app preview for doc and excel does not work anymore.

(from: https://github.com/owncloud/ios/issues/1011)

**Comment by jesmrec** [comment]
Fixed. It will be available in next version.
