### ISSUE TITLE
App crash after importing from a third-party app

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios#1009]
![2018-01-17 10_38_16](https://user-images.githubusercontent.com/33026403/35035776-a32ad938-fb72-11e7-89ff-ffcb34202dc3.gif)

### Steps to reproduce
1. Open an email with PDF attachment
2. Try to import this file to ownCloud

### Expected behaviour
File can be importet to the infrastructure with ownCloud app

### Actual behaviour
App crash

### Client
**iOS version:**
11.2.2
**ownCloud app version:**
3.7.2
**Device model:**
iPhone 5s

### Workaround

In the send to dialog you can select the ownCloud app under "more". This option allows importing.

![img_1305](https://user-images.githubusercontent.com/33026403/35039449-2967c8e8-fb7e-11e7-8471-231699ce3197.jpg)

**Comment by ChrisEdS** [comment]
@jesmrec Can you reproduce this behavior or do you need logs?

**Comment by jesmrec** [comment]
It does not happen (or i can not reproduce it) in iOS11. Let me check in iOS10.

**Comment by ChrisEdS** [comment]
Tested on my iPhone SE with 11.2.2 - same result. App crash.

**Comment by nasli** [comment]
>@jesmrec Can you reproduce this behavior or do you need logs?
 Not needed thank you, we can reproduce it.

There are two mode of share/import files for third party apps into OC, share and import, the share keep working, the one that crash was label as "import to OC or copy to owncloud" depending iOS version.

**Comment by jesmrec** [comment]
You are selecting the option "import with owncloud", there the bug is reproducible. But with the option "ownCloud", the file is shared and no crash happens. Could you check this option? @ChrisEdS

**Comment by ChrisEdS** [comment]
Yes, i agree @jesmrec . With the option "ownCloud" everything is fine.

**Comment by jesmrec** [comment]
So, we will check about this sharing options. Can it be related with the work in the "open in" feature @nasli?

**Comment by nasli** [comment]
Nop, was working within 3.7.0, regression it is within 3.7.2

**Comment by toughIQ** [comment]
Workaround with just the option „owncloud“ does not work properly for me. You can do an upload, but there is also the option to change the folder to upload to. You can choose any folder but it won’t keep this setting. Just uploads to the root owncloud folder.

**Comment by jesmrec** [comment]
yes, you are right @toughIQ . This problem is like the one reported here https://github.com/owncloud/ios/issues/788

**Comment by jesmrec** [comment]
Fixed in https://github.com/owncloud/ios/issues/1012

**Comment by ChrisEdS** [comment]
I close this issue @jesmrec - thanks for fixing!

**Comment by nasli** [comment]
@ChrisEdS not need to close it manually it will be closed automatically when the fix is merged and reference to the code that fixed ;)

**Comment by ChrisEdS** [comment]
Beautiful new world.
