### ISSUE TITLE
Cannot open doc and excel in preview on Ipad

### ISSUE THREAD

**Issue by Kassiematis** [owncloud/ios#1011]
After update ios and owncloud app preview for doc and excel does not work anymore.

**ownCloud version:**
9.1.7 or 10.0.4
### Client
**iOS version:**
11.2.2
**ownCloud app version:**
3.7.2
**Device model:**
Ipad MP2F2NF/A

#### Web server error log
no errors

**Comment by michaelstingl** [comment]
Added it here: https://github.com/owncloud/ios/issues/1007#issuecomment-358716675
