### ISSUE TITLE
Upload to a specific directory fails - upload is done to the root 

### ISSUE THREAD

**Issue by exzel123** [owncloud/ios#1017]
When I upload a photo to a specific directory or subdirectory in owncloud the photo isn't uploaded to the subdirectory. It is uploaded to the root. 

### Steps to reproduce
1. Open photos on the iPhone
2. Choose a photo
3. Upload the photo to the ownCloud app
4. The ownCloud app has been opened
5. In the ownCloud you can choose below another directory 
6. After you choosed  another directory click on upload to

### Expected behaviour
Tell us what should happen

The photo should be uploaded to the subdirectory. 

### Actual behaviour
Tell us what happens instead
But it is in the root directory of the ownCloud account

### Server configuration
It's hosted ownCloud

### Client
**iOS version:**
10.3.3
**ownCloud app version:**
3.7.2
**Device model:**
iPhone 6

**Comment by nasli** [comment]
Thanks for your feedback @exzel123, this is a duplicated of https://github.com/owncloud/ios/issues/788, please keep tracking there, thanks!

**Comment by exzel123** [comment]
Thanks for the responds. And sorry....
