### ISSUE TITLE
Offline Feature

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/ios#1023]
Dear all,

is it a normal behaviour when I have downloaded a file and set it to Offline that I allways get this message:

![img_2702](https://user-images.githubusercontent.com/9192953/36205670-cfcd4da8-118f-11e8-9121-ce4561befa08.PNG)

This is really confusing our users :-(

Cheers,

Pierre

**Comment by jesmrec** [comment]
this behaviour was improved last version, if i am not wrong. Which one are you using?

**Comment by pierrejochem** [comment]
Hi @jesmrec I use version 3.6.2

**Comment by pierrejochem** [comment]
You mean this:

- Improve network error messages inside the login view and all the app
- Improve UX for network warnings shown on the top of file list view

I will give it a try. Thank you for the hint. Next time I will read the release notes more in detail 👍

**Comment by jesmrec** [comment]
Thanks @pierrejochem. Let us know if you notice anything.

**Comment by pierrejochem** [comment]
Yes, sure and thank you very much for this nice app 👍
