### ISSUE TITLE
No full "Edit" option available for iOS client

### ISSUE THREAD

**Issue by konisolde** [owncloud/ios#1026]
No bug; feature request

### Expected behaviour
Tell us what should happen
1. Click on Settings
2. Click on ... 
3. See options to edit Account, including url, password, username
4. Update Account information
5. Use mobile app as usual

### Actual behaviour
Tell us what happens instead
1. Click on Settings
2. Click on ...
3. Only see option to Edit Password, Clear cache, and Remove Account -- no further options
4. Consequently, need to Remove account and complete initial set-up process with url, username, password, etc.

### Server configuration
**Web server:**

**Database:**

**PHP version:**

**ownCloud version:**

**Storage backend (external storage):**

### Client
**iOS version:** 11.2.5

**ownCloud app version:** 3.7.2

**Device model:** iPhone 6S

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
Edit option... you mean for some kind of files? maybe this is included in the scope od Files App, currently under development. More details will be appreciate. Thanks!!!

**Comment by konisolde** [comment]
@jesmrec - no, not for files - for the user account. :)

**Comment by konisolde** [comment]
Option to edit the URL.

**Comment by jesmrec** [comment]
In this case, i guess that the user/customer has moved to a new domain (or similar case that forces an URL change), we call it migration. They have to use the migration option, available in ownBrander for customers.

**Comment by konisolde** [comment]
@michaelstingl - wanna join in on this?

**Comment by javiergonzper** [comment]
@konisolde the URL it is not editable because historically was decided as it. 

Anyway I think that it is a bug is that the username is editable and should not be editable (as we are discussing here: https://github.com/owncloud/ios-app/issues/4). Probably was introduced on the new login screen. @jesmrec what do you think?

**Comment by jesmrec** [comment]
In the current app, the option to change the URL does not exist, but it is posible to move to a different URL with migration mode. If editing is desired, should be developed in the new login view.
