### ISSUE TITLE
Cannot close docx document

### ISSUE THREAD

**Issue by danieltuzes** [owncloud/ios#1028]
I've just installed the nextcloud onto iphone 4s. If I successfully log in and open a docx, I cannot close it, because I cannot see the options at the bottom of the screen. I know it should exist, because if I make a long tap, the zoom function appears. And if I move this lil window to the bottom, in the zoomed picture I'm able to see the buttons, but still cannot touch them.

Server version: 11.0.3

**Comment by jesmrec** [comment]
Please, ask for it in NC.
