### ISSUE TITLE
owncloud app 3.7.2 suddenly says that the server is in maintenance mode but it isn't

### ISSUE THREAD

**Issue by mamama1** [owncloud/ios#1029]
Nextcloud 11.0.6
owncloud app 3.7.2 on iOS

the app suddenly says that the server is in maintenance mode. web access is working as usual. access via the nextcloud "app" or web wrapper or whatever it is works too.
also the android app works (V 2.0.0)

where to start the search?

thanks.

**Comment by jesmrec** [comment]
Please, ask in NC.

**Comment by mamama1** [comment]
very helpful.

**Comment by jesmrec** [comment]
Sorry, i misunderstood your comment, but the problem here is to know the server response  against the maintenance mode. This is something that have to be checked in NC. But in any case, i will review what happens in oC.

**Comment by mamama1** [comment]
Hi

thanks, it seems to say HTTP 503 on the webdav part...

> 192.168.35.2 - - [02/Mar/2018:20:39:24 +0100] "POST /index.php/apps/files_sharing/shareinfo?t=vLztXE7rs10ZTY0 HTTP/1.1" 200 3510053 "-" "ownCloud Server Crawler"
> 192.168.35.2 - neumluc [02/Mar/2018:20:39:32 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 - "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.2"

**Comment by mamama1** [comment]
nvm it was fixed by adding ownCloud-iOS\/\d[.]\d[.]\d to base.php incompatible user agents list according to https://github.com/keeweb/keeweb/issues/492

**Comment by jesmrec** [comment]
ok, closing then.

**Comment by mamama1** [comment]
are there any plans to continue supporting nextcloud with the owncloud app anyways or will it seize to work at a random point in time? thanks

**Comment by jesmrec** [comment]
oC supports only oC. No plans, neither now nor in the past, to support other different platforms.

**Comment by mamama1** [comment]
i‘d pay an extra fee for NC support or a standalone NC app, just to make you think about it ;-)

the existing NC „app“ is a joke... and sure you oC guys know how to make a great app.
