### ISSUE TITLE
[5.7.3] Settings screen: Update year to 2018

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#1033]
```
//app year
#define k_year 2017
```
([source](https://github.com/owncloud/ios/blob/3f9580db31287d4306365bb7ab756e7b5457894e/Owncloud%20iOs%20Client/Branding/Customization.h#L17-L18))

**Comment by nasli** [comment]
This was already updated within 3.7.3 version https://github.com/owncloud/ios/blob/version_3.7.3/Owncloud%20iOs%20Client/Branding/Customization.h#L18
