### ISSUE TITLE
Can't select location other than the server document root 

### ISSUE THREAD

**Issue by mochour** [owncloud/ios#1035]
### Steps to reproduce
1. Open a document (pdf, jpg etc.)
2. Choose Owncloud as application to save with
3. Select a location in your server document tree
4. Clic Save 

### Expected behaviour
The document should be saved in the selected location

### Actual behaviour
The document is saved in the server document root

### Server configuration
**Web server: Apache 2.4.2**

**Database: MySQL 5.55**

**PHP version: 5**

**ownCloud version: 8.2.10**

**Storage backend (external storage):**

### Client
**iOS version: iOS 11**

**ownCloud app version: 3.7.3**

**Device model: iPhone 6**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by jesmrec** [comment]
duplicated from https://github.com/owncloud/ios/issues/788
