### ISSUE TITLE
OwnCloud as storage provider in Office 365

### ISSUE THREAD

**Issue by vbippus** [owncloud/ios#1038]
Hello,

This is not a bug a but a feature request, not on your apps directly, but related anyway ! 

### Steps to reproduce
1. Open a Doc file from the CERNBox App
2. Send the document to Word 365
3. Save as a copy 
4. Select location
5. Add a cloud provider

### Expected behaviour
It would be really nice to be able to add OwnCloud to the cloud providers list available on Office365 apps. 

### Actual behaviour
Currently many others such as Dropbox Edmodo or ShareFile are available.

Thanks for this nice product !

**Comment by michaelstingl** [comment]
@vbippus ownCloud is not a Cloud Storage Provider, it is only the software. In your case, CERNBox would need to apply at Microsoft to become a Cloud Storage Provider. The only thing, ownCloud could do, is to create central endpoint for Microsoft, where all ownCloud instances could proxy their traffic to make it accessible as a single Cloud Storage Provider. We are indeed investigating this, but I don't expect it in the iOS app soon.

In iOS11, Word uses also the Files app integration. This looks more promising, and we are working on the best Files app integration possible.

Files app integration is tracked here: https://github.com/owncloud/ios/issues/941

| Mobile Word "Open" menu | iOS11 Files app integration | Cloud Storage Provider |
| --- | --- | --- |
| ![2018-03-19_10_56_04](https://user-images.githubusercontent.com/214010/37590010-3abd69b8-2b67-11e8-9685-574ca1289ce6.png) | ![2018-03-19 10 58 34](https://user-images.githubusercontent.com/214010/37590122-92a4397c-2b67-11e8-9481-fe38c8b58db2.png)   | ![2018-03-19 10 58 53](https://user-images.githubusercontent.com/214010/37589527-d786f48c-2b65-11e8-89a2-56779b300a2f.png) |
