### ISSUE TITLE
Can not change Owncloud upload location when uploading via Photos iOS app

### ISSUE THREAD

**Issue by PrunelliParis** [owncloud/ios#1045]
Hello all,

Sorry if this issue already exists. Be sure that I looked for it without success, hence this (first for me :) issue

### Steps to reproduce
1. Open Photos application in iOS
2. Select one or several contents (photos/videos)
3. Share with ownCloud : ownCloud UI appears
4. Specify target location
5. Validate

### Expected behaviour
Upload location is updated with choice made at step 4 (info appearing at the bottom of the ownCloud UI)

### Actual behaviour
Upload location remains the root directory ("ownCloud")

### Info
This bug appeared during the last 3 months, but I can not trace exactly when.
For the record, I update iOS app and server (very) regularly.

### Server configuration
**Web server: Apache/2.4.25
**Database: 10.1.23-MariaDB-9+deb9u1
**PHP version: 5.6.30-0+deb8u1
**ownCloud version: 10.0.7
**Storage backend (external storage): Local HDD

### Client
**iOS version: 11.2.6
**ownCloud app version: 3.7.3
**Device model: iPhone 5s

**Comment by jesmrec** [comment]
Already reported: https://github.com/owncloud/ios/issues/788

**Comment by PrunelliParis** [comment]
Thanks

Strange though, as I was not experiencing this issue since quite recently.
For the record, my target folder is not empty.
