### ISSUE TITLE
[3.7.3] [UX] Create link share with expiration date

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#1047]
![2018-04-09 19 59 08](https://user-images.githubusercontent.com/214010/38517328-e6258bae-3c39-11e8-8469-ca1071c84a57.png)

### Steps to reproduce
1. Create a link share for a file or a folder
2. Add or edit the expiration date

### Expected behaviour
Date Picker should be fully visible

### Actual behaviour
Date Picker is 50% hidden under bottom device frame

### Server configuration
**ownCloud version:**
10.0.7

### Client
**iOS version:**
11.3

**ownCloud app version:**
3.7.3

**Device model:**
iPhone 7 Plus

@nasli please fix for next release /cc @jesmrec 

00009311

**Comment by jesmrec** [comment]
After fix developed by @pablocarmu, it looks like this:

![screen shot 2018-04-16 at 14 34 34](https://user-images.githubusercontent.com/14894746/38809356-82582a9c-4183-11e8-8c9a-6575b38e764a.png)


![screen shot 2018-04-16 at 14 35 13](https://user-images.githubusercontent.com/14894746/38809364-85a9d5d8-4183-11e8-9180-d0204ce2c5d5.png)

CC @michaelstingl

**Comment by jesmrec** [comment]
It will be released in 3.7.4
