### ISSUE TITLE
[3.7.3] [iPhone X] [UX] No safe area/margin on bottom of file preview page

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#1048]
| file list | file preview |
| --- | --- |
| ![file-list-2](https://user-images.githubusercontent.com/214010/38770629-1eff4c96-4016-11e8-9ab2-a154f01afdf9.png) | ![file-preview-2](https://user-images.githubusercontent.com/214010/38770630-1f1a886c-4016-11e8-8837-324df87c0fbd.png) |

### Steps to reproduce
1. Open preview of text file

### Expected behaviour
Bottom icons of preview page should have same safe margin than bottom icons of file list.

### Actual behaviour
Bottom icons of preview page are covered by iPhone X’s home indicator/bar. With passcode configured, it leads to the passcode activation when opening, downloading, sharing or deleting previewed file.

### Server configuration
**ownCloud version:**
10.0.7

### Client
**iOS version:**
11.3

**ownCloud app version:**
3.7.3

**Device model:**
iPhone X

00008588

**Comment by javiergonzper** [comment]
I am working on the issue here:
https://github.com/owncloud/ios/tree/fix_problems_previews_iphone_x

@pablocarmu if you come early tomorrow please start (or continue) with the issue:
https://github.com/owncloud/ios/issues/1047

**Comment by javiergonzper** [comment]
It is fixed from a developer point of view. Right now it is under QA

<img width="229" alt="screen shot 2018-04-16 at 12 52 04" src="https://user-images.githubusercontent.com/1815050/38805150-18335d66-4175-11e8-986b-a198c1cf68e8.png">

<img width="395" alt="screen shot 2018-04-16 at 12 52 09" src="https://user-images.githubusercontent.com/1815050/38805156-1e4964b6-4175-11e8-92a1-a200f47d7be2.png">

Also I fixed an issue on the preview of the documents (txt and office) happens the following once you rotate from portrait to landscape:

<img width="395" alt="screen shot 2018-04-16 at 12 37 41" src="https://user-images.githubusercontent.com/1815050/38805182-3b1b941a-4175-11e8-90e7-43de309e883a.png">

<img width="395" alt="screen shot 2018-04-16 at 12 39 19" src="https://user-images.githubusercontent.com/1815050/38805200-4715314a-4175-11e8-8c34-9bc9bd57d060.png">

From landscape to portrait:
<img width="229" alt="screen shot 2018-04-16 at 12 37 46" src="https://user-images.githubusercontent.com/1815050/38805215-5475ad38-4175-11e8-92ae-7ba362a5e636.png">

<img width="229" alt="screen shot 2018-04-16 at 12 39 25" src="https://user-images.githubusercontent.com/1815050/38805221-5c1bedd6-4175-11e8-96c3-0cbb417d5967.png">

As you can see a white space appear in the top after the rotation and in the bottom the tool bar dissapear.

Now everithing it is fixed:

<img width="229" alt="screen shot 2018-04-16 at 12 52 04" src="https://user-images.githubusercontent.com/1815050/38805306-a90889f6-4175-11e8-9988-22a578b3b38b.png">
<img width="395" alt="screen shot 2018-04-16 at 12 52 09" src="https://user-images.githubusercontent.com/1815050/38805307-a9246766-4175-11e8-90f9-2fdf4ea72e43.png">
<img width="229" alt="screen shot 2018-04-16 at 12 52 18" src="https://user-images.githubusercontent.com/1815050/38805308-a94440f4-4175-11e8-9614-53d689926ce9.png">
<img width="395" alt="screen shot 2018-04-16 at 12 52 21" src="https://user-images.githubusercontent.com/1815050/38805309-a95f757c-4175-11e8-9b27-93a61b34f92f.png">

**Comment by jesmrec** [comment]
Will be released in 3.7.4
