### ISSUE TITLE
Option to not insta upload on mobile data

### ISSUE THREAD

**Issue by Yoshimanly** [owncloud/ios#1053]
It's not really a problem, but I find it really annoying having to manually upload my photos because instant upload dosent have the feature to not upload when using mobile data, I still want to have access to my files when on mobile data, so no the fix is not going to options a disabling it. I may just be blind but I cannot find it. Thank you in advance ^^

**Comment by jesmrec** [comment]
Thanks for your suggestion!!

**Comment by jesmrec** [comment]
correct, we have already this opened issue. Let's track it there
