### ISSUE TITLE
It is not possible to connect to the server at this time

### ISSUE THREAD

**Issue by userahex** [owncloud/ios#1057]
Hi, it's been over 48 hours and I can't access my owncloud server. The message that shows up it "it is not posible to connect to the server at this time"
Please, help
 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
It should show up the log in screen

### Actual behaviour
Does not connect, and shows the message "it is not posible to connect to the server at this time"

### Server configuration
**Web server:**
37.59.62.212
**Database:**

**PHP version:**

**ownCloud version:**

**Storage backend (external storage):**

### Client
**iOS version:**

**ownCloud app version:**

**Device model:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
@userahex I also can't connect to your ownCloud server. I'd assume it's a problem with your server, not with the iOS app. To verify, you could try to connect to our demo server:
https://demo.owncloud.org/
(user: demo / pw: demo)

ownCloud forum is the better place to get help in general:
https://central.owncloud.org/

```
Michaels-MacBook-Pro-15:~ mstingl_oc$ curl -L -vvv http://37.59.62.212/
*   Trying 37.59.62.212...
* TCP_NODELAY set
* Connection failed
* connect to 37.59.62.212 port 80 failed: Operation timed out
* Failed to connect to 37.59.62.212 port 80: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to 37.59.62.212 port 80: Operation timed out
Michaels-MacBook-Pro-15:~ mstingl_oc$ curl -L -vvv https://37.59.62.212/
*   Trying 37.59.62.212...
* TCP_NODELAY set
* Connection failed
* connect to 37.59.62.212 port 443 failed: Operation timed out
* Failed to connect to 37.59.62.212 port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to 37.59.62.212 port 443: Operation timed out
```
