### ISSUE TITLE
empty file list, although files are there and creating files/folders works. 

### ISSUE THREAD

**Issue by mjollnir** [owncloud/ios#1062]
I'm not sure if this is related to the most recent upgrade or not although it seems like it may be.

I am syncing files between mac os and ios. The files are there on my mac and in the owncloud web interface, but the ios client, both on ipad and iphone, I see "Nothing in here. Upload something!". 

Creating a new folder or file from the ios app works (ie, it creates the data on the server, and it appears in the web interface and my mac), but the ios Files screen remains resolutely empty. 

I tried deleting all the files and resyncing and adding them back, as I wondered if there was an invalid filename or something, but that didn't fix it. 

I upgraded the server to 10.0.8-1+1.1 but that didn't fix it.

Debian stable with apache 2.4.25-3+deb9u4, php 7 7.0.27-0+deb9u1, postgresql 9.6+181+deb9u1
ios apps are both latest versions from the app store 3.7.5

I have access to server logs but there is nothing of note there.

**Comment by michaelstingl** [comment]
Could you check the Apache access logs for entries from your iOS client?

What version of iOS did you test?
What device did you test?

**Comment by mjollnir** [comment]
Thanks for getting back to me! 

Pulling down the Files screen to refresh shows the following entries in the server log:

[ip address] - - [20/Jun/2018:23:12:16 +0200] "GET /owncloud/status.php HTTP/1.1" 200 3498 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.5"
[ip address] - - [20/Jun/2018:23:12:18 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 3650 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.5"
[ip address] - - [20/Jun/2018:23:12:18 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 401 1060 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.5"
[ip address] - penny [20/Jun/2018:23:12:18 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 7038 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.5"
[ip address] - penny [20/Jun/2018:23:12:19 +0200] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 200 881 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.5"

This is for my iphone8, ios 11.4.

Doing the same thing on my ipad gives

[ip address] - - [20/Jun/2018:23:15:49 +0200] "GET /owncloud/status.php HTTP/1.1" 200 3498 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.5"
[ip address] - penny [20/Jun/2018:23:15:50 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 7257 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.5"
[ip address] - penny [20/Jun/2018:23:15:51 +0200] "GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 200 881 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.7.5"

and that's an 4th gen ipad, running 10.3.3.

**Comment by jesmrec** [comment]
Could you send us a test account on your server? to try to reproduce here and check if any problem is happening in the request exchange.

**Comment by mjollnir** [comment]
Sure, how should I send you the password?

**Comment by michaelstingl** [comment]
@mjollnir ==> apps@owncloud.com

**Comment by mmattel** [comment]
@michaelstingl 
I have the same issue as @mjollnir 
It works on the iPhone but not on the iPad, it worked in the past...
Switching accounts on the client does not change the behaviour

Server: Ubuntu 16.04, nginx, php7.0
IOS 11.4 on both devices
Client 3.7.5

**Comment by michaelstingl** [comment]
@mmattel Hm, that sounds strange, why does it work on the one device, and doesn't work on another one? Different WiFi settings? Cellular connection vs. WiFi? VPN? Could you delete the app and re-install?

**Comment by michaelstingl** [comment]
@mjollnir Can't reproduce with your test account on iPhone 7 Plus with iOS 11.4 and iPhone X with iOS 12 beta 3.

**Comment by mmattel** [comment]
Same environment for both devices.
Uninstalled and reinstalled on the iPad - works now.
I don´t know if I should be happy or not as such things should not appear...

**Comment by mjollnir** [comment]
Ok, I uninstalled and reinstalled on both iphone and ipad. That fixed it for me too. One thing I *had* previously tried, which hadn't worked, was "Clear cache" from the account list.  So I wonder if that's not clearing a cache properly where uninstalling and reinstalling does actually delete everything.  Anyway I am not convinced this problem is fixed either, but perhaps we can close this issue for now if nobody can reproduce it consistently.  Thanks!

**Comment by michaelstingl** [comment]
@javiergonzper @jesmrec Is there an internal migration step that could break things at the update to 3.7.5? What can be done to prevent such issues?

**Comment by jesmrec** [comment]
yes, if was tested in the upgrade stage. In any case, the upgrade from 3.7.3 to 3.7.5 did not include database upgrades: https://github.com/owncloud/ios/blob/master/Changelog.md. am i wrong?

**Comment by javiergonzper** [comment]
Yes, the database have changes:
> Alter files table, added new field to store the oc_privatelink from the propfind requests.

**Comment by jesmrec** [comment]
ummm, in any case this request should not break the upgrade. I will repeat the upgrade just in case and review what happened with the PROPFIND in the test account.

**Comment by jesmrec** [comment]
I reproduce the problem with the test account by installing from scratch `version_3.7.3`

- Upgrading 3.7.3 -> 3.7.5: Works fine
- Installing 3.7.5 from scratch: Works fine

**Comment by mmattel** [comment]
both work fine?

**Comment by jesmrec** [comment]
3.7.5 works fine in both cases: from scratch and upgrading from 3.7.3

3.7.3 from scratch -> list file is not displayed.

All of this stuff with the test account @mjollnir sent. We have to check differences with test servers to heck where the difference is. Do you have the problem with 3.7.5?

**Comment by mmattel** [comment]
yes, I have on both devices 3.7.5

**Comment by jesmrec** [comment]
ok, maybe checking the problem with 3.7.3 we can find out what happens with 3.7.5 as well.

**Comment by javiergonzper** [comment]
We found an issue related with a downgrade the version from 3.7.5 to 3.7.3 on a iPhone 6 Plus 11.3.1 device. This provoque a similar weird behavior but it is not related with your issue because it was fixed after remove the app and reinstall it again (and you are using the last version 3.7.5 and iOS 11.4).

Did you update from an older version than 3.7.3? For example a 3.7.2 or older?

**Comment by mjollnir** [comment]
No, I always update regularly, so I updated from whatever previous version was in the app store.

**Comment by chawbs** [comment]
I had same issue with automatic upgrade from latest previous version to 3.7.5 (I have automatic installs on iPad). Simply stopped working and initially gave errors about site not being secure before not allowing me to see any file. Re-install fixed it.

**Comment by javiergonzper** [comment]
@chawbs are you using a self signed certificates (not trusted) on your server?

**Comment by mmattel** [comment]
From my side,
I use a letsencrypt certificate without any worries
I upgrade my IOS app whenever a new verion is out - since years...

**Comment by chawbs** [comment]
@javiergonzper I use trusted certificates for all sites on the web, only use a self signed for my server at home which does not have a proper domain name. All working fine on every other platform - must have been an update fail of some kind...

**Comment by javiergonzper** [comment]
Yes must be an update fail on the database. The strange thing it is that did not affect to many people because we just have your two cases.
We will be more careful on the next update of the app in order to check all the possibilities that could exist during the upgrade 👍

**Comment by chawbs** [comment]
As far as I can see, it has worked in all cases for me apart from the one instance where this happened. It could be that another software update asked for a reboot and I pressed reboot during the auto-update which may have killed it part way through. I don't know if it is possible to stall windows restart until critical updates have finished???

**Comment by jesmrec** [comment]
could you check if problem persists with 3.8.0 version?

**Comment by chawbs** [comment]
Updated on 8 Sep without issue 👍

**Comment by jesmrec** [comment]
@mmattel @mjollnir issue fixed?

**Comment by mmattel** [comment]
I needed to kill my previous installation and reinstalled the new one. after that it worked. the point is, how will it behave on the next upgrade. that would show if it is fixed.

**Comment by michaelstingl** [comment]
@mmattel We've got no reports about this from users upgrading to 3.8.0.
