### ISSUE TITLE
Re-shares not shown in iOS app UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#1065]
### Steps to reproduce
1. User A shares folder with User B
2. User B shares received folder with User C

### Expected behaviour
Owner of a share should also see recipients of re-shares, same as in web UI.

### Actual behaviour
Re-shares not shown in iOS app UI.

### Server UI

| User A | User B | User C |
|---|---|---|
| ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43005844-5480580a-8c34-11e8-966f-b4919a4ce127.png) | ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43006035-f13fce96-8c34-11e8-904c-4dc63e00516a.png) | ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43006098-1d726a50-8c35-11e8-9ea0-d2ff65cd7f71.png) |

### iOS app UI

| User A | User B | User C |
|---|---|---|
| ![2018-07-20 16 17 13](https://user-images.githubusercontent.com/214010/43010437-c1c6d4fa-8c40-11e8-954b-6f1cfab610c0.png) | ![2018-07-20 16 17 57](https://user-images.githubusercontent.com/214010/43010445-c61d1352-8c40-11e8-9927-d36ff9daae83.png) | ![2018-07-20 16 18 48](https://user-images.githubusercontent.com/214010/43010448-c873125a-8c40-11e8-8cf6-c1dd25597c2f.png) |

### Server configuration
ownCloud version:
10.0.9

### Client
**iOS version:**
iOS 11.4

**ownCloud app version:**
3.7.5

**Device model:**
iPhone 7 Plus

## Solution

@jnweiger PR for the desktop client: https://github.com/owncloud/client/pull/6665

related: https://github.com/owncloud/enterprise/issues/2505

@javiergonzper another tiny one for the 3.7.6?

**Comment by javiergonzper** [comment]
After debug it is not so simple as we expected.
We have to modify things on the app and also on the library because we are using the same request to read all the shares of a folder and also to read the shares of a concrete file/folder.

So we need to separate both request.

**Comment by jesmrec** [comment]
Stuff done and merged. It will be available within the next release.
