### ISSUE TITLE
Change Password is buggy

### ISSUE THREAD

**Issue by voroyam** [owncloud/ios#1082]
### Steps to reproduce
1. Setup oC 10.0.9 + iOS App 3.8.0 + Basic Auth
2. Connect user1 to ownCloud on iOS device
3. Change password as the user1 or as the admin

### Expected behavior
Connection on the iOS device should be lost

User should be advised to edit his account settings.

### Actual behaviour
User can upload, navigate, download files.

After a while, a timeout error appears in the app.

If the user then clicks on edit password, 
1. he is send to the login screen
2. connection is tested
3. connection can not be established
4. no possibility to edit the password is shown
- adding a new account on the same server does not work. Steps 2-3 happen again.
- adding a new account on a different server does not work. 2-3 again.
- removing the account and adding it again does not work. 2-3.
![photo-2018-09-17-16-49-24_0520](https://user-images.githubusercontent.com/24212810/45632477-b7bc4180-ba9d-11e8-941b-37a21ca2ce90.PNG)
![photo-2018-09-17-16-49-35_0521](https://user-images.githubusercontent.com/24212810/45632478-b854d800-ba9d-11e8-8a1d-06c9b9d8c9a1.PNG)
![photo-2018-09-17-16-49-39_0522](https://user-images.githubusercontent.com/24212810/45632479-b854d800-ba9d-11e8-84e0-c1aab566fc70.PNG)
![photo-2018-09-17-16-49-44_0523](https://user-images.githubusercontent.com/24212810/45632480-b854d800-ba9d-11e8-9897-1341b6163f04.PNG)
![photo-2018-09-17-16-49-48_0524](https://user-images.githubusercontent.com/24212810/45632481-b854d800-ba9d-11e8-9a9e-762bae9dfcab.PNG)
![photo-2018-09-17-16-49-52_0526](https://user-images.githubusercontent.com/24212810/45632482-b854d800-ba9d-11e8-8ab4-16ad6f7f28e8.PNG)
![photo-2018-09-17-16-50-23_0525](https://user-images.githubusercontent.com/24212810/45632483-b854d800-ba9d-11e8-9371-52f29a4a8615.PNG)

maybe related

https://github.com/owncloud/android/issues/2296

**Comment by voroyam** [comment]
@michaelstingl

**Comment by michaelstingl** [comment]
@voroyam Is this basic auth or oauth2?

**Comment by voroyam** [comment]
Basic, I updated the Steps to reproduce

**Comment by michaelstingl** [comment]
Seems some magic in the 2.9.0-beta fixed it for the Android platform: https://github.com/owncloud/android/issues/2296

**Comment by jesmrec** [comment]
this is in the iOS side. It seems that cookies can be involved. I will have a look anyway.

**Comment by voroyam** [comment]
any update on this? @jesmrec
