### ISSUE TITLE
request not valid

### ISSUE THREAD

**Issue by soydepr** [owncloud/ios#1083]
oath2 stop working with ios app.

running latest app latest server 

today started Getting request not valid 
![img_0459](https://user-images.githubusercontent.com/546367/45850753-50082f80-bd05-11e8-92d3-6bba9236a301.PNG)

when i hit back it logs me to calendar 

![img_0460](https://user-images.githubusercontent.com/546367/45851220-cad24a00-bd07-11e8-972a-53e8dbfb65de.jpg)

**Comment by michaelstingl** [comment]
@soydepr Did you removed the "OAuth 2.0 Registered clients" in the "User Authentication" settings ?

**Comment by soydepr** [comment]
Sadly yes as I thought were demos.  How I fix this

**Comment by michaelstingl** [comment]
@soydepr I opened a new issue for this here: https://github.com/owncloud/oauth2/issues/163
