### ISSUE TITLE
iOS App does not remember download status apparently

### ISSUE THREAD

**Issue by voroyam** [owncloud/ios#1085]
iOS App does not remember download status apparently

### Steps to reproduce
1. Upload file via Web UI to Folder `MyFiles`
2. Make `MyFiles `offline available on your iOS device.
3. Wait until the files in the folder are synced.
4. Add new file, via 1.
5. Check the folder again on the iOS device.

### Expected behaviour
old, downloaded files should be already downloaded on the device, marked with the green circle.

only the added file should be not green, but blue, and be downloaded.
### Actual behaviour
All files appear to be **not downloaded**, and are all **blue** and are being downloaded.

The status of the folder `offline available` is **gone**.

Tested with damkencloud 3.7.5 and iOS 12. Chrome browser was used for upload.

**Comment by ChrisEdS** [comment]
@jesmrec @jesmrec Do you need more information here?

**Comment by jesmrec** [comment]
This issue was detected in the iOS12 preliminary tests (check here: https://github.com/owncloud/ios/issues/1067) and fixed in 3.8.0 iOS version.
