### ISSUE TITLE
3.8.0 iOS App crashes constantly.

### ISSUE THREAD

**Issue by voroyam** [owncloud/ios#1089]
### Steps to reproduce
1. on your iOS Device connect to a server 10.0.9
2. Mark a folder as offline available. ( I have 5 videos in that folder, 200 MB each)
3. Go in to that folder.

### Expected behavior

I can see the content of my folder

### Actual behavior

App crashes. 

If I try to open it again, and go in to the folder, it crashes again.

Tested and reproduced with damkencloud.

**Comment by jesmrec** [comment]
i'll have a look
