### ISSUE TITLE
App crashes when creating and opening new folder (iOS App/Client)

### ISSUE THREAD

**Issue by flomasteris** [owncloud/ios#1091]
Hello,
I've been having issues with this for a long time. 
So in my work I have to take pictures of the certain things and create new folder in ownCloud server and upload photos to that folder.
The problem is that when I create folder and try to open it ownCloud instantly crashes/shuts down. I have to reopen the App and go through it to find that specific folder.
(P.S When I create folder and wait for a bit then try to open. Then it doesn't crash. But if I try to open folder instantly it just crashes)
I've been suffering from this since iOS 10.3.3
I don't know if this problem exists only on iPhone 6 maybe lack of optimization or something but I have tried on iPhone 8 and the problem is same.
Just wanted to report this in case this might be real bug and developers might look in to it. Because it gets frustrating when using this app all day every day.

**Comment by michaelstingl** [comment]
@flomasteris Thank you very much for reporting this issue! Could you send the crash log to apps@owncloud.com?

> 1) Open Settings app
> 2) Go to Privacy, then Diagnostics & Usage
> 3) Select Diagnostics & Usage Data
> 4) Locate the log for the crashed app. The logs will be named in the format: `<AppName>_<DateTime>_<DeviceName>`
> 5) Select the desired log. Then, using the text selection UI select the entire text of the log. Once the text is selected, tap Copy
> 6) Paste the copied text to Mail and send to apps@owncloud.com

**Comment by flomasteris** [comment]
> @flomasteris Thank you very much for reporting this issue! Could you send the crash log to [apps@owncloud.com](mailto:apps@owncloud.com)?
> 
> > 1. Open Settings app
> > 2. Go to Privacy, then Diagnostics & Usage
> > 3. Select Diagnostics & Usage Data
> > 4. Locate the log for the crashed app. The logs will be named in the format: `<AppName>_<DateTime>_<DeviceName>`
> > 5. Select the desired log. Then, using the text selection UI select the entire text of the log. Once the text is selected, tap Copy
> > 6. Paste the copied text to Mail and send to [apps@owncloud.com](mailto:apps@owncloud.com)

Report Sent to given email
