### ISSUE TITLE
As an owncloud IPhone/IPad user I want to invite other when creating new calendar events

### ISSUE THREAD

**Issue by onewaypub** [owncloud/ios#110]
Actually it is not possible to invite people during creating new calendar events. 

Example: http://www.imore.com/how-send-calendar-event-invitations-using-iphone-or-ipad

A workaround for that would be a shared calendar. But this is only a workaround for people how have permanently shared events. If you want to invite a friend its not a valid opportunity

Requirements/Acceptance test:
1) Create a calendar event and invite others during the creation
2) Others receive the invitation
3) Other accept or deny the invitation
4) calender event will be updated 

![how_to_calendar_invites_screens_01](https://f.cloud.github.com/assets/3080663/1006917/efdbee6e-0af6-11e3-9ef9-6917070e50a7.jpg)
![how_to_calendar_accept_screens_03](https://f.cloud.github.com/assets/3080663/1006918/f5e92a24-0af6-11e3-833b-4e09c3c8944a.jpg)

**Comment by michaelstingl** [comment]
calendar is not in scope of the ownCloud iOS app
