### ISSUE TITLE
Option to select all pictures in "upload photo/video"

### ISSUE THREAD

**Issue by igormcoelho** [owncloud/ios#1103]
### Steps to reproduce
1. Open App and select upload photo/video
2. Select one folder
3. Now you have to manually select every photo (from 2500 photos in my case)

### Expected behaviour
There should be a button like "select all", or any other easier way to select 2500 pictures. Another option is to allow InstantUpload to upload past images...

### Actual behaviour
I have to manually click 2500 photos.

### Server configuration
**Web server:**

**Database:**

**PHP version:**

**ownCloud version:**

**Storage backend (external storage):**

### Client
**iOS version:**
iPhone XS

**ownCloud app version:**
iOS 3.8.0 cdc72af

**Device model:**
iPhone XS

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
 
### Tell us what could be improved:
Please improve this! this will help a lot users to submit older pictures not send by InstantUpload. Thanks!

**Comment by michaelstingl** [comment]
This got implemented in the successor of this ownCloud app. You can test with the TestFlight beta. We'd love to hear your feedback!

Here you can find more information:
- https://owncloud.org/news/working-brand-new-ios-app-sdk/
- https://central.owncloud.org/t/there-are-new-features-for-the-ios-beta-app/16992
