### ISSUE TITLE
Prepare deprecating "old" iOS App

### ISSUE THREAD

**Issue by hosy** [owncloud/ios#1109]
Because we releasing the new iOS app very soon, we need to point the user in the current iOS app to the new app.
We need some steps to prepare deprecating the old iOS app:

## Ideas
- Show a view on first launch after update, with some information about the new iOS app and link against the new app
- If the user dismiss this view, it should be possible to reach this view via the app settings
- update the app icon to differentiate to the new iOS app (suggestion: grey out app icon)

### Info View
This view could also include a WebView to show the release blog entry or a link to open as a SFSafariViewController.

### Client
**ownCloud app version:**
3.8.1

**Comment by michaelstingl** [comment]
@hosy Could you imagine some inter-app-linking to send your server-url and username to the new app or request it in the new app from the old app? (maybe not the password and the data itself)

**Comment by hosy** [comment]
> @hosy Could you imagine some inter-app-linking to send your server-url and username to the new app or request it in the new app from the old app? (maybe not the password and the data itself)

yes, could be possible, but this will need an update for the new iOS app

**Comment by michaelstingl** [comment]
> yes, could be possible, but this will need an update for the new iOS app

Yeah, maybe we should support this with a 1.1 version… ==> new issue

**Comment by hosy** [comment]
We could use the Guide view, which is used for onboarding to show some steps what is new in the new iOS app. 
Benefit:
- already exists
- teasing new features will encourage the user to switch

@michaelstingl what do you think?

![Simulator Screen Shot - iPhone X - 2019-06-26 at 09 44 54](https://user-images.githubusercontent.com/736109/60161098-19f95e00-97f7-11e9-9375-9b8888105870.png)

**Comment by michaelstingl** [comment]
Yeah, perfect! Need to be shown to ALL users, not only fresh installs. Please also a branding option for this (default: off)

**Comment by hosy** [comment]
Is already branded and would be shown for all users, after they open the updated version. I will implement some feature screens.

**Comment by hosy** [comment]
Here is a suggestion for a "disabled" app icon:

![disabled_icon](https://user-images.githubusercontent.com/736109/60167032-8fb6f700-9802-11e9-887c-052bb073cc15.png)

**Comment by michaelstingl** [comment]
> Here is a suggestion for a "disabled" app icon:

@ChrisEdS What do you think?

**Comment by ChrisEdS** [comment]
I like the idea! The other possibility would be to provide only the cloud with less opacity. Here is an example with 20%.

![ownCloud_ios_legacy](https://user-images.githubusercontent.com/33026403/60176927-ee3aa000-9817-11e9-862c-d3205a9c9028.png)

**Comment by michaelstingl** [comment]
![background](https://user-images.githubusercontent.com/214010/60203997-3eccf000-984e-11e9-8181-7047ed8652c2.png)

Makes this clear which version is what?

**Comment by ChrisEdS** [comment]
We should go with the grey background.

**Comment by hosy** [comment]
Here is how the update guide looks like. It will be shown to all users after the first start, when they updated. It is also reachable in the settings view.
@michaelstingl does it work for you:

![ezgif-4-ffbd3a2e2227](https://user-images.githubusercontent.com/736109/60248252-8725f580-98c2-11e9-89a2-d26a9d51d7ca.gif)

**Comment by michaelstingl** [comment]
> @michaelstingl does it work for you:

@hosy Yeah, very cool! Maybe check wording with @spangtey

**Comment by michaelstingl** [comment]
> We should go with the grey background.

Please check, it should not look like an app that is inactive because of limited **Screen Time** or because of the "Offload Unused App" feature.

**Comment by MichaelvanLaar** [comment]
> Please check, it should not look like an app that is inactive because of limited **Screen Time** or because of the "Offload Unused App" feature.

Did you consider something like a little banner in one of the upper corners, with "Legacy" or "for iOS 10 or lower" or something similar on it? Then you could use the blue background, the grey cloud and have a much clearer distinction, also in the App Store in case both apps appear in a listing.

**Comment by ChrisEdS** [comment]
Like this?

![image](https://user-images.githubusercontent.com/33026403/60271700-1ba84c00-98f3-11e9-8348-4be923d7aaac.png)

**Comment by MichaelvanLaar** [comment]
@ChrisEdS Yes. I just don't know if "legacy" can give any negative impression in this context. Because we want users with older iOS version to still use this app. But everything more explanatory is too long, I guess.

**Comment by hosy** [comment]
@MichaelvanLaar is the text in the update view ok? Look at the gif above?

**Comment by MichaelvanLaar** [comment]
@hosy Had to find a way to play and pause the GIF, not a default thing on a Windows machine. ;-) That's why it took a few minutes longer.

Just a few suggestions for consideration.

**In general:**
Headlines/captions either always in title case or olways in sentence case. (I always use http://titlecase.com/ with the default settings and use the "Title Case" output four headlines on our websites etc.)

**Regarding specific slides:**

_Menu item:_
- "Discover our new iOS App" -> I'd rather be more specific: "Discover the new ownCloud App for iOS 11+"

_Slide 1:_
- "iOS ownCloud App made new!" -> "Discover the new ownCloud App"
- "Discover our new iOS App" -> "Rebuilt from scratch for iOS 11+"

_Slide 4:_
- "Complete Data Overview" -> "Complete overview at a glance"

_Slide 5:_
- "Access to all your accounts" -> "Easily access all your clouds"

Otherwise: Perfect! :-)

**Comment by hosy** [comment]
@MichaelvanLaar thank you! I think the sentence for the menu item is too long, but will check it.

_Slide 1:_
I will use your suggestions.

_Slide 5:_
These captions we are currently using on the AppStore Screenshots. I thought it make sense to use the same!?

**Comment by MichaelvanLaar** [comment]
@hosy Then keep the text on slide 5 to keep it consistent.
