### ISSUE TITLE
"Server not found" using personal SSL certificates

### ISSUE THREAD

**Issue by xyza** [owncloud/ios#117]
Hello,

I am getting the following error while trying to connect from the iOS client:

![img_0554](https://f.cloud.github.com/assets/5508120/1185864/bc6a061c-22cd-11e3-8a82-9aa232b605a5.PNG)

The server (lighttpd) is configured to accept connections only from browser having personal certificates installed. The corresponding certificates are installed on iOS in Settings > General > Profiles. Using Safari the URL can be accessed (however Chrome for iOS cannot access it).

The server does not log anything in the access log, but in the error log i get the following "2013-09-21 17:43:12: (connections.c.305) SSL: 1 error:140890C7:lib(20):func(137):reason(199)".

Is this something that can be solved?

**Comment by nasli** [comment]
Closed for inactivity, if it is still an issue please reopen. Thanks!
