### ISSUE TITLE
iOS app connection data is not included in iTunes full backup

### ISSUE THREAD

**Issue by rakekniven** [owncloud/ios#121]
Hello,

my iTunes is taking a full backup of my device and stores it locally on my computer.
Using password stores connection data like credentials as well.

Last week I changed my device from iPhone 4s to 5s.
Procedure:
Connected 4s
iTunes did a full backup
Disconnected 4s
Connected 5s
Selected option to restore device from full backup.
Entered backup password
Restore took place
Device was ready to use.

Problem:
After launching oc app on 5s for the first time it asked me for connection details.

For many other apps and apple homemade apps there was no need to enter someting. Everything was there.

Does oc app stores connection details different then other apps do?

**Comment by hodyroff** [comment]
@nasli Lets focus on the original description - is this possible or fixed in newer versions anyway?

**Comment by nasli** [comment]
@hodyroff this is something we need to discuss about, if we want to store all the connection set up to iCloud or not. And at least this should be set as an setting options to make the user take the final decision if they want to store out these sensible data.

It is not a bug, is an enhancement and a platform security decision to discuss.

**Comment by rakekniven** [comment]
Closed due to inactivity
