### ISSUE TITLE
ownCloud for iOS - add fingerprint support for authentication

### ISSUE THREAD

**Issue by j-ed** [owncloud/ios#124]
Environment:
- ownCloud for iOS v2.21
- iOS 7.0.3

At the moment you can only secure access to you ownCloud data by setting an App-PIN. On iPhone 5S with iOS 7.0.3 it is possible to optionally use the fingerprint for authentication purposes. Support for this option should be added because it makes it easier to access the ownCloud content.

**Comment by JimLoose** [comment]
@rperezb any updates concerning the discussion with the product owner?

**Comment by rperezb** [comment]
@JimLoose we will include this on future versions of the app, thx for the suggestion

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by otbe** [comment]
Eh 2013 ? Any update so far?
It's quite annoying to enter a pin. :(

**Comment by javiergonzper** [comment]
@otbe do not worry it will be merged soon :wink:

**Comment by rperezb** [comment]
Closed via: https://github.com/owncloud/ios/pull/567
