### ISSUE TITLE
move file dialog should be improved

### ISSUE THREAD

**Issue by j-ed** [owncloud/ios#130]
Environment:
- ownCloud for iOS v3.0.0
- iOS 7.0.3

If you want to move a file in the ownCloud app, a dialog is opened to select the destination folder. This dialog differs from previous or other dialogs because
a) the _cancel_-button is shown in the upper right corner and not the upper left corner.
b) a _create folder_ button is shown in the lower left corner and overlaps the text in the middle of that menu bar.

Current layout:
![20131031_owncloud_ios_datei_verschieben](https://f.cloud.github.com/assets/2572764/1444372/2c562ddc-4206-11e3-9b0a-4e3b03fc2cb0.png)

Recommended layout:
1. Move the _cancel_-button to the upper left corner.
2. Add a _+_-button to the upper right corner which allows to create a new folder.

![20131031_owncloud_ios_datei_verschieben-neu](https://f.cloud.github.com/assets/2572764/1444380/6a2a3db0-4206-11e3-8776-5bbf9b436b29.png)

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
