### ISSUE TITLE
.xlsm file support

### ISSUE THREAD

**Issue by ghost** [owncloud/ios#142]
Hi,
on your app for iphone, .xls files are supported but not ,xlsm. Can you modify your app for iphone to be able to read xlsm files. On dropbox we can read xlsm files but not in owncloud. This file contain macro, but we just want to be able to read it without macro. 
thanx

**Comment by nasli** [comment]
Hi @enyrix,

with the new document provider feature incorporated in the last version 3.4  you can open and edit your .xlsm file within another app that support it like Office.

Thanks for your suggestion, we will keep on mind for future.
