### ISSUE TITLE
ownCloud for iOS - iPhone restore from a backup doesn't restore ownCloud app settings

### ISSUE THREAD

**Issue by j-ed** [owncloud/ios#143]
## Expected behavior

When you restore your iPhone from a backup all ownCloud app settings, like server name, login, password, PIN, etc., should be restored too.

## Actual behavior

When you restore your iPhone from a backup none of the ownCloud app settings are  restored and they need to be entered again.

#### Server Configuration

OS: Linux 2.6.24-24
Web server: Apache2 2.4.6
Database: MySQL 5.1.72
PHP version: 5.4.21
ownCloud version: 6.0 beta5

#### Client Configuration

ownCloud for iOS v3.0.0
iOS 7.0.4

**Comment by guruz** [comment]
Dup -> https://github.com/owncloud/ios/issues/121
