### ISSUE TITLE
thumbnails for image formats (jpg, png...) for downloaded files

### ISSUE THREAD

**Issue by olivtt** [owncloud/ios#149]
I think it would be fine to have a thumbnails for jpg, png...files 
This feature is implemented in Dropbox. for example et I miss it in owncloud on ios.
thanks

**Comment by nasli** [comment]
This feature it is right now under QA process and will be within next release 3.4.7.

**Comment by rperezb** [comment]
Fixed via: https://github.com/owncloud/ios/pull/549

**Comment by rperezb** [comment]
@carlaschroder new feature for the iOS app

**Comment by carlaschroder** [comment]
\o/

**Comment by carlaschroder** [comment]
@rperezb What is the release date?

**Comment by jancborchardt** [comment]
Yooooo finally! Nice work! :)

**Comment by rperezb** [comment]
We haven't decided a release date yet

cc @MTRichards

**Comment by MTRichards** [comment]
More as soon as we look at the backlog / review what is complete / schedule a release based on the best timing.

**Comment by TylerTemp** [comment]
Hi, what about leave this issue open till release to app store?

**Comment by rperezb** [comment]
@jesmrec what do you think?

**Comment by jesmrec** [comment]
@TylerTemp the release is already done, that is an old conversation. Currently the iOS app supports thumbnails for both formats, regardless the pic is donwloaded or not.

We have opened an issue in core for thumbnails in servers with OAuth2 auth, it you want to track that problem or you are affected: https://github.com/owncloud/core/issues/29914
