### ISSUE TITLE
error "sharing not enabled on server" with build 3.1.1

### ISSUE THREAD

**Issue by clayton256** [owncloud/ios#167]
I was really excited sharing was added as a new feature to the iOS app.

Unfortunately, I can't see how to make it work. If I swipe a file, I get the bar to "open with, delete, rename, etc". If I tap "share link" I get an error box stating: "Sorry, the feature is not enabled on your server..." 

I can share from my owncloud web page so I'm guessing I've correctly enabled sharing on the server. 

I don't see any owncloud or apache errors in my logs. 

I'm running owncloud 5.0.10 on apache 2.2.6 and linux and I have iOS 7.0.6

Any ideas are greatly appreciated.

Thanks!

**Comment by rperezb** [comment]
Closed for inactivity, if needed, please reopen
