### ISSUE TITLE
Add a search field above the TableView - text search

### ISSUE THREAD

**Issue by georgehrke** [owncloud/ios#17]
Please make the files searchable by adding a search field right above the TableView.
(Like in the contacts app http://media.idownloadblog.com/wp-content/uploads/2012/02/iphone-contact-list.jpg)

UPDATED 05/09/17 @nasli
As final Design explained by @ggdiez [here](https://github.com/owncloud/ios/issues/927#issue-249615266) a new search bar is going to be added in the top of file list view. 
This new bar is going to include also the shortcuts to sort the file list view.

IMPORTANT: As first approach, this search tabbar are going to filter files on the current local folder that contains the text entered in its file name. 

For search over all your onwCloud server files will require an API that will be available on future versions of ownCloud. Meanwhile we can allow the search over current folder.

![newfilelistview](https://user-images.githubusercontent.com/6570505/30060582-51dadb88-9244-11e7-96a5-fbe9aada01c8.png)

TASKS
- [ ] [DEV] Add search bar in the top of file list view
- [ ] [DEV] Placeholder with the wording "Search on this folder" 
- [ ] [DEV] Filter local files on the current folder if their names contains the text introduced (as first approach)  
- [ ] [NTH] Add menu icon to sort file list view
- [ ] [QA] Test plan

**Comment by scream88** [comment]
Same for me. Any ETA when search is avaiable in iOS App?

**Comment by javiergonzper** [comment]
@scream88 I think that the ownCloud server do not have an API of search so the iOS or Android app can not make search on the server by now...

**Comment by jancborchardt** [comment]
@DeepDiver1975 @PVince81 @butonic do we not have a search API from the server?

**Comment by butonic** [comment]
nope, still not implemented.

**Comment by gwes** [comment]
+1 for this feature. (as well as #391)

filtering / searching would make the iOS app loads more usable for larger directories.

Coding skills not so great but I'm happy to help test things

**Comment by jancborchardt** [comment]
@rperezb @MTRichards @ggdiez @javiergonzper can we move this community request up? (It’s similar for Android.)

**Comment by MTRichards** [comment]
As we have no search API from the server, this would be just a search of filenames at this time. That is something we can move up, though quite a lot to do before that.

**Comment by Froster** [comment]
Is there anything on the Roadmap?

Would very  nice and helfpfull if this would be implemented.

**Comment by rperezb** [comment]
Same status, no search API from the server, backlog ftm

**Comment by Froster** [comment]
I think in the first step it would be enough to search in file names?

**Comment by MTRichards** [comment]
What we need is an API from the server to perform the search. It is on the backlog, but not with a date just yet. Of course, folks are welcome to accelerate this, but at this time we are looking at at least 9.1 to resolve this

**Comment by supportreq** [comment]
@rperezb @MTRichards are we having this in the upcoming release? or even a simple tableview based filter?

**Comment by MTRichards** [comment]
Right now, we are planning on a rather heavyweight elastic search cluster text search in 9.1 - hopefully this will make it. Then we can provide an API to this search and get the proper search text. However, this does require a rather extensive elastic search cluster setup before this can work...may not he all that helpful.

**Comment by jancborchardt** [comment]
So, how difficult is a tableview based filter for the current folder? @rperezb

**Comment by rperezb** [comment]
The key thing is that, if we want to implement this - just searching on the current folder, we have to be very clear of this fact in order to avoid misunderstanding.

As @MTRichards has said for a general search (whole server) we have to wait for the server API.

@jancborchardt in terms of complexity, it's not the problem, can you please suggest us a design idea of how you would do it?

**Comment by nasli** [comment]
In that case, I would suggest a placeholder with "search on this folder"
![search](https://cloud.githubusercontent.com/assets/6570505/14486726/c910061a-015e-11e6-85b4-ee292a61b0cd.png)

**Comment by supportreq** [comment]
@nasli looks good.. this will do for the time being

**Comment by jancborchardt** [comment]
Yup @nasli, good call. To keep it short I would suggest »Search in folder«.

**Comment by supportreq** [comment]
@nasli @rperezb are we having this anytime soon?

**Comment by NicolaiErtl** [comment]
+1

**Comment by rperezb** [comment]
@supportreq @N1TeSH1FT currently we are working on fixing some issues related to the latest iOS version and release a new version with this.
Probably, within the next version we will work on improving the management of some errors such as:
- https://github.com/owncloud/ios/issues/714
- https://github.com/owncloud/ios/issues/687
- https://github.com/owncloud/ios/issues/494

We do agree on the importance of this feature, we have this on the list.
We may follow the development status thanks to the milestones and taking advantage of the zenHub board, we try to keep it updated!

**Comment by nasli** [comment]
Related on Android: https://github.com/owncloud/android/issues/695

**Comment by Kawohl** [comment]
[00006794](https://na25.salesforce.com/5003100000ikV2G)

**Comment by Kawohl** [comment]
@pmaier1 FYI

**Comment by CorneelDragon** [comment]
From SURFdrive (25.000 users) also a +1 for this for the reasons mentioned (enterprise context with a lot of files).

**Comment by nasli** [comment]
This is in our roadmap and we are currently working on improving the file list view.
Updated first comment with the latest designs. :)

**Comment by nasli** [comment]
Keep in mind that for search over all your onwCloud server files will require an API that will be available on future versions of ownCloud. Meanwhile on mobile clients we can allow the search over current folder.

**Comment by CorneelDragon** [comment]
looks good, thanks for the update! And let's hope future version of the server will enable a 'complete' search

**Comment by michaelstingl** [comment]
This is a first step on the server side: https://github.com/owncloud/core/pull/26507 . For full server this side support, this needs to be fixed: https://github.com/owncloud/core/issues/13915

**Comment by michaelstingl** [comment]
Search API has been implemented on oC server and is planned to be included in oC 10.0.10: https://github.com/owncloud/core/issues/25373#issuecomment-400967608

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94

The new iOS app already got a search field to filter files in the current folder (https://github.com/owncloud/ios-app/pull/64) and real search is one of the next items on the roadmap: https://github.com/owncloud/ios-app/issues/53
