### ISSUE TITLE
ownCloud for iOS - folders should be sorted above files by default

### ISSUE THREAD

**Issue by j-ed** [owncloud/ios#171]
## Expected behavior

Folders should be displayed above files by default when ownCloud data is displayed.

## Actual behavior

At the moment, ownCloud data is sorted alphabetically and doesn't differentiate between
folders and files. The app should show folders above files by default or should allow
to change the sorting.

#### Server Configuration

OS: Linux 2.6.24-24
Web server: Apache2 2.4.7
Database: MySQL 5.1.73
PHP version: 5.4.23
ownCloud version: 6.0.2

#### Client Configuration

ownCloud for iOS v3.1.1
iOS 7.1

**Comment by nasli** [comment]
Thanks for your suggestions.
Related with sorting files and folders you can keep up to date also in #318

**Comment by guruz** [comment]
Let's discuss in https://github.com/owncloud/ios/issues/481
