### ISSUE TITLE
Long filenames impossible to view

### ISSUE THREAD

**Issue by almonie** [owncloud/ios#180]
I often work with files with long filenames where only the middle part of the filename is different. So in the iOS app it’s impossible to differentiate between the files. I would like some way to see the whole filename. Either by a scrolling filename with a wider display, or via an extra file information pop up window. This pop up could also show additional information about the file such as if it’s shared, access permissions, created/modified time. Version information etc.

**Comment by rperezb** [comment]
Another solution that we talked about was to add a new option: information.

**Comment by rperezb** [comment]
Indeed, this solution was suggested too on: https://github.com/owncloud/ios/issues/129 let's track there the status
