### ISSUE TITLE
OwnCloud IOS v.3.1.2 app bugs & feedback

### ISSUE THREAD

**Issue by ferryarman** [owncloud/ios#185]
* These following errors happened on Ipad (IOS 7.1.1)

Firstly, I logged in using admin account on my shared hosting owncloud.

1). After uploaded a photo & clicking on share link, it gave me error message:
"You don't have permission to complete the operation". Same issue, when you tried to share on folder.

2). When I chose the photo to be "Delete from device and server", the Loading spinner kept appearing (never ending) until I manually closed the app. Strangely, it worked ok on Ipod touch.

3). When I chose the photo to be "Delete from device", the image kept appearing on the left frame & still able to be selectable.

* These following errors happened on Ipod touch (IOS 7.1.1)

Firstly, I logged in using admin account on my shared hosting owncloud.

1). After uploaded a photo & clicking on share link, it gave me error message:
"You don't have permission to complete the operation". Same issue, when you tried to share on folder.

2). This is only minor issue, when you upload one or more big files (eg > 1 megs), there's no progress indicator & the loading spinner only appeared after the files have been successfully uploaded. I could be wrong.

3). This is just feedback, when clicking on Help, it redirected to the front page of owncloud official website. Perhaps it would be better, if there's a tailored page for mobile site, otherwise the font of the contents is too tiny & need to pinch the screen.

**Comment by enoch85** [comment]
@ferryarman Is this issue fixed in recent versions?

**Comment by ferryarman** [comment]
@enoch85: I will check it over the weekend & let you know.

**Comment by rperezb** [comment]
Closed for inactivity, if this is still an issue, please reopen
