### ISSUE TITLE
animated gif just static, doesn’t play

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#19]
When trying to view animated gifs I downloaded with the client, they don’t play but just show the first frame. Gif in question:
![](http://memeorama.com/wp-content/uploads/2012/07/thumbs-up-gif.gif)
(I guess you’ll agree it’s way more awesome when animated.)

**Comment by hodyroff** [comment]
Please test with the newest version. Issue still existing? @nasli

**Comment by rperezb** [comment]
Yes, this is still not developed neither estimated

**Comment by hodyroff** [comment]
Would be great to get an estimate in the next weeks ...

**Comment by rperezb** [comment]
@ggdiez your input is appreciated

**Comment by ggdiez** [comment]
We can use this https://github.com/Flipboard/FLAnimatedImage 
It seems perfect for we need and easily to add in ownCloud iOS app. 
If we want to integrate it in our Image Gallery we will have more work. 
But the first step can be integrate it in a single way.

**Comment by ggdiez** [comment]
@jesmrec you can test in add_gif_support branch

**Comment by jesmrec** [comment]
Now GIFs are supported by iOS app.

Approved

**Comment by jesmrec** [comment]
Feature merged.
