### ISSUE TITLE
Creating files in iOS app

### ISSUE THREAD

**Issue by tranquilityatlum** [owncloud/ios#195]
It would be much easier if while on the go I could create text documents instead of having to be on the web interface just to add a text document to edit on my mobile devices.

PR: https://github.com/owncloud/ios/pull/648

TASK
- [X] [DEV] Add create text files feature @nasli
- [X] [QA] Validate @jesmrec 
- [X] Merge branch "add_new_txt_documents" @mRoRo

BUG:
- [x] Status bar of the text editor is shown in black https://github.com/owncloud/ios/issues/670 @mRoRo [FIXED]
- [x] App crashes when the txt file is saved and the session expires https://github.com/owncloud/ios/issues/671 @nasli [FIXED]

**Comment by MTRichards** [comment]
Cool! Looking forward to editing too :)

**Comment by nasli** [comment]
This feature is under QA process here https://github.com/owncloud/QA/issues/226
