### ISSUE TITLE
Unable to return to the list of files after downloading a file on iPad

### ISSUE THREAD

**Issue by ashleydemers91** [owncloud/ios#197]
I am running iOS 7.1.1 with the OwnCloud app version 3.1.3, using both an iPad 2 and iPad air.  When viewing/downloading files in portrait mode on the device after scrolling through the document the user is occasionally unable to return to the view of the list of files while viewing that open document when the file is downloaded for the first time, and this does not appear to be an error loading the document because once this bug appears the user is unable to view the list of files until the user either closes the app or views the document in landscape mode.  Is this a known issue?

**Comment by hodyroff** [comment]
Does this issue still exist in the newest version?

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
