### ISSUE TITLE
Ability to view text files (and maybe edit them)

### ISSUE THREAD

**Issue by rakekniven** [owncloud/ios#2]
For dropbox there is an 3rd party app.
Maybe you can do it inside.

**Comment by haeringer** [comment]
As an aside - of course it would be great to have this feature on Android, too. Does it make sense to open a separate issue at [owncloud/android](https://github.com/owncloud/android) or are the features of both apps aligned anyway?

**Comment by javiergonzper** [comment]
@haeringer no, the issues are not aligned you should open a new one on the Android repository :+1: but check before that it does not exist in order to not duplicate the issue.

**Comment by jancborchardt** [comment]
The related Android issue already exists at https://github.com/owncloud/android/issues/88

**Comment by nasli** [comment]
Within iOS app is possible to preview text files and in next releases will be able to create New txt files #195. 
To Edit text files let's keep tracking #486 
For preview more file types let's continue here #68
