### ISSUE TITLE
Clarify if a shared item is owned by you or someone else

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#200]
Currently on the mobile apps it’s not clear if an item was shared by you or with you. We need some way to distinguish that.

We should do that using the icons on the right of the row. (Because we shouldn’t show 3 icons there then, we should not duplicate the globe icon there because it’s already shown as the folder icon.) We need two icons for:
* this item is owned/shared by you
* this item is owned/shared by someone else

cc @owncloud/designers @MTRichards @rperezb

**Comment by nasli** [comment]
Hi @jancborchardt, now there are different icons :)
![sharedicons](https://cloud.githubusercontent.com/assets/6570505/8546223/1ce7dbfe-24b6-11e5-9d53-e32c2d4d1e66.png)

**Comment by jancborchardt** [comment]
@nasli um – the top icons is for a file being shared by link (hence the »link« icon). And the bottom one is for it being shared internally. That’s how we use the icons in the web interface and I hope the apps do the same cc @rperezb @davivel @javiergonzper 

The differentiation of files shared by or with you is less important.

**Comment by davivel** [comment]
Hi, Jan.

In Android, for the moment, we are following the same approach as in the web UI, we show a single icon. In iOS, right now, two 'share' icons may be shown on the right side; the top one may be the link or the angle (share by you via link Vs shared by you with user/group); the bottom one will always be the angle (shared with you by other user).

**Comment by jancborchardt** [comment]
In iOS it should be the same as on Android, same as in the web interface. The web interface is always the blueprint.

**Comment by rperezb** [comment]
@jancborchardt yes, the plan is to get to the web interface, adding *shared* if you are the owner or *the owner name* if it has been shared with you.
However, this is not expected within the next version, incremental development! ;)
