### ISSUE TITLE
Accessibility in IOS-Client

### ISSUE THREAD

**Issue by sebastian2012** [owncloud/ios#201]
Hi!

A lot of Buttons in the Owncloud-Client for Iphone and Ipad are not correctly labeled. 
This is required for using the APP with screenReader VoiceOver
For Example:
If you have opened a Picture, and want to go back to the File-tree, the Back-Button is labeled "root". Other Buttons are not Labeled.

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Accessibility in the new iOS app is already better than in the old one. We'd love to hear your feedback!

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
