### ISSUE TITLE
No sharing from ios app if admin enforces password protection

### ISSUE THREAD

**Issue by autrui** [owncloud/ios#204]
If an OC7 admin has enabled "Enfore password protection" for sharing via (public) links,
you can't share files anymore via public links using the iOS app.

OC admin log excerpt:
"Error 	OCP\Share 	You need to provide a password to create a public link, only protected links are allowed"

The **iOS app needs an option to set a password** and preferably an expiration date.

**Comment by nasli** [comment]
Hi @autrui, share link with a protect password will be available within version 3.4.1
