### ISSUE TITLE
View of all downloaded files - with possibility to delete them all

### ISSUE THREAD

**Issue by muetze-online** [owncloud/ios#207]
Space on iOS-Devices is rare, so i would like to have a view on all downloaded files - and the possibility to delete one or all of them.
Deleting of downloaded files is not easy: I have to remember, which files I downloaded to my device, navigate to that file in my folders and delete the local version - not very handy.

**Comment by nasli** [comment]
Right now it is also possible to delete all downloaded files per account going to:
Settings, select menu option per account, select "Clear cache". 
This will erase all your local data downloaded in your device.

**Comment by nasli** [comment]
For downloaded view let's keep tracking here #183
