### ISSUE TITLE
ios client app: not able to synch changes back

### ISSUE THREAD

**Issue by timmie** [owncloud/ios#210]
Disclaimer:
Maybe this is a general problem I personally have with the file access in iOS client app which  currently only allows read acces to synched files...

I would like to see the following workflow with at least ascii files (*.txt, *.rst, *.py, *.css):

1) synch
2) open in text editor
3) edit & change or even rename
4) change get synch back to the server for editing on other devices or web

See also:
http://forum.owncloud.org/viewtopic.php?f=24&t=22110

Just as an example:
AirFile opens an inline text editor when opening a text file allowing to edit and upload to the same file in owncloud.
It even opens rst-files in the text editor!

So my question: what is the added value of the app over other apps such as air file if it cannot offer the colaboration features?

P.S.: taken from: https://github.com/owncloud/mirall/issues/1935

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
