### ISSUE TITLE
favourites: also folder not only file

### ISSUE THREAD

**Issue by timmie** [owncloud/ios#216]
in the iOS app, please make it possible to favourite not only a single file but also a specfic folder like the iPad exchange folder etc.

Thanks

**Comment by rperezb** [comment]
We have started working on this feature, first step is to implement download folder option, https://github.com/owncloud/ios/issues/393

**Comment by rperezb** [comment]
Work in progress on https://github.com/owncloud/ios/tree/favorite_full_folder

**Comment by rperezb** [comment]
Done, this will be included within the next iOS versions 3.4.6
Regression test on going on https://github.com/owncloud/ios/tree/release_3.4.6
