### ISSUE TITLE
Can not authinticate against this server

### ISSUE THREAD

**Issue by Draaxdard** [owncloud/ios#224]
Hello there,
I have this Ipad where i get the following error message after entering the server adress: Can not authinticate against this server.
Installed the app on my Android and it works instantly.

Using owncloud 7.0 server with the latest php.
Any input would be nice!
Thanks.

**Comment by octlabs** [comment]
Apache Log:
Mac Desktop Client: "PROPFIND /remote.php/webdav HTTP/1.1" 207 8190 "-" "Mozilla/5.0 (Macintosh) csyncoC/0.91.5 neon/0.30.0"
Thunderbird: PROPFIND /remote.php/webdav/ HTTP/1.1" 207 300 "-" "Mozilla/5.0 (Macintosh) mirall/1.6.1
----> No Errors :)

iPhone: PROPFIND /remote.php/webdav/ HTTP/1.1" 500 20 "-" "Owncloud iOs Client/3.3.2 (iPhone; iOS 8.1.2; Scale/2.00)
IPad: PROPFIND /remote.php/webdav/ HTTP/1.1" 500 20 "-" "Owncloud iOs Client/3.3.2 (iPad; iOS 8.1.2; Scale/2.00)"
----> Still Error 500 :(

ownCloud 7.0.4 (stable) PHP 5.3.29,  GeoTrust Wildcard SSL Cert
All clients are in the same LAN an connect to my internet server, no proxy, no firewall.

All debugging setting on.

I also have on the same server (only other domain/vhost) on another domain with ownCloud 7.0.1 (stable) without update. after updating 7.0.4 it is also working! 

Last time with this bug I rest all data from the web server an re-sync everything. I'm not sure that i also did a database reset. But that can't be a solution!?

Any reproduce or retrace in this issue?

**Comment by octlabs** [comment]
Found a solution to fix my current problem:
In table 'oc_share_external' was a obsolete entity of an other OC Server.
After remove this entity in the SQL database it is working also on iOS.
btw. I wasn't able to 'unlink' this 'folder' in the OC web backend. So i used the database directly.

**Comment by rperezb** [comment]
This should be fixed within the latest update 3.4.4

If not, please reopen
