### ISSUE TITLE
PDF viewer works not with pdf-internal links since 3.3.0

### ISSUE THREAD

**Issue by Bewo** [owncloud/ios#229]
Hi,
my english ist not the best, so sorry if there is a mistake... :-)

Problem: Since 3.3.0 the PDF-viewer works not with pdf-internal links. If you click a link the page is blank and threre is no further option. In the versions before everything works fine.

Here is a example-PDF:
https://ssl.webpack.de/worlitschek.eu/bwcloud/public.php?service=files&t=d40796d9a15a7f15a6fb138c5ee5e240

Tested with iPad and iPhone both iOS 8.0.2; ownCloud 7.0.2

I use this links to navigate quickly in some pricelists, so its terrible to scroll 30 pages to get one price. :-((
Yes of course, i can open the PDF in another Viewer (PDF Expert for example) but thats terrible too if had to switch apps all the time.

**Comment by nasli** [comment]
This issue will be fixed with the new pdf viewer that will be available for the release 3.4.1

**Comment by Bewo** [comment]
It's done PERFECT in 3.4.1!! Great job - thanks so much! :-)

**Comment by javiergonzper** [comment]
@Bewo thank you for report :+1:
