### ISSUE TITLE
iOS client failed to connect to owncloud server with selfsigned certificate

### ISSUE THREAD

**Issue by patrickheinzelmann** [owncloud/ios#233]
The iOS client of owncloud display an error that it can't authenticate against the owncloud server. Error Message: "Authentifizierung mit Server nicht möglich"

I'm using a self-signed certificate, owncloud 7.0.2. and iOS owncloud client 3.3.1, but I also had the problem with owncloud 6.0.x and iOS owncloud client 3.x.x.

When I'm using the WebDav Interface "/remote.php/webdav/ " of the owncloud server via the browser, the login works without any issue.

The logs of owncloud is showing following entries for the login request of the iOS client:
Debug webdav Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found

![img_0821](https://cloud.githubusercontent.com/assets/578630/4967946/f7cf083a-682a-11e4-8acb-592eddf45b27.jpg)

**Comment by arabesc** [comment]
I have an issue with ownCloud v8.0, iOS client app v3.3.3 and self-signed certificate.
OC works without visible issues if I connect to the server from a browser (actual Firefox) or WebDAV client (like the Finder in the MacOS X).
iOS client app can successfully authenticate, it shows file list, but it fails on forced update (pull-to-refresh).
![img_0657](https://cloud.githubusercontent.com/assets/2709027/6432190/58e977d6-c05a-11e4-9501-9c698495c971.PNG)
Here's how it looks in the nginx access.log:
> 192.168.0.115 - - [01/Mar/2015:21:32:38 +0300] "GET /status.php HTTP/1.1" 200 104 "-" "Owncloud%20iOs%20Client/3.3.3 CFNetwork/711.1.16 Darwin/14.0.0"
> *192.168.0.115 - igor [01/Mar/2015:21:33:15 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1"* ***499*** *0 "-" "Owncloud iOs Client/3.3.3 (iPhone; iOS 8.1.3; Scale/2.00)"*
> 192.168.0.115 - igor [01/Mar/2015:21:33:16 +0300] "GET /ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 200 120 "-" "Owncloud iOs Client/3.3.3 (iPhone; iOS 8.1.3; Scale/2.00)"

And in the owncloud.log:
> {"reqId":"f88c94c641aff925ef67a29336230c7e","remoteAddr":"192.168.0.115","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-01T21:32:49+03:00"}
> {"reqId":"f88c94c641aff925ef67a29336230c7e","remoteAddr":"192.168.0.115","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-01T21:32:51+03:00"}
> {"reqId":"f88c94c641aff925ef67a29336230c7e","remoteAddr":"192.168.0.115","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-01T21:32:53+03:00"}
> ...
> {"reqId":"f88c94c641aff925ef67a29336230c7e","remoteAddr":"192.168.0.115","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-01T21:33:13+03:00"}
> {"reqId":"f88c94c641aff925ef67a29336230c7e","remoteAddr":"192.168.0.115","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-01T21:33:15+03:00"}
> {"reqId":"f88c94c641aff925ef67a29336230c7e","remoteAddr":"192.168.0.115","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-01T21:33:17+03:00"}

**Comment by rafdalb** [comment]
Hello,

I had a similar problem with my account (using apache). It seem it is due to the link to dropbox. When I unlinked dropbox from my own cloud profile everything started working.


Attached my owncloud.log before removing Dropbox reference.

{"reqId":"a4d5a39ccd0a7f22d6253e4549b2392b","remoteAddr":"192.168.6.5","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-16T17:51:30+00:00"}
{"reqId":"a4d5a39ccd0a7f22d6253e4549b2392b","remoteAddr":"192.168.6.5","app":"files_external","message":"Error: (401) Unauthorized\n","level":3,"time":"2015-03-16T17:51:32+00:00"}

**Comment by rperezb** [comment]
Thanks for the logs, @jvillafanez does this ring any bell? thx

**Comment by jvillafanez** [comment]
@arabesc @rafdalb please, check that you can reproduce https://github.com/owncloud/core/issues/11759 in your environments. It might be related to what you are experiencing.

Fixes for that issue are available in ownCloud 8.0.3 and 7.0.5 so I would recommend update your server to one of those versions if possible.

**Comment by nasli** [comment]
@arabesc , still happening?
Check also related issue with nginx proxy https://forum.owncloud.org/viewtopic.php?f=24&t=9564&start=10

**Comment by arabesc** [comment]
@nasli, I need time to check it. I have not used ownCloud from the time of this report and now it's in inoperable state. Probably, I need to verify PF and nginx config. I will report later.

**Comment by matt407** [comment]
Hi,
i undergo the same issue. 
When I try to connect to OC 8.1 with the latested IOS app via mobile network, the connection doesn't work. If I try the same over wi-fi, it is working. This appears really strange to me. Does anyone has an advise?

**Comment by rperezb** [comment]
have you tried to access via the mobile network using a web browser to your server?

**Comment by try2codesecure** [comment]
Got the same problem with OC 8.1 and iOS 8.4. Can't connect from iOS to the Owncloud Server (with the OC app nor with the iOS browser). It works from any other system and client with certificatiion warnings (self-signed certificate).

**Comment by matt407** [comment]
Hi, 
thank you for reply.
The owncloud server is accessilble via webbrowser, caldav, carddav via mobile network. I also use the same provider (Tmobile Germany)  as the initial creator of this topic.
Due to this issue with the Owncloud app, i tried another webdav app (Crypto Cloud) to access my files via webdav - this works fine.

**Comment by raimund-schluessler** [comment]
I had the same issue with iOS 8.4 and oC8.1. It worked for a long time, but with the latest update to iOS Owncloud client 3.4.4 it stopped working. The app does not accept the self signed certificate, although it asks if it should (which I agreed to).

As a workaround I added the self-signed certificate to the trusted certificates on the iOS device. You can do so by sending an email with the certificate (in the "pem" format) to your device and installing it.
Now the app does connect again to the server.

**Comment by matt407** [comment]
Hi,
thank you Raimund. 
I did an import of the ca cert on the ios device, too. It work's now. 
However I hope for a Bugfix in this case :)

**Comment by matt407** [comment]
With Version 3.4.5 the bug isn't fixed. Is there any bugfix on the roadmap?

**Comment by rperezb** [comment]
thanks for checking the latest version.
@matt407 can you please contact us on apps@owncloud.com, it would be very helpful if you may provide to us a test account on your server so that we will be able to reproduce the error.

**Comment by matt407** [comment]
@rperezb - great, you will hear from me soon. :)

**Comment by matt407** [comment]
The issue is gone with ios client version 3.4.6

**Comment by raimund-schluessler** [comment]
Confirmed. 3.4.6. accepts the self signed certificate.
