### ISSUE TITLE
features request: sync folders, storage provider

### ISSUE THREAD

**Issue by jeby** [owncloud/ios#234]
* It would be nice if ownCloud app could biderectional sync enitre folders marked as favourite (similar to what happens with files, but for folders), propagating deletion etc. See Documents by Readdle, it does this also for webdav account such as ownCloud.
* once the folder is available offline, it could be made available via document picker from other apps

**Comment by nasli** [comment]
Hi @jeby, thanks for your suggestions.
About the sync folder is on our roadmap, however there is not an eta yet. 
About document provider feature will be available in the next version 3.4.0.

**Comment by nasli** [comment]
About sync favourite folders you can keep up to date in this issue #216
