### ISSUE TITLE
As an OC iOs user I want the top and bottom bar to be half-transparent and vanish after a while so that I can focus on content

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#236]
AC
-  The top and bottom bars must be half-transparent
-  The top and bottom bars must vanish after X second, if you are previewing a file
-  Once the bars have disappeared, by tapping on the file, they will be displayed again

**Comment by legendecas** [comment]
Is this ok?

* The top and bottom bars will vanish after scrolling down the file
* The top and bottom bars will displayed again by scrolling up
* The top and bottom bars will toggle appearing and disappearing by tapping on the file

![2017-03-09 00_00_42](https://cloud.githubusercontent.com/assets/8500303/23711670/77b32ed6-045b-11e7-8e77-7e25124e2c59.gif)

**Comment by nasli** [comment]
Great!! Looks awesome @legendecas , thanks for your contribution!!
