### ISSUE TITLE
As an OC iOs user I want any document to be downloaded just by tapping on it so that I have a quicker access to my documents

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#237]
AC:
- Currently, if you tab over a file which is not downloaded and it´s possible to be previewed within the app, it´s downloaded automatically.
- The aim of this issue is that any file, no matter whether it´s possible to be previewed or not, it will be downloaded automatically, for instance, zip files
- The current behavior of a download while remain the same, meaning this:
  +  Once the download finishes, it will be displayed automatically a pop up with those installed app that can handle it
  + It must be possible for the user to cancel the download, at the right of the progress bar, there will be a "x" icon, by clicking on it, the download will be cancelled.. 
  +  When the file is being downloaded a progress bar will be shown
  + On the file list, it will be shown a yellow arrow which means download in progress

**Comment by nasli** [comment]
Fixed, will be within the next version.
