### ISSUE TITLE
As an OC user I want to delete uploads on progress on the same way as failed uploads so that I use the same action 

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#238]
AC:
- Currently, if you want to cancel an upload in progress or in the queue, there is a cancel button, while for other uploads on the same view, the way of removing them is using the swipe menu.
- The aim of this issue is to follow the same behavior, instead of showing the cancel button, it will be removed the upload by swiping over the file, it will be shown the option detele and once you click on it, the file will be removed from the queue

**Comment by nasli** [comment]
The recent view is refreshing each time a upload finished, so the better aproach for the user experience will be leave the current cancel button. It has a quicker access. 
Closed as won't fix.
