### ISSUE TITLE
Can't connect to the server over cellular network with HTTPS - Error message occurs

### ISSUE THREAD

**Issue by Kun19** [owncloud/ios#241]
When I use the cellular network and the HTTPS protocol I'm not able to connect to the server. The authentication works without any problems but when I try to connect to the server I get an corresponding error message that I can't connect to the server.

The app is working as expected when
- I use wifi and HTTPS 
- I use the cellular network and HTTP

I'm using a self-signed certificate but I also tried to use an official certificate. The problem still exists.
I don't know if it is a server configuration problem or an app related problem.

Any input would be nice.
Thanks

**Comment by javiergonzper** [comment]
Hi @Kun19 

Sometimes we had problems with some networks because there are "many redirections".

Could you try to connect with your server using WebDav on Safari?
https://yourserver.com/remote.php/webdav/

**Comment by Kun19** [comment]
I tried connecting to my server on safari with https://yourserver.com/remote.php/webdav/ and this works !

**Comment by javiergonzper** [comment]
I think that your 3G provider have a proxy or any other redirection extra that API of iOS can not support...

**Comment by nasli** [comment]
This issue could be related with #233,
 if not, please reopen it.
