### ISSUE TITLE
Xcode can request a new iOS Development signing identity for you.

### ISSUE THREAD

**Issue by tlsion** [owncloud/ios#248]
Xcode compile-time hint this wrong, what error?What's the meaning of?

**Comment by javiergonzper** [comment]
Hi @tlsion 

To develop using a iOS real device you must to have a iOS developer account.
https://developer.apple.com/programs/ios/
Once you have the account you have to create your own Bundle Identifiers and set them on the multiple targets of ownCloud iOS App.
