### ISSUE TITLE
Feature Request: Send iOS voice memos to Owncloud

### ISSUE THREAD

**Issue by gmtex** [owncloud/ios#265]
Any way to enable sending Voice Memos to Owncloud? 

We have some users that dictate confidential information and we would like to give them a secure way to send those files from their phone/iPad to a desktop folder.

**Comment by javiergonzper** [comment]
It is very interesting, right now maybe on the app it is difficult to include it on the interface but it is something that we should study.

Thanks for your suggestion

**Comment by nasli** [comment]
Hi @gmtex, with the new document provider feature you will be able to send voice files into your onwcloud account. This feature will be included in the new release 3.4.0

**Comment by gmtex** [comment]
Great news! Our users will be really happy to stop carrying voice recorders and simply use their phones.

**Comment by nasli** [comment]
Sorry I mistaken the feature, is the new share in feature that will support to send voice files into your account. It is currently under development process and will be incorporated in next releases. :)
