### ISSUE TITLE
iOS Client - 2 GB+ files failing to upload

### ISSUE THREAD

**Issue by EducationIT** [owncloud/ios#266]
We are trying to use the iOS client to upload files that are greater than 2 GB in size (but smaller than about 5 GB).  The iOS client begins to upload and then the upload status wheel disappears and the file is not uploaded, though a file with 0 KB size is created on the server.  The iOS app uploader status shows the size of the file is: -2058538.4 KB (image attached)

ownCloud app version: iOS 3.3.2
ownCloud server version: ownCloud 7.0.4 (stable) and ownCloud 7.0.3 (stable)

Also, for files that are 512 KB or 1 GB, etc., the upload status wheel disappears after about a minute and it seems as though the upload has failed.  However, after 30 minutes or more, the files eventually appear in the iOS client and on the server.  A more reliable or verbose upload status mechanism would be helpful within the iOS app.

Thank you!

![2015-01-07_14-27-12-owncloud](https://cloud.githubusercontent.com/assets/10439576/5651886/82416ca2-9679-11e4-844f-818b92bf93fb.png)

![2015-01-07_14-31-45-owncloud](https://cloud.githubusercontent.com/assets/10439576/5651937/02d70278-967a-11e4-915b-21287cfbf839.png)

**Comment by nasli** [comment]
Hi @EducationIT, thanks for reported it, we add it to our roadmap.

**Comment by nasli** [comment]
Hi @EducationIT,

we have been tested with a lot of devices and files sizes and we can only reproduce it with the iphone 5, and files bigger than 2GB. With any other device the video is uploaded without any problem. 

Please, make sure you have enough available space in your device. You need at least the same size as the video file you are uploading.

Related to the progress bar disappears has been fixed within the new realease 3.4.4.
