### ISSUE TITLE
automatic camera upload of photos taken with iOS

### ISSUE THREAD

**Issue by JimLoose** [owncloud/ios#267]
Please add a feature to automatically sync your iOS photos with Owncloud
- would be great to replace the default Photostream which was hacked a few month ago: <http://techcrunch.com/2014/09/01/heres-what-we-know-so-far-about-the-celebrity-photo-hack/>
- Similar to https://www.dropbox.com/help/289
- Similar to Google+ App

may be duplicate with https://github.com/owncloud/ios/issues/13 (if yes please close one)

**Comment by nasli** [comment]
Hi JimLoose, this feature is in progress. The issue is duplicated, you can track the status in #13.
