### ISSUE TITLE
File list icon sometimes not responding

### ISSUE THREAD

**Issue by stonie08** [owncloud/ios#269]
This problem occurs when using the owncloud app on an iPad in portrait mode. When rapidly switching between two PDFs (may be with other formats too) the owncloud icon in upper left corner doesn't react any more. To fix it one has to turn the device 90 degrees and back again.
Steps to reproduce:
0. make sure the iPad is in portrait mode
1. browse to a folder where you have 2 different PDFs already downloaded
2. open the first one
3. rapidly tap on the background so the list goes away
4. rapidly bring up the file list again by tapping on the OC icon in the upper left corner
5. tap on the other file very fast
6. repeat steps 3 to 5 about 2 to 3 times 

Using iPad 3 with iOS 8.1.2
PDFs used had about 2MB.

**Comment by nasli** [comment]
Hi @stonie08, thanks for your commets.
It is already included on our roadmap.
That view will be replaced with a native one that will fix this issue.

**Comment by stonie08** [comment]
Good to hear, thank you

**Comment by rperezb** [comment]
Close via https://github.com/owncloud/ios/pull/360
This will be included on the version 3.4.3
