### ISSUE TITLE
"Open with" taking a long time to load

### ISSUE THREAD

**Issue by stonie08** [owncloud/ios#270]
When trying to open a PDF in another application, the "open with" button takes a very long time (about 15 seconds) to bring up the choices for applications you have.

iPad 3 with iOS 8.1.2

**Comment by ggdiez** [comment]
HI @stonie08, 

Right now we are working to fix this bug. It will be included in one of the next versions.

**Comment by nasli** [comment]
Hi @stonie08, the new version 3.4.0 will resolve that issue.

**Comment by stonie08** [comment]
Great, I'm looking forward to it
