### ISSUE TITLE
Problem with the app

### ISSUE THREAD

**Issue by splash94** [owncloud/ios#272]
Hi, I bought the owncloud app on App store to connect through my personal cloud.. When I insert the server it's all ok and the connection is established (my server is not ssl enabled so it is http://...).
Then I insert my user and my pass but the app says "Is not possible to connect to the server now". My friend with Android app can connect with the same credentials..
Can anybody help me?
Thanks
Francesco

**Comment by rperezb** [comment]
Thanks for contacting us.
Can you please check whether this keeps happening on the latest version, 3.4.1?
If so, can you please check whether there is any log on the server side when this error is shown on the iOS app?

**Comment by rperezb** [comment]
Closed for inactivity, if this is still an issue, please reopen
