### ISSUE TITLE
Link in PDF offers no 'back'

### ISSUE THREAD

**Issue by stonie08** [owncloud/ios#281]
When viewing a PDF with the Owncloud app that offers a link to a website there's no way to get back to a previous site and/or the pdf itself. One can always reopen the PDF but has to scroll to the position in the PDF again.

There should be some kind of back button that allows to get back to the PDF and the position one left of.

Steps to reproduce:
1. download a PDF with clickable URLs
2. Click on URL
3. try to get back to the PDF and the position you have been before.

Owncloud App version 3.3.2
iOS 8.1.2 on iPad 3

**Comment by ggdiez** [comment]
Essentially this issue is the same that other issue open here: #229
