### ISSUE TITLE
Could not access servers in adhoc mode with iOS 7

### ISSUE THREAD

**Issue by vervatovskis** [owncloud/ios#282]
Hi,

I am facing an issue with OwnCloud iOS client with iOS 7 in Adhoc mode (With iOS 8 all is OK).

With iOS 7 devices.

- When I run the application from XCode the application works correctly with a developer provisioning profile or with a distribution provisiong profile.

- When I archive the application for Adhoc use, and upload it into Testflight, then when I download it in devices running with iOS 7, the app could not establish connection with servers (secured and not secured one). This issue don't appear with devices running with iOS 8.

I could not locate the problem in the source code because as I said when running the app from Xcode it works fine.

Please this is very urgent!!

**Comment by javiergonzper** [comment]
It is very strange. It should work.
Did you try to install the Ad-Hoc IPA using iTunes?

Anyway, do you know that TestFlight will close at the end of February? After that you only can use TestFlight via itunes connect and only will works for iOS8.

**Comment by javiergonzper** [comment]
Witch branch are you using?

I recommend you to use the branch release_3.3.3 because the master branch contain the targets of the Document Provider that are under develop and we had problems with the Applestore to upload that code. That is way we have the release branches and targets.

**Comment by vervatovskis** [comment]
Hello Javier, Thank you for the answer, I will try with the branch release_3.3.3 and give you my feedback.

**Comment by vervatovskis** [comment]
It works with the branch release_3.3.3. Thank you Javier :)

**Comment by javiergonzper** [comment]
Great! You are welcome
