### ISSUE TITLE
[Share link] [password] As an OC user I want to be able to share a link with password so that the security is increased

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#283]
AC:
- Being the first time the link is created (it hasn´t been created on another client) when the user selects to share link, before the link is generated, it is shown a view where the user may select whether to set a password or not.

@jancborchardt we need your input for desinging this view, thx
(once this will be designed on the iOS, we will copy this to the Android repo too)

**Comment by rperezb** [comment]
As agreed, first step, being the password enable on the server, when the user selects to share by link, a popup will appear so that the user may enter the password

**Comment by MTRichards** [comment]
@carlaschroder We should have a release note that public links with required passwords will not work in 8.0.

**Comment by MTRichards** [comment]
Maybe desktop has a workaround, where they get a 403 error, the client tries to submit a password with the link to see if that works.
https://github.com/owncloud/client/commit/4849c31addc1d1c6b9a45a5487c22511d5cac83c

would that work?

**Comment by luto** [comment]
[Core seems to state the real reason](https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/controllers/sharecontroller.php#L125) for the 403 error in the body. Maybe you could read that and show the expected password dialog?

**Comment by carlaschroder** [comment]
release noted. I tested this with my Android tablet-- it fails with the message "You do not have permission to share this file"
https://github.com/owncloud/documentation/pull/879

**Comment by nasli** [comment]
For the iOS client new version 3.4.1 will be incorporated a workaround and when the client get a 403 error the app will prompt to the user for enter a password to share a link.
