### ISSUE TITLE
Is there an implementation for Carddav/Caldav in OwnCloud for iOS

### ISSUE THREAD

**Issue by vervatovskis** [owncloud/ios#294]
Hello, I am wondering if there is any implementation for Carddav/Caldav protocol in the OwnCloud iOS Library. Thanks in advance.

**Comment by javiergonzper** [comment]
I am sorry but by now it is not on our plans...

**Comment by j-ed** [comment]
@vervatovskis Afaik there is no requirement to implement the Carddav/Caldav protocol in the iOS client because iOS devices should support both protocols automatically. I've configured access to oC calendars and oC contacts several times without any problem.

**Comment by rakekniven** [comment]
Can confirm that iOS is supporting Carddav/Caldav by default and it works out of the box. No need to ship own implementation. What are your thoughts on this?

**Comment by enoch85** [comment]
Closing this as it works out of the box as @rakekniven stated ---^
