### ISSUE TITLE
Custom Agent String for iOS Client

### ISSUE THREAD

**Issue by MTRichards** [owncloud/ios#295]
As an admin I want to be able to prevent standard ownCloud apps from connecting to my ownCloud server, I want my users to use the custom ownCloud apps I have branded.

The concept here is that a quick fix with a custom user agent string through ownBrander would enable a filter on "non-authorized" clients.

Not perfectly secure for a determined user, but ok as a quick fix.

**Comment by nasli** [comment]
The iOS Client new version 3.4.1 will support a custom user agent.
