### ISSUE TITLE
Clean local cache button

### ISSUE THREAD

**Issue by cyberb** [owncloud/ios#301]
My use case:

1. iPhone full of pictures
2. Backed up to owncloud using iOS client
3. Removed pictures form the phone
4. Free space is the same as before (owncloud local cache?) 
5. Reinstalled the app to drop owncloud cache fixed free space issue.

It would be useful to have "Clean local cache" button.

Thanks

**Comment by rperezb** [comment]
Thanks for this request.
We have been talking about it, we plan to add an offline view in this view we will include a "delete all downloaded files" button

cc @jancborchardt

**Comment by tushevorg** [comment]
This would be great

**Comment by DenBeke** [comment]
+1

**Comment by rperezb** [comment]
Hi, 

We are discussing about where to set up this option, 
@jancborchardt suggested to set it after the Instant Uploads option, option 1

What about setting it after the manage accounts, just before the Instant Upload setting, so that it is closer to the accounts info, we may start a new section, something such as: Active Account Settings Option 2

![img_0173](https://cloud.githubusercontent.com/assets/1846927/8211189/05b8c60a-1516-11e5-87e2-46f208df49a0.PNG)

A third option could be to add this option on the offline view. IMPORTANT, this view is not developed yet neither estimated to be developed in the short term

What do you think?

**Comment by ggdiez** [comment]
I like the option 2, to be more detailed I could put the next:

- New section below "Add new account button" with a title with something like this: "Active_account has downloaded XX MB in your device" and a button below with a title with something like this: "Clear data".

**Comment by jancborchardt** [comment]
That’s too present – we shouldn’t clutter that view up with such technical and little used functions.

Better put it in the account details instead – when there is cache data, show a new section when you go to the details showing an entry:
> **Clear cache**
> 345 MB of locally cached data will be cleared

**Comment by tushevorg** [comment]
I suggest we should add a label describing how much space is used in total; and then a button that will move the user to another view, where he could wipe the cache for different accounts.
As well account options view should have this as well.

Apple introduced teh similar scheme in Settings - you can edit all settings (such as geolocation) both in app settings and in the corresponding submenu (geolocation, for instance).

**Comment by ggdiez** [comment]
Hi guys,

More talk about this feature ;)
 
@jancborchardt for the moment we don't have view of account details, only we re-use the login view to change the password. 

In the future, with account details view we could have there this feature, change password, data about the space used in the server, instant uploads, etc

But right now if we want develop this feature maybe it's possible to include it in the Settings view. I have attached a screenshot with the "Clear cache". It's not developed is only a mockup.

The info of the label over the "Clear Cache" button will be updated when the user change the account.


![option](https://cloud.githubusercontent.com/assets/2051473/8719518/9e586bac-2bac-11e5-997b-4d1f35d65e25.png)

**Comment by tushevorg** [comment]
@ggdiez looks nice :)

Personally I'd rename "Clear cache" to "Clear account cache", and added somewhere (possibly in the brackets) the total amount of storage used by ownCloud (when #accounts >= 2)

**Comment by rperezb** [comment]
after talking with @jancborchardt he has suggested as a first iteration to include a new option on the swipe menu; curently, we have the delete option, we will include the: "clear cache"

The only thing is that perhaps is too long the string :worried:

**Comment by jancborchardt** [comment]
Yep. Just for the record, a big »Clear cache« button in the settings is too present. And it’s also confusing because it’s per-account, but no one will notice that.

**Comment by John475** [comment]
Yes. Please add some sort of a clear cache.
Just an idea: how about a local cache button that will show everything currently local with size listed. There could be a button at the top of the list to "remove all" or delete just the ones you want to get rid of.

**Comment by nasli** [comment]
We are currently working on this feature, design should looks as @jancborchardt has suggested here https://github.com/owncloud/ios/issues/640#issuecomment-218448462

**Comment by rperezb** [comment]
Let's follow the status on https://github.com/owncloud/ios/issues/657
