### ISSUE TITLE
Send requested properties in PROPFIND, do not use allprops

### ISSUE THREAD

**Issue by PVince81** [owncloud/ios#310]
SabreDAV only allows these properties to be returned:
https://github.com/fruux/sabre-dav/blob/master/lib/DAV/PropFind.php#L50

In past OC versions we hacked Sabre to also include "oc:permissions", "oc:size", etc.

We are now upgrading to Sabre 2.1 (https://github.com/owncloud/core/issues/12876) and would like to remove the hack (which is actually not possible to use any more due to code changes in SabreDAV).

Please update the mobile client to explicitly request the properties.
A PROPFIND request could send a body that looks like this:
```
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
<a:prop><a:getcontenttype/></a:prop>
<a:prop><a:getetag/></a:prop>
<a:prop><oc:permissions/></a:prop>
<a:prop><oc:size/></a:prop>
...
</a:propfind>
```

As an added bonus: note that if you only want the mtime, then just request "a:getlastmodified". This way the server doesn't need to do extra work for properties that you don't want :smile: 

Note that this "explicit request properties" is compatible with older OC versions.

CC @davivel @javiergonzper  as discussed

**Comment by davivel** [comment]
@MTRichards , @rperezb , this needs to be pushed high in priority or the apps will break with OC 8.1.

**Comment by rperezb** [comment]
thanks! do we have an eta for oc 8.1 ?

**Comment by PVince81** [comment]
I thought it should be around April ?

**Comment by rperezb** [comment]
thx

**Comment by PVince81** [comment]
Note: please do not request "href" explicitly. It is not a WebDAV property because it is not part of the "propstat" response block.

**Comment by davivel** [comment]
Seen, our bad. Thanks.

**Comment by nasli** [comment]
The new version 3.4.1 iOS Client will support this new propfind.

**Comment by PVince81** [comment]
Note: this also means that older clients will not work properly against 8.1.
But I guess we can expect people to upgrade mobile clients more often than desktop clients ?

**Comment by rperezb** [comment]
thanks @PVince81 for pointing out this.

@MTRichards this is important to be taken into account to be aligned iOS app update and server one.
