### ISSUE TITLE
iOS app doesn't show available content on WebDAV share

### ISSUE THREAD

**Issue by j-ed** [owncloud/ios#311]
## Expected behavior

If the ownCloud iOS app is started it should connect to the ownCloud server and should show the available content of a user.
## Actual behavior

If the ownCloud iOS app is started it connects to the ownCloud server but  the content of a user is not shown and after a while the following message is displayed:

```
Verbindung zum Server nicht möglich  -> Unable to connect to the server.
```

This message isn't correct because I can instantly see data requests coming in from the iOS app which also continue to fill the owncloud.log file after the above mentioned error message has been shown.
Surprisingly the same problem appears when connection with the Android app so that it might be a general problem of the underlying ownCloud WebDAV API. (See https://github.com/owncloud/android/issues/814) for further details.
It seems to me that an initial WebDAV access triggers an update of the whole share tree including external storage which has been mounted (WebDAV and Google Drive).
If my assumption is correct it would help to restrict the relevant requests to the requested folder only to speed-up the apps instead of trying to read the whole WebDAV tree/content at once.

The following messages can be found in the Apache2 log file, which indicated to me that a connection could be established:

```
192.168.1.51 - - [19/Feb/2015:18:38:18 +0100] "GET /owncloud/status.php HTTP/1.1" 200 93 "-" "Owncloud%20iOs%20Client/3.3.2 CFNetwork/711.1.16 Darwin/14.0.0" 689 1296
```

The owncloud.log file shows hundreds of these messages:

```
{"reqId":"a704b91358367236029d401994056056","remoteAddr":"192.168.1.55","app":"core","message":"DB execute with arguments : array (   0 => '13',   1 => 'd41d8cd98f00b204e9800998ecf8427e', )","level":0,"time":"2015-02-19 18:31:35+01:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"a704b91358367236029d401994056056","remoteAddr":"192.168.1.55","app":"core","message":"DB prepare : SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,\n\t\t\t\t\t   `storage_mtime`, `encrypted`, `unencrypted_size`, `etag`, `permissions`\n\t\t\t\tFROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?","level":0,"time":"2015-02-19 18:31:35+01:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"a704b91358367236029d401994056056","remoteAddr":"192.168.1.55","app":"core","message":"DB execute with arguments : array (   0 => '13',   1 => 'ba9914343a79932ea13cf32f24b3a541', )","level":0,"time":"2015-02-19 18:31:35+01:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
{"reqId":"b4f895dd0a5468e5008209a7aae75a31","remoteAddr":"192.168.1.51","app":"core","message":"DB prepare : SELECT `fileid` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?","level":0,"time":"2015-02-19 18:31:35+01:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

If I access the WebDAV share from my desktop PC or if I use the web browser on my iOS device to access it, the available content is instantly shown.
## Steps to reproduce

1.) Start the ownCloud iOS app
2.) refresh the screen
3.) wait ...
#### Server Configuration

OS: Linux 3.2.54
Web server: Apache2 2.4.10 with **self-signed certificate**
Database: MySQL 5.1.73
PHP version: 5.4.35
ownCloud version: 8.0 (stable)
#### Client Configuration

Operating system: iOS 8.1.3
ownCloud iOS app: v3.3.2
Wifi quality: excellent
Wifi speed: 65 Mbps

**Comment by guruz** [comment]
Do you still have this issue? Can we close it?

**Comment by nasli** [comment]
Closed for inactivity, if needed, please reopen
