### ISSUE TITLE
owncloud App Crashes with PDF Documents

### ISSUE THREAD

**Issue by BarbT** [owncloud/ios#312]
When trying to forward a Document from Owncloud for Example ibook te ios App is doing nothing for about 10-15 seconds and then crashes. This seems to happen with bigger files >100MB.
How to work fix or workaround these ? 
(splitting files is not an option for many files)

**Comment by rperezb** [comment]
Thanks for reporting this, there is another issue about this, let´s follow its state there https://github.com/owncloud/ios/issues/215
