### ISSUE TITLE
Sharing PDF Files bigger than 20MB is not working

### ISSUE THREAD

**Issue by offlinehoster** [owncloud/ios#314]
If you sync a pdf file with the iOS ownCloud client on an iPad you are able to open this pdf file inside the ownCloud Client app, but after clicking on the icon to share this file with "iBook" is not working, after some time, the app is crashing and you have to restart the app. 

If you use smaller pdf files up to 8 or 9 MB it is working, but it needs some time to load the menu for ibook and all the other share/open options.

**Comment by ggdiez** [comment]
Hello @offlinehoster, 

We have resolved that problem in the new version 3.4, but you have to wait until the new version will be released.

**Comment by offlinehoster** [comment]
Hi @ggdiez , i will have a look if the issue is "really" resolved ;).

When is release date for 3.4?

**Comment by javiergonzper** [comment]
Hi @offlinehoster 
Sadly this fix will not be included on the 3.4 version but we will launch the 3.4.1 with this fix and others to support ownCloud 8.1 just after Apple approve the 3.4 :wink:.

The 3.4 version will be release this week :+1:

**Comment by offlinehoster** [comment]
So we have to wait...hurry up guys ;)

**Comment by javiergonzper** [comment]
Yes... but the wait will be worth :wink:
The new PDF viewer will have a preview by pages to navigate fast to any page and also will work the links inside the PDF to navigate to other page. Will be awesome!

**Comment by offlinehoster** [comment]
Ok, just for being right, what i mean is if you open/download a pdf with the iOS ownCloud client and open this pdf file inside the iOS ownCloud Client and click then this icon/button (see screenshot) than nothing happen if you opened a big file, bigger than 20MB, maybe just bigger than 13MB.

The iOS ownCloud client is crashing after some time, 15-30seconds.

![Screenshot](https://cloud.githubusercontent.com/assets/1618359/6572813/a0ba2d1e-c715-11e4-8080-1adf2a87f725.png)

**Comment by javiergonzper** [comment]
Yes, that bug I think that was fixed by @ggdiez for the version 3.4. 
Now the app does not crash and the button works immediately

**Comment by rperezb** [comment]
This is fixed, if you reproduce the error, please reopen
