### ISSUE TITLE
Server Not found error on iOS client..

### ISSUE THREAD

**Issue by vkshatriya1** [owncloud/ios#319]
Hi,
I am getting "Server Not Found" error while trying to configure owncloud on iOS client.
My URL format is https://www.xxxx-xxxxx.com/owncloud/
Certificate is Thirdparty signed certificate. 
I am able to open the owncloud through browser on all devices by using the same URL. 
Can you please advise what could be the wrond in my setup.

Owncloud is being accessed through Apache Proxy. 

Device : iPhone.
OS: iOS 8.1.3
OwnCloud : 8.0

**Comment by ggdiez** [comment]
Hi @vkshatriya1 

We have detected in the pass that the Network iOS API does not work well with proxy servers. Please review your Apache Proxy, if you are using the last version or the forums of the proxy support. 

In our case we tested our Squid proxy server and we found this in the forums:
http://lists.squid-cache.org/pipermail/squid-users/2014-October/000550.html

**Comment by vkshatriya1** [comment]
hi ggdiez, what could be the solution ?  Anything specific to e configured on proxy apache or apache serving owncloud ?

**Comment by otbe** [comment]
Maybe my issue is not related to that, but I get the "Server Not Found" error when clicking on a folder or file in a random manner. Sometime it works again on retry.

Before updating to 3.4 it works like a charm, but now the app is almost broken. I have nothing changed to OC Server (8.0.2 with nginx and self-signed certificate).

**Comment by nasli** [comment]
This issue could be related with #233,
 if not, please reopen it.

**Comment by vkshatriya1** [comment]
Think issue is related to SSL Tunneling for TCP connections through Apache proxy. HTTPS is going through Apache proxy with no issues but iOS network modules require a state-full TCP connection which Apache proxy may not be providing. I got this working through by listening at different port which will forward the requests to internal own cloud Apache. I haven't explored any other options.

**Comment by cloim** [comment]
After update IOS 9 Beta 3, Same error was here. But, I found this.

"iOS 9 and OSX 10.11 require TLSv1.2 SSL for all hosts you plan to request data from unless you specify exception domains in your app's Info.plist file."
http://stackoverflow.com/questions/30720813/cfnetwork-sslhandshake-failed-ios-9-beta-1

And It work now. I wish It will help you guys.

**Comment by javiergonzper** [comment]
Thanks @cloim today we will start to work with iOS9 we will take into account this
