### ISSUE TITLE
Cloud Integration in iOS "Locations" Menu

### ISSUE THREAD

**Issue by miqrogroove** [owncloud/ios#322]
For extra slick usefulness, I want to open and save files using MS Office apps.  MS announced support for this through an iOS 8 API.

http://blogs.office.com/2015/02/17/new-cloud-storage-integration-office/

Pretty Please :)

**Comment by nasli** [comment]
Hi @miqrogroove, thanks for your comment.

With the Document provider feature that will be within the new version 3.4.0, you will be able to open your files using MS Office apps. :)

The version is just pending to Apple approval. 

This issue is duplicated, you can keep up to date in #193
