### ISSUE TITLE
Options to open files in other apps gone in v3.4

### ISSUE THREAD

**Issue by fasttech** [owncloud/ios#323]
I'm asking you to please bring this functionality back or revert the app back to v3.3.

v3.3
![ociosv3 3](https://cloud.githubusercontent.com/assets/11577725/6759896/161ef09c-cf01-11e4-8c9d-33f2f61f5cbf.PNG)

new v3.4
![ociosv3 4](https://cloud.githubusercontent.com/assets/11577725/6759898/1e635edc-cf01-11e4-81b5-3ccd9fdb0c89.PNG)

**Comment by tflidd** [comment]
I can't send PDF-files to GoodNotes any more. Neither can I import. The same for images from camera roll, I can't send them to owncloud neither can I import these images to owncloud.

Without the possibility to exchange files with other apps than Mail, Message and Evernote, this app is useless!

**Comment by MacMapple** [comment]
Thanks for this post. The last two days I had searched the reason for this bug an I'm very frustrated about this. I need to open KBDX-Files. Hopefully the bugfix is coming as soon as possible.

**Comment by tegbains** [comment]
I am also having the same problem; I can no longer send .epub files to iBooks. Not sure why this feature was removed.

**Comment by berick77** [comment]
I am also very disappointed about the latest version. I need this feature everyday.... strange enough I read in this as a new feature: "Document Provider extension: access to your ownCloud files from other iOS apps" .... does it mean it goes the other way round (accessing files from the apps)..... does anyone know whether there is a new documentation available for V3.4.0?

**Comment by ggdiez** [comment]
Hello, 

In the current version we fixed a crash issue related with the previous "open in" view and doing that, we have lost the full functionality of the open in feature. 

Thanks for your fast comments about this bug this morning we have fixed the problem and we have added the previous functionality inside the current one. 

We will send to Apple the new version ASAP, so in the next version, 3.4.1, this bug will be fixed. 

Sorry for the inconvenience.

**Comment by tflidd** [comment]
Thanks for your fast response.

**Comment by berick77** [comment]
This sounds very good....many thanks for your fast and honest reply......  I really need this feature. Shit can always happen, the point is how the reaction is.... and this is in your case very cool

**Comment by srissel** [comment]
Indeed, thanks for the support!

**Comment by PeterKaagman** [comment]
Still no update.... 2 workarounds....

- get an Android device ;)
- use Safari

**Comment by MTRichards** [comment]
the fix is in process, and will be in Apple's review later this week, for release as soon as they approve - stay tuned.

If your other app has implemented a document provider connection, you can open ownCloud documents from that app, as ownCloud can now be a document provider source, rather then send them from ownCloud as a workaround.

**Comment by javiergonzper** [comment]
@PeterKaagman an Android device? really? :grimacing:
Be patient please we are on it :+1:

**Comment by mtoivo** [comment]
MTRichards: except opening files from document provider -enabled apps doesn't seem to work, at least in Drafts -app. It "sees" owncloud, but cannot open / save files to that provider.

**Comment by MTRichards** [comment]
@mtoivo Can you open another issue with your document provider problem here and outline how to repeat it? then we can see if it is specific or general as a problem. 
I found that it works great with Microsoft apps, for example, but that doesn't mean much for the myriad of other apps out there.

**Comment by mtoivo** [comment]
@MTRichards I think it's same issue as users are reporting in #193 but I might as well open a new case

**Comment by moritzheiber** [comment]
If you guys need any Testflight volunteers, count me in. Right now I'm pretty much stuck without any passwords on my iPhone :sweat_smile:

**Comment by Cagorso** [comment]
Still not working after the 3.4.1 update 😭

**Comment by rperezb** [comment]
@cagorso have you tried to click on the open "open in" option? This is included as one of the "open with" options.
thx

**Comment by Cagorso** [comment]
SORRY!!! Pls forgive me! I Made a mistake! Sorry. Everything works fine

**Comment by rperezb** [comment]
great to read this, @Cagorso !
Let's close this, if someone has any problem, please reopen or open a new ticket if the steps are different.
thx
