### ISSUE TITLE
Instant Upload, permanently GPS active

### ISSUE THREAD

**Issue by TheReal1604** [owncloud/ios#324]
Hi guys, 

thanks for the Great nee feature in the iOS App. But i got a little problem. If i activate the Instant Upload feature, my gps is permanently on. (Shown as the little arrow in the upper right status bar)

Can anyone explain why this is needed? 

Greets 
TheReal

**Comment by tflidd** [comment]
Check out this comment: https://github.com/owncloud/ios/issues/13#issuecomment-84086331

**Comment by nasli** [comment]
Hi @TheReal1604, 
This icon idicates that you allow share your location. 
We do not use active gps, instead, we use the significant-change location service. This service delivers updates only when there has been a significant change in the device’s location. This way we do not have to worry about the battery drain. 
You can keep up to date in the issue that @tflidd indicated you. Thks.
