### ISSUE TITLE
Crashes on URL entry

### ISSUE THREAD

**Issue by yellowcrash10** [owncloud/ios#325]
The latest version of the app (3.4.0) crashes when it attempts to verify the entered URL It doesn't ask to save the certificate, so that may be the problem. If I force it to use HTTP, it appears to log in, but doesn't list files.
My device is an iPhone 5s running iOS 7.0.4.

**Comment by javiergonzper** [comment]
Hi @yellowcrash10 

I tested it using 3G with a https self signed and I receive the question about accept the certificate.
Did you try to delete an reinstall again ownCloud?
Could you post your status.php? https://example.com/status.php

**Comment by yellowcrash10** [comment]
I tried deleting it and reinstalling it, and the problem persists. This is the output of status.php:
{"installed":true,"maintenance":false,"version":"8.0.2.0","versionstring":"8.0.2","edition":""}

**Comment by javiergonzper** [comment]
Could you try to update your device? We test iOS7 with a 7.1.1 (the last one) version. Also if you want you can contact with us at apps@owncloud.com to give us a test account to try to reproduce the problem on your server.

**Comment by rperezb** [comment]
Closed for inactivity, if this is still an issue, please reopen
