### ISSUE TITLE
.odt files in Ios

### ISSUE THREAD

**Issue by sebastien180** [owncloud/ios#326]
Hello all, 
I was very surprised yesterday when, using a "recommended" application, Documents, in my 8.0.5 server, with files supporting .odt extensions, I was not able to read them (edit them ?) in my owncloud application for IOS. 
Either you should not recommend that application, either you should support these files in the IOS application.
Do you want to compete with Google Documents or not ? 
Thanks for the rest of OwnCloud.

**Comment by RealRancor** [comment]
Hi,

as also written in your forums thread: https://forum.owncloud.org/viewtopic.php?f=24&t=27274 you need to understand that this app is a **Sync-Client** and not an Editor app. Especially not for advanced file formats like .odt...
