### ISSUE TITLE
IOS 8.2 unable to install owncloud

### ISSUE THREAD

**Issue by jdwirtz** [owncloud/ios#327]
I've upgraded my iPhone 5s to IOS 8.2 and can no longer install owncloud.
I was having issues of my photos that I uploaded to owncloud were being 
resized to a smaller size. I uninstalled owncloud and re installed, no change.
IOS was 8.1.2, so I upgraded to 8.2 and now I can't install owncloud. It shows
about a 3/4 load on the icon and just sits there.  I've deleted app, reset/rebooted
my iPhone.  After 30mins I don't think it going to install.

**Comment by javiergonzper** [comment]
Hi @jdwirtz 
Looks like it is a problem related with the Appstore.
Can you install any other app?

**Comment by jdwirtz** [comment]
Yes.. I'm able to install other apps.

**Comment by jdwirtz** [comment]
I just tried again… this time it installed.  Not sure what the deal was then,

Cause it would install on my mini an ipad. But it there now.

The reason I was doing this, is because when I upload pictures from

My iPhone it resizes the picture to a smaller size.  After this last install

It will upload some a full size and some at reduced size?  But when I 

Dump them off the phone with USB cable they are all full size.

Any ideas on that one?

 

Jim

**Comment by javiergonzper** [comment]
Witch version of iOS and iPad it is? We checked that time ago and was fixed but maybe we have a bug in a concrete version.

**Comment by jdwirtz** [comment]
The iPad is IOS 8.1.2

My iPhone was 8.1.2 and now 8.2 

The reduction in size happened on 8.1.2 and now on 8.2

Just took a couple of pictures uploaded them via my phone to owncloud 

and copied the same pictures via USB cable to my owncloud folder.

 



 

From my iPad mini



 

and oddly enough one photo I uploaded from my iPhone via owncloud app that came out the right size??



 

but as you see here that is the exception not the rule.

**Comment by jdwirtz** [comment]
Any luck coming up with a solution for this problem?

 

Jim

 

 

 

The iPad is IOS 8.1.2

My iPhone was 8.1.2 and now 8.2 

The reduction in size happened on 8.1.2 and now on 8.2

Just took a couple of pictures uploaded them via my phone to owncloud 

and copied the same pictures via USB cable to my owncloud folder.

 

cid:image001.png@01D066E5.2557CF40

 

From my iPad mini

cid:image002.png@01D066E6.2CAEF880

 

and oddly enough one photo I uploaded from my iPhone via owncloud app that came out the right size??

cid:image003.png@01D066E6.2CAEF880

 

but as you see here that is the exception not the rule.

cid:image004.png@01D066E6.53014DD0

**Comment by nasli** [comment]
We can close this issuee and keep up to date in this one #244. Thanks
