### ISSUE TITLE
how to access the File Picker and Document Provider Extension functionality?

### ISSUE THREAD

**Issue by NasirMalik** [owncloud/ios#328]
AppStore is asking for this info. Please help.

At your earliest opportunity, please review the following question(s) and provide as much detailed information as you can. The more information you can provide upfront, the sooner we can complete your review.

1. Please provide information of how to access the File Picker and Document Provider Extension functionality.

**Comment by rperezb** [comment]
@NasirMalik not sure how we may help you, this deppends on the app that you are uploading to the the market.

**Comment by NasirMalik** [comment]
Its same replica of ownCloud iOS app. So please tell me answer of this question, I need to answer to appStore people.

**Comment by rperezb** [comment]
@NasirMalik it is not possible to upload the ownCloud Mobile App for iOS to the market due to the license, you may check it on https://owncloud.org/contribute/ios-license-exception/

**Comment by NasirMalik** [comment]
Ok thanks for information.
