### ISSUE TITLE
app can't list the file/directory

### ISSUE THREAD

**Issue by cdliufei** [owncloud/ios#329]
while I launch the app, the console will show me the following error:

Could not create database queue for path (null)/cache_folder/DB.sqlite
Error creating directory path: The operation couldn’t be completed. (Cocoa error 513.)

Could you please give me a hand, thanks!

**Comment by cdliufei** [comment]
solve it by myself.
it was caused by App extension.

**Comment by javiergonzper** [comment]
Probably you have that null because you do not have the AppGroup. Are you using the simulator or a real device?

**Comment by vechie** [comment]
hello, I have the same error as you lists,such as 
Owncloud iOs Client[2858:27717] Could not create database queue for path (null)/cache_folder/DB.sqlite
fatal error: unexpectedly found nil while unwrapping an Optional value
But I don't know what to do ?  Please help me ,thank you~

**Comment by vechie** [comment]
hello, I have the same error as you lists,such as 
Owncloud iOs Client[2858:27717] Could not create database queue for path (null)/cache_folder/DB.sqlite
fatal error: unexpectedly found nil while unwrapping an Optional value
But I don't know what to do ? Please help me ,thank you~@cdliufei

**Comment by bizonix** [comment]
I have the same issues, how you solved it?
```
2015-07-02 04:24:52.843 Owncloud iOs Client[806:288296] Error creating directory path: Unable to complete the operation. (Cocoa, error 513)
2015-07-02 04:24:52.855 Owncloud iOs Client[806:288296] error opening!: 14
2015-07-02 04:24:52.856 Owncloud iOs Client[806:288296] Could not create database queue for path (null)/cache_folder/DB.sqlite
fatal error: unexpectedly found nil while unwrapping an Optional value
```

**Comment by ranby** [comment]
I also have the same problem. How did you solve it?

I'm currently using the simulator.

**Comment by harithahdasan** [comment]
Did you create App group and Add all the bundle Id's to that group?

**Comment by ranby** [comment]
No I didn't. How do you do that? I just forked the repo an hour ago and tried to get it up and running

**Comment by vechie** [comment]
could you tell me how to do this please?
And I have a develper account ,but I  don't know how to do next?
Please show me~ thank you again ~@harithahdasan

**Comment by ranby** [comment]
I managed to solve it. If you have a valid developer account and a signing profile imported to your xcode project and go to "App Groups" on the "Capabilities" tab in your project, xcode should be able to fix any issues automatically. It xcode fails, you can try logging in to Apple Developer Member Center and try to add App IDs and App Groups manually there.

**Comment by rperezb** [comment]
You may find helpful the info available on: https://doc.owncloud.org/server/8.0/admin_manual/enterprise_ios_app/publishing_ios_app_3.html
https://doc.owncloud.org/server/8.0/admin_manual/enterprise_ios_app/publishing_ios_app_5.html

**Comment by harithahdasan** [comment]
@vechie :Yes do follow the above two links provided by @rperezb  it will work I too followed the same path..
