### ISSUE TITLE
As an ownCloud iOS user, I want an extended settings menu (account, pincode, camera upload, etc.)

### ISSUE THREAD

**Issue by oguelich** [owncloud/ios#333]
Hi guys,
ownclouds current settings menu contains just a few options for account, pincode, automatic camera roll upload only. In my pov a change could be done very easily and will increase user experience and satisfaction with iOS app in a strong way.

Menus could be redesigned in form of categories, e.g. Accounts, Options, Application. Within these categories following items could be assigned (settings menu tree below is just a short idea):
- Accounts

-- List of accounts as implemented in current version
--- Account details (editable)
---- Server
---- User
---- Password

--- Further Information
---- Connection status to account server
---- Disk space statistics
---- Access to Deleted Files
- Options

-- Pincode
--- Activate/Deactivate Pincode
--- Change Pincode

--- Request pincode (show state: active/inactive)
---- Activate/Deactivate request pincode
---- Options: Immediately, After 1 min., After 5 min., After x min.
Currently the pincode will be requested every time when you leave owncloud app (already when you double tap home button just to access iOS multitasking view).

--- Delete/Remove account configuration (show state: active/inactive)
---- Activate/Deactivate account removal
---- Options: After 5 times, After 10 times, After x times

-- Camera Upload (show state: active/inactive)
--- Activate/Deactivate Camera Roll Upload

--- Upload when connected to WiFi only
--- Choose folder for upload

--- Upload Resolution ( #244 )
---- Image Size (Original, Very Big, Big, Middle, Small) 
- Network
  -- Use Wifi only
  -- Clear local cache ( #301 )
- Application
  -- Version
  -- Rate Application
  -- Help
  -- Feedback
  -- Developer Information
  -- Log

Features which are coming within the next releases and needs some settings could be easily assigned to this structure (e.g. usage of TouchID, Lock for protected folders, etc.)

**Comment by oguelich** [comment]
@javiergonzper @nasli @rperezb @jancborchardt

Hi at all, could anybody categorize this issue. I think some parts of it could be done by a junior dev e.g. reorganization of menus within categories.

**Comment by jancborchardt** [comment]
@oguelich since this puts many issues in one, it would be good to split it up. And let’s view it from a different point, rather than »I want more settings«, we need to think about »what functionality we need, for what reason«.

Start with one – what’s the most important thing you miss from the app? And describe your usecase.

**Comment by tushevorg** [comment]
a simple text editor (like notes) will be very useful

**Comment by javiergonzper** [comment]
@tushevorg,
Can you open a new issue to make your request? :+1:

**Comment by tushevorg** [comment]
@javiergonzper, ok, I will

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
