### ISSUE TITLE
Make Instant Uploads directory configurable

### ISSUE THREAD

**Issue by mcnesium** [owncloud/ios#335]
Right now instant uploads go to to a directory named InstantUpload in the document root of the latest active profile. This should be configurable, not only the target directory, but also the target profile.

**Comment by oguelich** [comment]
I've already mentioned this point in another issue ( See #333 )

Best Regards

**Comment by Mito73** [comment]
This would be a really important feature in my point of view. Here is my use-case:

- All family members are taking photos with their mobile devices
- Each of them does have an own ownCloud folder for this pots, e.g. Photos_Michael
- When taking a photo is is instantly uploaded to our ownCloud-Server on the web
- All family ownCloud folders are shared with a special download user called NASuser
- A script on the family NAS server connects periodically to ownCloud with NASuser
- The photos of all family members are downloaded to the corresponding directories on the NAS 
- Photos older than 12 month will be deleted from ownCloud by the script

This way we would keep the ownCloud system lean and clear and all photos are archives safely on the local NAS storage at home.
BUT, precondition for a solution like this would be to have the ability to have different and dedicated instant upload folders! I don't see any solution to share several identical named 'InstantUpload' folders to one single user and still keeping the content apart.

I guess there will be similar scenarios in a business context also :-)

Kind regards,
Michael

**Comment by mbardelmeijer** [comment]
:+1:

**Comment by gawin** [comment]
+1 For this feature!

My use case: I have a folder structure that I would like the OwnCloud app to respect.
In my case uploads should go to '/home/media/pictures/iphone'

For my scans I'm using Scanbot, which uploads new scans automatically using WebDAV to a specific folder on my OwnCloud server. Would love to see a similar functionality in the OwnCloud App!

**Comment by rawbertp** [comment]
+1 please fix this!

**Comment by andreasba** [comment]
I would also really like this feature

And thank you very much for the great app so far!

**Comment by nasli** [comment]
Let's keep tracking on this issue #453
