### ISSUE TITLE
[Share link] As a OC user I want to be able to share a link setting up the password so that before accessing to data, the password will be required

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#336]
AC:
- When a user select to share a file/data by link a new menu will be shown so that the user may select additional options for the moment  set password, then set expiration time

UI DOUBTS: 
- Do we show a new view?
- Will it work the mockup attached? cc/ @jancborchardt 

![screen shot 2015-04-07 at 15 01 35](https://cloud.githubusercontent.com/assets/1846927/7023643/0954049e-dd37-11e4-8c82-a64ad2618d72.png)

**Comment by jancborchardt** [comment]
Ok, will work on a mockup!

Btw – what do you use for mockups? :D I can recommend [Pencil](http://pencil.evolus.vn/), they have a good sketch look.

**Comment by jancborchardt** [comment]
Here you go:
![sharing dialog](https://cloud.githubusercontent.com/assets/925062/7067065/c5e64a62-dec8-11e4-8f15-d58b3fea928b.png)

With the relevant file name and a thumbnail. This is based on the current desktop sharing dialog (and the current web interface sharing dialog). Of course this has to properly be done with the iOS 8 design (and Material design for Android).

Btw – what do you use for mockups? :D I can recommend [Pencil](http://pencil.evolus.vn/), they have a good sketch look. The sources for this mockup are [in our design repo](https://github.com/owncloud/design/blob/master/mobile/sharing%20dialog.ep).

**Comment by rperezb** [comment]
I used http://ninjamock.com

**Comment by rperezb** [comment]
Done via https://github.com/owncloud/ios/pull/478
