### ISSUE TITLE
As an ownCloud iOS user I want to clear my upload list.

### ISSUE THREAD

**Issue by rakekniven** [owncloud/ios#339]
As a long time user I have many uploads and want to clear list. 

At the moment list shows all time history which is not interesting at all.

Please provide option to clear list.

**Comment by nasli** [comment]
Hi @rakekniven, 
thanks for your suggestion, this could be a usefull feature. 
We will considere it for future versions.

**Comment by jesmrec** [comment]
Approved

**Comment by nasli** [comment]
Closed via https://github.com/owncloud/ios/commit/ccaf75826207801d49065ae4710423384c3ab98c
