### ISSUE TITLE
unable to get the list of files when selecting  a directory 

### ISSUE THREAD

**Issue by Zarrami** [owncloud/ios#347]
when i select a directory  in the Files list (didSelectRowAtIndexPath). I can not get the list of files in the selected directory. I've got error:
Finishing up a navigation transition in an expected state.Navigation Bar subview tree might bee corrupted.

**Comment by javiergonzper** [comment]
It is strange. Did you change anything?
Maybe this could help you:
http://stackoverflow.com/questions/5301014/ios-popviewcontroller-unexpected-behavior

**Comment by rperezb** [comment]
Closed for inactivity, if this is still an issue, please reopen
