### ISSUE TITLE
app doesn't work 

### ISSUE THREAD

**Issue by iRy5** [owncloud/ios#348]
Hello, 
I am new with own cloud 
I installed it fine, and I can upload and download of the browser from my laptop 
and I can use it from my iPhone browser to upload and download

but when I bought owncloud app for iOS and after I log in nothing shows up
( Nothing in here. Upload something! )

I tried to upload from the app, but it gives me an error, if I clicked on the file
it tells me to overwrite or rename, if I chose any of them it gives me 
(Waiting for server connection)

![1](https://cloud.githubusercontent.com/assets/11977336/7179805/1c15df58-e444-11e4-9558-cc460a0b58b5.png)
![2](https://cloud.githubusercontent.com/assets/11977336/7179804/1c155a42-e444-11e4-8152-cfe452e1e2a2.png)
![img_8371](https://cloud.githubusercontent.com/assets/11977336/7179803/1c12983e-e444-11e4-94a2-844523b49774.PNG)

![- -](https://cloud.githubusercontent.com/assets/11977336/7179809/2a43379c-e444-11e4-881a-fb367bf45ec5.png)

note: I deleted this line ( Options -Indexes ) from .htaccess , because it causing ( 500 internal error ) 
and my web host told me to delete it

**Comment by javiergonzper** [comment]
Hi @iRy5 

Can you connect using the WebDav interface?
http://yoururl/remote.php/webdav/ 

The mobile clients use that interface to get the list of the files and make other operations.

**Comment by iRy5** [comment]
Yes it's work 

![- -](https://cloud.githubusercontent.com/assets/11977336/7187353/96aa7150-e478-11e4-9c50-bd83f53e5102.png)

**Comment by iRy5** [comment]
But from the admin panel : 
 
![- -](https://cloud.githubusercontent.com/assets/11977336/7187413/fc8ac5ec-e478-11e4-8840-6d2b60971b11.png)

**Comment by javiergonzper** [comment]
The last problem could be causing the wrong behavior on the iOS app. Maybe you should ask on the ownCloud forums or on the server side repository:
https://forum.owncloud.org/
https://github.com/owncloud/core/issues

I am sorry but about the server configuration i do not have much idea.

**Comment by javiergonzper** [comment]
@iRy5 did you fix this?

**Comment by rperezb** [comment]
Close for inactivity, if needed please reopen, thx
