### ISSUE TITLE
Losing Configuration of the iOS App

### ISSUE THREAD

**Issue by corsch** [owncloud/ios#353]
Hi,

I have a problem with the Owncloud App for iOS.
The App loses its configuration after some time.

iPhone 4s with iOS 8.3 
Owncloud App 3.4.1
Owncloud Server 7.0.5

Best Regards,
Corvin Schmid

**Comment by javiergonzper** [comment]
Hi @corsch,

Duplicated: https://github.com/owncloud/ios/issues/344

This is a problem related with the keychain. It is a known bug of Apple that is reported. In the next release we will make a fix that will reduce the probabilities that it happens. 
As workaround you can kill the app and open it again. If you do that the app will open with the configuration fine.
