### ISSUE TITLE
Crash on saving certificate!

### ISSUE THREAD

**Issue by MasoudCS** [owncloud/ios#358]
When I try to run client on "iOS Simulator", after I enter server URL, it crashes and point me to this line:(Utils/SSL/CheckAccessToServer.m, Function: saveCertificate:(SecTrustRef) trust withName:(NSString *) certName)
PEM_write_X509(file, x509cert);

and output this error:
2015-05-07 15:20:22.420 Owncloud iOs Client[3545:83725] <0x7fa2f053dbe0 CheckAccessToServer.m:(192)> willSendRequestForAuthenticationChallenge
2015-05-07 15:20:22.420 Owncloud iOs Client[3545:83725] <0x10fa53a50 UtilsUrls.m:(43)> Error creating directory path: The operation couldn’t be completed. (Cocoa error 513.)
2015-05-07 15:20:22.420 Owncloud iOs Client[3545:83725] <0x7fa2f053dbe0 CheckAccessToServer.m:(277)> Error: The operation couldn’t be completed. (Cocoa error 4.)
2015-05-07 15:20:22.424 Owncloud iOs Client[3545:83725] <0x10fa53a50 UtilsUrls.m:(43)> Error creating directory path: The operation couldn’t be completed. (Cocoa error 513.)

As you see, It can't write certificate on file (I think no matter trusted or not, but in my case it is self-signed).
and surprisingly I encounter this error on a Jailbroken iPhon4 with some owncloud IPA that I downloaded from Internet. (this time obviously no error, crash and then nothing)

so, any idea whats wrong here? I can't login to owncloud iOS at all, except with the version that I buy from AppStore!
I'm using Yosemite on MiniMac, XCode 6.2 and the owncloud iOS app release version 3.4.1_signed that I cloned from github.

Thanks in advance

**Comment by javiergonzper** [comment]
@MasoudCS could you check the path where the app try to save the certificate? Maybe it does not exist...

**Comment by MasoudCS** [comment]
@javiergonzper 
Tnx javier .

in implementation of "- (void)saveCertificate:(SecTrustRef) trust withName:(NSString *) certName;" method in CheckAccessToServer class, the file value after "file = fopen( [certName UTF8String], "w" );" execution is be nil and in "PEM_write_X509(file, x509cert);" code
we have crash...!

the [certName UTF8String] method is ok and certName value also!

Thanks again

**Comment by javiergonzper** [comment]
@MasoudCS 

When you execute the line:
PEM_write_X509(file, x509cert);

Do file and x509cert have any value?

**Comment by MasoudCS** [comment]
the x509cert have a value but the file variable don't...!

**Comment by javiergonzper** [comment]
Does "certName" have value?

**Comment by MasoudCS** [comment]
yes

**Comment by javiergonzper** [comment]
The (null) is your problem. You are getting the wrong path of the system.

The method getOwnCloudFilePath it not working property. Looks like it can not access to your Appgroup.
You need to create all the certificates on Developer Account... I thought that it will works on the simulator but looks like that not works...

ownCloud need the Appgroup to work with the Document Provider and the Share In

**Comment by MasoudCS** [comment]
Sorry for late answer.
so first of all I have to buy a developer account! :-)
Thank you very much Javier.

**Comment by javiergonzper** [comment]
No problem ;)
Yes I am sorry but looks like that is the problem.

If you have any problem reopen this issue.
