### ISSUE TITLE
Instant upload on iphone 4

### ISSUE THREAD

**Issue by RomanSzabados** [owncloud/ios#359]
Hi,

The instant upload feature does crash the app on iphone 4.
OwnCloud version: 3.4.1
iOS version: 7.1.2

Right after enabling the instant upload feature in settings (of ios owncloud client), the screen freezes. After restarting the phone and opening the app, only the background image stays visible, no controlls, no menu, nothing else.

Disabling access to the gallery in iOS settings, the ownCloud client works again.

The instant upload feature is crucial in this case, as i try to move away from dropbox which was used for exact this purpose.

**Comment by javiergonzper** [comment]
Hi @RomanSzabados, sorry for the delay.

I am checking the issue on iPhone 4S with 7.1. The app get freeze for a few seconds but after that everything works fine.

We have to investigate why it happens. Looks like there is any process on the main thread that freeze the app.

Thanks for reports

**Comment by RomanSzabados** [comment]
Hi,

Its my wife's phone, so i am unable to test it right now. Last time, i have waited for about 3 minutes (which may not be enough) .
Is there a way to obtain some log file? Or how can i help?

Could it be that the app is indexing/scanning the existing photos/videos? It might be some gigabytes.
Thank you.

**Comment by javiergonzper** [comment]
Hi @RomanSzabados do not worry I was checking the issue and I found the problem.
Thanks a lot for your help :+1:

**Comment by nasli** [comment]
Hi @RomanSzabados, 
we have made some refactor in the instant uploads feature in order to reduce the use of memory and access to the database. 
Please, make sure that you have enough space on your device.
This updates will be within v3.4.5 new version.
