### ISSUE TITLE
InstantUploads: do not try to create the InstantUploads folder if it already exists

### ISSUE THREAD

**Issue by hberntsen** [owncloud/ios#373]
### Expected behaviour
Upload the photo to the InstantUploads folder

### Actual behaviour
~~Photos taken stay in the uploads list with the text: Waiting for server connection.~~
Photos are uploaded but the server logs an error (see below) 

### Steps to reproduce
Let the InstantUploads feature upload photos while the folder itself already exists.

### Environment data
iOS version: 8.3
Device model: iPhone 5
ownCloud app version: iOS 3.4.1
ownCloud server version:  ownCloud 8.0.4 (git)  (in docker, via https://registry.hub.docker.com/u/l3iggs/owncloud/ and  https://registry.hub.docker.com/u/jwilder/nginx-proxy/ )

#### Web server error log
Nothing logged
#### Web server access log
172.17.0.2 - - [25/May/2015:11:20:29 +0000] "GET /status.php HTTP/1.1" 200 95
172.17.0.2 - - [25/May/2015:11:20:28 +0000] "POST /index.php/heartbeat HTTP/1.1" 200 -
172.17.0.2 - aberntsen [25/May/2015:11:20:29 +0000] "PROPFIND /remote.php/webdav/InstantUpload/Photo-2015-05-25-13-19-40_4900.JPG HTTP/1.1" 404 276
172.17.0.2 - - [25/May/2015:11:20:32 +0000] "GET /status.php HTTP/1.1" 200 95
172.17.0.2 - - [25/May/2015:11:20:33 +0000] "GET /status.php HTTP/1.1" 200 95
172.17.0.2 - aberntsen [25/May/2015:11:20:33 +0000] "GET /ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 200 691
172.17.0.2 - aberntsen [25/May/2015:11:20:35 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 671
172.17.0.2 - - [25/May/2015:11:20:36 +0000] "GET /status.php HTTP/1.1" 200 95
172.17.0.2 - - [25/May/2015:11:20:37 +0000] "GET /status.php HTTP/1.1" 200 95
172.17.0.2 - aberntsen [25/May/2015:11:20:38 +0000] "PROPFIND /remote.php/webdav/InstantUpload/Photo-2015-05-25-11-43-43_4896.JPG HTTP/1.1" 404 276
172.17.0.2 - aberntsen [25/May/2015:11:20:39 +0000] "PROPFIND /remote.php/webdav/InstantUpload/Photo-2015-05-25-13-19-40_4900.JPG HTTP/1.1" 404 276
172.17.0.2 - aberntsen [25/May/2015:11:20:41 +0000] "GET /ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 200 691
172.17.0.2 - aberntsen [25/May/2015:11:20:42 +0000] "GET /ocs/v1.php/apps/files_sharing/api/v1/shares HTTP/1.1" 200 772
172.17.0.2 - aberntsen [25/May/2015:11:20:44 +0000] "MKCOL /remote.php/webdav/InstantUpload/ HTTP/1.1" 405 247
172.17.0.2 - aberntsen [25/May/2015:11:20:46 +0000] "GET /ocs/v1.php/apps/files_sharing/api/v1/shares?path=&subfiles=true HTTP/1.1" 200 691

#### ownCloud log (data/owncloud.log)

This gets repeated every time it tries to upload:

Exception: {"Message":"The resource you tried to create already exists","Code":0,"Trace":"#0 \/usr\/share\/webapps\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(964): Sabre\\DAV\\Server->createCollection('InstantUpload', Array, Array)\n#1 [internal function]: Sabre\\DAV\\Server->httpMkcol('InstantUpload')\n#2 \/usr\/share\/webapps\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(474): call_user_func(Array, 'InstantUpload')\n#3 \/usr\/share\/webapps\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('MKCOL', 'InstantUpload')\n#4 \/usr\/share\/webapps\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#5 \/usr\/share\/webapps\/owncloud\/remote.php(54): require_once('\/usr\/share\/weba...')\n#6 {main}","File":"\/usr\/share\/webapps\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php","Line":1714}

**Comment by ggdiez** [comment]
Hi @hberntsen 

Thanks for the detailed bug ;). 

We will check your bug as soon as posible, in the meanwhile I say you that we are having problems with the uploads in iOS 8.3 and the current version published in the App Store (3.4.1). We opened a bug on Apple about this.

**Comment by nasli** [comment]
Hi @hberntsen, 

you have a file marked as favorite? 
can you upload or download any file?
In the market version theres a problem in uploads and downloads with favorites.
Try to remove all favorites, kill the app and open it again. All should work. 
This problem it's already fixed and will be within 3.4.2 version.

Cheers

**Comment by hberntsen** [comment]
At the time of reporting I was able to manually upload photos via the app. Downloading also was no problem. No files were marked as favorite.

I tested InstantUpload again, it works now! I did upgrade software/configs on the server side so that could have fixed the core issue.

My server logs still show the error message mentioned in the issue description.

**Comment by ggdiez** [comment]
Hello @hberntsen 

I'm glad that you can use instant uploads. :)

Don't worry with the error message that you mentioned, we are not checking if the folder already exists in the server for that the app try to create the folder every time.
