### ISSUE TITLE
[iPad] [layout] empty folder and first file/folder scrolls under top bar

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#374]
### Expected behaviour

I would like to see all files in all folders.

### Actual behaviour

After some steps, folders don't show content and file list scrolls under top bar.

### Steps to reproduce

1. start iOS app on iPad in Landscape mode
2. open PDF
3. make PDF full width (document top left "<")
4. bring file list back (document top left ">")
5. open folder in file list **==> folder looks empty**
6. go back to parent folder (file list top left "<") **==> first file/folder scrolls under top bar**

**Workaround:**

1. open PDF
2. make PDF full width (document top left "<")
3. klick on the ownCloud icon (document top left) to show hovering file list
4. klick on the ownCloud icon again (document top left) to close hovering file list
5. bring file list back (document top left ">") **==> file list is fully visible, folders have content**

**another bug:**

1. open PDF
2. make PDF full width (document top left "<")
3. klick on the ownCloud icon (document top left) to show hovering file list
4. bring file list back (document top left ">") **==> black space instead of file list**

### Environment data

iOS version:
8.3

Device model: 
iPad 2

ownCloud app version:
3.4.1

ownCloud server version:
8.0.3

@rperezb Is this known and already fixed for next release? Please add [blue-ticket].

00003185

**Comment by rperezb** [comment]
hey @michaelstingl thanks for reporting this.
yes, we are aware of this, the whole behavior of the list and detail view on iPad will be changed on 2 releases. 
What we have implemented is a native behavior so that the button "<" will dissapear. 
This is related to: https://github.com/owncloud/ios/issues/269  and to this one https://github.com/owncloud/ios/issues/97

**Comment by rperezb** [comment]
Close via: https://github.com/owncloud/ios/pull/360
This will be included on the version 3.4.3
