### ISSUE TITLE
Server not found

### ISSUE THREAD

**Issue by iskatu** [owncloud/ios#380]
When trying to connect with the iOS App I get the error "Server not found". Connecting to the web interface with Safari works fine. The desktop clients are working fine as well.

**Comment by rperezb** [comment]
Thanks for contacting us.

Can you please check from any web browser:

- Do you have access to yourServerurl/status.php without being needed to enter your credentials?
- If the previous works, can you access to yourServerurl/remote.php/webdav? In this case your credentials have to be asked

**Comment by iskatu** [comment]
It works as you described. `status.php` is accessible without authentication, `remote.php/webdav` requires my credentials.

**Comment by iskatu** [comment]
This might be a DNS issue. Using the actual IP of the server, everything works fine. However, this is not an options as I don't have a static IP and therefore rely on a DynDNS service to get the current IP address. Safari on the same iPhone is able to correctly resolve the domain name.

**Comment by stickr** [comment]
I've been receiving the same errors for a while, I can access the status.php without authentication but each time the following is place into my owncloud.log

{"reqId":"e7134eac239991d1fa49d175547e0f7e","remoteAddr":"XX.XX.XX.XX","app":"webdav","message":"Exception: {\"Message\":\"No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/media\\\/raid\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(126): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#1 \\\/media\\\/raid\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#2 \\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod('GET', 'status.php')\\n#4 \\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(433): call_user_func_array(Array, Array)\\n#5 \\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(455): Sabre\\\\DAV\\\\Server->broadcastEvent('beforeMethod', Array)\\n#6 \\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('GET', 'status.php')\\n#7 \\\/media\\\/raid\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/media\\\/raid\\\/www\\\/owncloud\\\/remote.php(54): require_once('\\\/media\\\/raid\\\/www...')\\n#9 {main}\",\"File\":\"\\\/media\\\/raid\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":73}","level":0,"time":"2015-06-17T02:27:28+00:00","method":"GET","url":"\/remote.php\/webdav\/status.php"}

**Comment by enoch85** [comment]
@iskatu Is this issue still existing? Please close otherwise. :)

**Comment by iskatu** [comment]
@enoch85 Yes, the issue still persists.

**Comment by rperezb** [comment]
@stickr this is likely to be a different issue, the 
```No basic authentication headers were found``` i'd recommend you to update the server if you are not on the latest version.

**Comment by rperezb** [comment]
@iskatu about this one, can you please check using any web browser within the mobile app if you may access your server url?
thx

**Comment by iskatu** [comment]
@rperezb It works fine with Safari on the same iPhone.

**Comment by rperezb** [comment]
@iskatu can you please send to us a mail at apps@owncloud.com 
thx

**Comment by rperezb** [comment]
@iskatu is this fixed within the latest version, 3.4.5? 
If not, please reopen

**Comment by iskatu** [comment]
The issue still exists, same error.

**Comment by nasli** [comment]
Hi @iskatu, please send us a test account to apps@owncloud.com and will check it,THK

**Comment by zeezee300** [comment]
Hi, any news to this issue?
With the latest version 3.4.5 i receive following error in my owncloud log:

Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(154): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(127): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70

**Comment by iskatu** [comment]
Found the solution, the issue is related to [this one](https://github.com/owncloud/android/issues/509).

After chaning `'installed' => 'true'` to `'installed' => '1'` in my `config.php` the app is working fine now.

**Comment by javiergonzper** [comment]
Thank you for post the solution!

**Comment by nickvergessen** [comment]
Better to change it to `'installed' => true,` which is the expected value ;)

**Comment by nickvergessen** [comment]
Also will be fixed on the server with https://github.com/owncloud/core/pull/24765
