### ISSUE TITLE
Remote Thumbnails ios app

### ISSUE THREAD

**Issue by aqxavier** [owncloud/ios#385]
Someone is developing some routine for the generation of thumbnails in client ios ??
In the android app I know this works well ...

**Comment by ggdiez** [comment]
Hi @aqxavier, 

Right now we have an user story about this in our backlog. So we expect to work in that for the next releases.

The idea is make the thumbnails like Android. 

The thumbnails feature are composed by two parts: 

1) Generate the thumbnails from the downloaded images in the app. (We don't need server connections for that)

2) Get the thumbnails from the OC server using the API for that. But this part will not be in this repository, the idea will be add a method to get the thumbnails in the iOS library repository https://github.com/owncloud/ios-library. 

If you can help us, your are more than welcome to start contributing on the ownCloud project!

Before starting, we'd appreciate you sign the contribution agreement, http://owncloud.org/contribute/agreement/ and send it to @karlitschek 

You may be found useful to read https://github.com/owncloud/ios/blob/develop/CONTRIBUTING.md

In case you want to contact us not only we are on github but also on the IRC, freenode #owncloud-ios


Best,

**Comment by nasli** [comment]
Yes, @michaelstingl.
 This part is already ongoing on https://github.com/owncloud/ios/tree/thumbnails_for_downloaded_images

**Comment by MorrisJobke** [comment]
This was merged yesterday: https://github.com/owncloud/ios/pull/549

Close?

**Comment by rperezb** [comment]
@MorrisJobke this is the first part, #549 includes thumbnails for downloaded images

It's pending to include thumbnails for remote ones, let's keep this issue open for this requirement

**Comment by nasli** [comment]
Remote thumbnails will be within next release. 
It will support thumbnails for images and video files.
To support remote thumbnails for video files will require to install video package on the server (ffmpeg or avconv) and to update config.php file with
'enabledPreviewProviders' => array(
'OC\Preview\Movie'
)

**Comment by errotu** [comment]
Thanks a lot for the implementation of this very useful feature!
Do you know when the release will be published?

**Comment by rperezb** [comment]
We are currently working on the regression test
The plan is to send it to Apple this week, likely to be in the market beginning of May

**Comment by rperezb** [comment]
Already implemented
