### ISSUE TITLE
Improve Sharing data between iOS apps and OwnCloud app

### ISSUE THREAD

**Issue by nona00** [owncloud/ios#386]
When sharing data between IOS apps and the OwnCloud app for uploading purposes there should be the following improvements:

- [ ]  it should be possible to switch the owncloud account in the Upload Dialog
- [ ] the last used folder should be saved and reused (not always "ownCloud")
- [ ] it would be better if Filename and extension where splitted to two different field, so that the user does not accidentally remove the file extension
- [x] the button of the folder selection is named as "Move" (in german: "Verschieben"). This is slightly misleading. It would be better to name it "Select" (in german: "Auswählen")
- [ ] while uploading the window "Uploads" should automatically selected

**Comment by nasli** [comment]
Hi @nona00, thanks for your suggestions, we will consider it for the future.

**Comment by tushevorg** [comment]
Sharing from ownCloud to other apps should be improved as well. For instance, I cannot open text file from the cloud in Safari

**Comment by nasli** [comment]
Hi @tushevorg, that's not an OC app issue, Safari does not support that type of files.

**Comment by nasli** [comment]
@mmattel, @tushevorg, Related with:

"the button of the folder selection is named as "Move" (in german: "Verschieben"). This is slightly misleading. It would be better to name it "Select" (in german: "Auswählen")"

We can not reproduce where the button is named as "Move" could you send as a screenshot, thanks!

**Comment by nona00** [comment]
@nasli: attached are the screenshots. In the folder selection of the upload, the button is named "Verschieben" ("Move")

![img_5952_1](https://cloud.githubusercontent.com/assets/3192606/10242833/249f639e-68f4-11e5-8b4d-4cc313921447.PNG)


![img_5953_1](https://cloud.githubusercontent.com/assets/3192606/10242834/24c1cdc6-68f4-11e5-909b-dffa7cd6626f.PNG)

**Comment by nasli** [comment]
Not is a problem in the app, it is a problem with the translation. 

The en version show "Choose" and the de version was "Verschieben" as you show. Has already been changed and will be within next version. 

https://www.transifex.com/owncloud_robot/owncloud/viewstrings/#de/mobile-ios/38858482?q=choose

Thanks to point it out, you are more than welcome to colaborate with transifex!

**Comment by sronline** [comment]
@nasli : the problem with the translation is fixed in 3.4.6.

But the following issues remain:
1) Last used folder in the upload dialogue is not stored (it defaults to "ownCloud" each time)
2) Not possible to switch the account in the upload dialogue
3) It would be better if Filename and extension where splitted to two different field, so that the user does not accidentally remove the file extension
4) while uploading the window "Uploads" should automatically selected
5) Abort in the upload dialogue does not switch back to the application which has initiated the upload

**Comment by nasli** [comment]
I added to your comment the tast lisk icon, but for improved tracking it is better you create different issues for each enhancement. Thanks!

**Comment by nasli** [comment]
Thanks @sronline, let's keep tracking on these issues
