### ISSUE TITLE
Custom URL Scheme

### ISSUE THREAD

**Issue by marcelocecin** [owncloud/ios#387]
please implement Custom URL Scheme for iOS app

**Comment by ggdiez** [comment]
Hello @marcelocecin ,

Thanks for the suggestion. What is your interest about that? We can implement this feature only to open the ownCloud app from other app or for pass other parameter for example to open in a specific way.

**Comment by marcelocecin** [comment]
function would be to open a folder or file directly, thank you @ggdlez
