### ISSUE TITLE
As a oc user I want to be able to use forbidden characters on the folder and file names froc 0c8.1 server versions on so that the errors will be handled on the server side

### ISSUE THREAD

**Issue by ggdiez** [owncloud/ios#388]
AC:
- Allow forbidden characters on the server on file and folder names
- In case of error, the error message it would be: "The name contains at least one invalid character"
- It won't be allowed the  "/" character the reason is because it will imply deep changes on the code

**Comment by rperezb** [comment]
Done, https://github.com/owncloud/ios/pull/392
