### ISSUE TITLE
tap and hold to move file/folder

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#39]
Currently, long press exposes a menu. That’s a) hard to discover, b) not a pattern on iOS (but rather on Android) and c) duplicating the swipe menu anyway.

A much better use for long press is drag&drop move. Best try it out yourself, there’s a great implementation in the app »iA Writer«. This would also make move more inherent to the interface and remove the need for a dedicated »Move« entry in the context menu.

**Comment by michaelstingl** [comment]
This got implemented in the successor of this ownCloud app. You can test with the TestFlight beta.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
