### ISSUE TITLE
Download a folder

### ISSUE THREAD

**Issue by That-Dude** [owncloud/ios#393]
For instance, I have a folder tree containing JPG's on my OC server, I'd like to cache them on my iPad / iPhone for offline access when I have no Internet connection.

If I could swipe a folder and choose 'cache on this device' and have that entire folder tree downloaded to my device that would be awesome.

**Comment by ggdiez** [comment]
Hello @That-Dude 

For now the workaround is download manually each file :(

Right now in our backlog the "Download folder" feature is not far, so we expect to include this feature in next versions.

**Comment by That-Dude** [comment]
Hi ggdiez

Thanks for the update, I'm really looking forward to this feature. Manually downloading the files in not practical for me as I have >500 and they are in sub-directories, I really need to be able to 'offline enable' the parent folder.

**Comment by rperezb** [comment]
We are currently working on this feature.
@That-Dude I have modified the issue name so that it´s easy for us to identify it.

**Comment by rperezb** [comment]
Work in progress on: https://github.com/owncloud/ios/tree/download_full_folder

**Comment by rperezb** [comment]
AC:
 - All the files in the downloaded folder and subfolders will be downloaded in background.
- The download folder option will be included on the swipe menu under the more option
- Error management, it will follow the same behavior that is followed with files downloaded, in case of any error the full download is cancelled. 
- If a folder is being downloaded, it is not possible neither to: delete, rename or move. Nor the parent folder nor any of its content
- Being on user1 downloading a folder, if you change to user2 the download is cancelled as it currently happens with any download in progress

**Comment by rperezb** [comment]
Done, this will be included within the next iOS versions 3.4.6
Regression test on going on https://github.com/owncloud/ios/tree/release_3.4.6
