### ISSUE TITLE
Multiaccount using dropbox as external storage mixes files of set up accounts

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/ios#394]
### Steps to reproduce

In the server:
1. Enable external storage app.
2. Create two users, user1 and user2.
3. Upload different files to each user.
4. Mount a dropbox folder, be sure access is granted.

In the mobile app:
1. Set up accounts for user1 and user2.
2. Browse files of user1.
3. Change account to use user2.
4. Browse files of user2.
5. Change account to use user1.
6. go to 2. until files are mixed between accounts and user1 can see user2's files or user2 can see user1's files.

### Expected behaviour
There is a warning, or an error telling the user that he is mounting every folder of the SFTP connection.

### Actual behaviour
No warnings, no errors. User mounts / folder showing everything.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
External storage

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, Dropbox (as sandbox)

**Are you using encryption:** 
No

### Client configuration

**Mobile**
iOS 3.4.2

**Comment by SergioBertolinSG** [comment]
cc @LukasReschke 

Added captured packages of the issue
https://s3.owncloud.com/owncloud/index.php/s/t6LxLRxs0Myg1tQ

**Comment by rperezb** [comment]
@LukasReschke is very important your help here to determine where the error lies

**Comment by LukasReschke** [comment]
Can confirm this behaviour not only for Dropbox mounts but also for others if the user has not yet logged-in before to the ownCloud web interface.

I did:

1. Setup as user admin
2. Upload a bunch of data and folders using my fuzzer
3. Create a user test
4. In the iOS app login as admin
5. In the iOS app login as user test

=> User test sees the structure of user admin. The server is returning the correct content and this is an issue within the iOS app.

**Comment by davivel** [comment]
So, the problem does not exist if the test user logs in the web before than in the iOS app?

What happens in the first log-in through the web that does not happen with the first log-in through the iOS app?

Sure this is a problem in the app, and not a problem in the WebDAV entry point? The mobile clients do exactly the same in the first log-in and in all the other log-ins

**Comment by LukasReschke** [comment]
Admin:

```
PROPFIND /master/remote.php/webdav/ HTTP/1.1
Host: 192.168.0.18
Accept: */*
Authorization: Basic YWRtaW46YWRtaW4=
Accept-Language: en;q=1, de;q=0.9
Accept-Encoding: gzip, deflate
Content-Type: application/xml
Content-Length: 321
Depth: 1
Connection: keep-alive
User-Agent: iOS-ownCloud
Cookie: ocpb71s3sihf=v76votvvbvab1m633j9c7qljn4

<?xml version="1.0" encoding="utf-8" ?><a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns"><a:prop><a:getlastmodified/></a:prop><a:prop><a:getcontenttype/></a:prop><a:prop><a:getcontentlength/></a:prop><a:prop><a:getetag/></a:prop><a:prop><a:resourcetype/></a:prop><a:prop><oc:permissions/></a:prop></a:propfind>
```

Testuser:

```
PROPFIND /master/remote.php/webdav/ HTTP/1.1
Host: 192.168.0.18
Accept: */*
Authorization: Basic dGVzdDp0ZXN0
Accept-Language: en;q=1, de;q=0.9
Accept-Encoding: gzip, deflate
Content-Type: application/xml
Content-Length: 321
Depth: 1
Connection: keep-alive
User-Agent: iOS-ownCloud
Cookie: ocpb71s3sihf=v76votvvbvab1m633j9c7qljn4

<?xml version="1.0" encoding="utf-8" ?><a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns"><a:prop><a:getlastmodified/></a:prop><a:prop><a:getcontenttype/></a:prop><a:prop><a:getcontentlength/></a:prop><a:prop><a:getetag/></a:prop><a:prop><a:resourcetype/></a:prop><a:prop><oc:permissions/></a:prop></a:propfind>
```


It looks for me like you reuse the cookie for the different account. There are some measures in place to detect these but generally speaking this will lead to problems.

**Comment by LukasReschke** [comment]
That said some requests do have the correct cookie, but in some cases I definitely see mixups.

**Comment by davivel** [comment]
My point:
- iOS app shouldn's send session cookie from a user and credentials of other user.
- Server shouldn't respond satisfying two users in the same request.

Lose-lose

:(

**Comment by javiergonzper** [comment]
This is very interesting... when we make a change of user we store the current cookies to keep the session and restore the old ones.
Could the server sent us the wrong cookies when we change the user? Because if we are doing something wrong this bug should had appear many months ago.
It is very strange.

**Comment by LukasReschke** [comment]
> Server shouldn't respond satisfying two users in the same request.

Actually the plan is to not support cookies in the WebDAV backend in long-term and rely on authentication tokens which would make a lot of things easier :smile: - But a long way to go :)

> Could the server sent us the wrong cookies when we change the user? Because if we are doing something wrong this bug should had appear many months ago.

No. As far I can tell this involves nothing from the server-side.

**Comment by javiergonzper** [comment]
Ok. We have to check then what is happening with that cookies then.
Thanks a lot for your work @LukasReschke you have locate a lot the problem :+1:

**Comment by davivel** [comment]
> Actually the plan is to not support cookies in the WebDAV backend in long-term and rely on authentication tokens which would make a lot of things easier :smile: - But a long way to go :)

Sure, unfortunately. Some deployments are using cookies to determine load balance, AFAIK, so many things would be broken if this was just removed.

**Comment by nasli** [comment]
The problem was that the first request was received before the second one.
Fixed within PR:
#410 
owncloud/ios-library#91
