### ISSUE TITLE
Dataname change after uploading

### ISSUE THREAD

**Issue by gismoat** [owncloud/ios#395]
I use ownCloud 8.0.3 with ownCloud iOS App 3.4.1
When i upload a picture via iOS App with filename IMG_1234.jpg than rename the APP automaticly the file to Photo-2015-06-06-14-02-52_1234.JPG . This issue i haven't on the last IOS APP 3.4.0 Does anyone know how I can change this? I would not that my filename was remaed after the upload.
thanks
Werner

**Comment by javiergonzper** [comment]
Hello @gismoat 

Do you upload the files from the gallery?

Regards

**Comment by gismoat** [comment]
Hello @javiergonzper
i upload the files where i maked with my iphone.
I go with the owncload app to my folder where i would like upload the picture and press the + Button.
And i use the Picture/Video upload funktion and add a picture from my gallery on my iphone.

**Comment by javiergonzper** [comment]
Ok, that then it is the normal behavior, when we upload image we use the format Photo-xxxx-xx-xx-xx-xx-xxxx.JPG not the IMG_XXXX.jpg of iOS.
I do not know if @jancborchardt want to change the format of the names of the files...

**Comment by gismoat** [comment]
Hi,
i have this behavior since i make the last update to IOS owncload 3.4.0. Before i haven't this behavior.
I hope @jancborchardt would like implement an option that i can set YES/NO for a automatically rename.

cheers
Werner

**Comment by jancborchardt** [comment]
Hm, did we say we want to force rename photos? I don’t remember that. Because that makes it pretty difficult to know which photos you have and don’t have synced. I would not do any renaming at all. (Unless the characters are forbidden of course – which isn’t the case here.)

**Comment by rperezb** [comment]
We defined the name of the images on: https://github.com/owncloud/ios/issues/57
If I remember right, we decided not to use the IMG_XXX  in order to avoid duplications from other devices uploading images on the same folder.
The format that we went for is to use the date when the image was taken

**Comment by gismoat** [comment]
Hi rperezb, 
thanks for your answer and the link to #57 .
Have every one an idea how i can downgrade the IOS APP?
@jancborchardt Do you know where i can get another version or can make an option to set yes or now for renaming?
I would not like the automaticly rename on my files !
I can remeber that on the version 3.3.x i havent this issue.

**Comment by jancborchardt** [comment]
@rperezb hmm, in #57 renaming the file was a given. We never questioned that. Since apparently people have problems with this, we should keep the original filename.

If there are conflicts with photo names from other devices, then we can append a " (2)" to the filename. But uploading should not change the name as you can not compare again when you also transfered them via a different means.

**Comment by rperezb** [comment]
Before taking the decision of changing this, I'd suggest to listen to other users.
For instance, on the core there is a related issue reported: https://github.com/owncloud/core/issues/18449

**Comment by jancborchardt** [comment]
@rperezb this is a different issue I’d say. Even with filenames based on date and seconds there can still be conflicts. There needs to be proper conflict management either way.

**Comment by rperezb** [comment]
@jancborchardt let's talk about this one in Berlin conference

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
