### ISSUE TITLE
Unchecked Error Condition: Malloc

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/ios#398]
Got some reports of this by VeraCode, probably worth changing to make future reports look smaller :speak_no_evil: 

> Unchecked Error Condition (CWE ID 391)
> The result of this call are not captured. Failing to check the return code can result in unexpected behavior.
> Effort to Fix: 2 - Implementation error. Fix is approx. 6-50 lines of code. 1 day to fix.

https://github.com/owncloud/ios/blob/b2cd50d21a3e2e4fc0effe8d390d4ca6547ab8b4/Owncloud%20iOs%20Client/Network/Uploads/PrepareFilesToUpload.m#L131
https://github.com/owncloud/ios/blob/b2cd50d21a3e2e4fc0effe8d390d4ca6547ab8b4/Owncloud%20iOs%20Client/Network/Uploads/PrepareFilesToUpload.m#L145
https://github.com/owncloud/ios/blob/b2cd50d21a3e2e4fc0effe8d390d4ca6547ab8b4/Owncloud%20iOs%20Client/Network/Uploads/PrepareFilesToUpload.m#L290
https://github.com/owncloud/ios/blob/b2cd50d21a3e2e4fc0effe8d390d4ca6547ab8b4/Owncloud%20iOs%20Client/Network/Uploads/PrepareFilesToUpload.m#L304

**Comment by LukasReschke** [comment]
Note: Not high priority from my PoV but would be nice to have it changed at some point if easily possible.

**Comment by ggdiez** [comment]
Hello @LukasReschke 

As you can see is the same method in all the cases. It's this line: 

Byte *buffer = (Byte*)malloc(chunkSize);

This line is for create a buffer (memory allocate with a specific size). This buffer is for store the chunks of images/videos of the iPhone Camera Roll. We use this buffer to not used too much memory moving big files from the Camera Roll to the ownCloud app. We use that correctly and then we release this reference.

I don't know why VeraCode it's failing to check the return of this call. 

Can I check with VeraCode to test if doing changes the fail disappear?

**Comment by rperezb** [comment]
Close for inactivity, if needed, reopen
