### ISSUE TITLE
Login failed when it actually works

### ISSUE THREAD

**Issue by stevejordi** [owncloud/ios#399]
We have a major question, we have installed our server and everything is fine. But some users can't connect via their mobile devices.
We have noticed that their access are blocked by our brute force prevention technology we have installed (fail2ban) because each time an mobile connects, it keeps sending "login failed" message even when they connect correctly.
A folder refresh sends "login failed" in the owncloud.log (Linux)
Those are regarded as hacks. In this case they are not.

As an example, when I connect my iPhone or Android Tablet I generate 10 lines like this one
{"app":"core","message":"Login failed: 'jordi' (Remote IP: 'nnn.nnn.nnn.nnn', X-Forwarded-For: '')","level":2,"time":"2015-07-01T13:39:19+02:00"}

Why are the mobile apps sending those login failed messages?
Android and iOS all behave the same way.

**Comment by javiergonzper** [comment]
Hello @stevejordi 

Looks like you have a configuration problem on your server when you try to access using the WebDav interface.
You should ask on the core (https://github.com/owncloud/core/issues/) or on the forums (https://forum.owncloud.org/) to get help to configure your server.

Regards
