### ISSUE TITLE
iOS cannot connect via external site

### ISSUE THREAD

**Issue by layoric1** [owncloud/ios#400]
I have freeNAS installed, ownCloud installed via plugin rep. Purchased the iOS for iPhone 5s ownCloud app. I can connect on my network via all methods on PC and iPhone. However, connecting via ddns or external IP directly from iphone when OFF my internal network, the page is NOT forwarded correctly, seemingly. It loads the ddns website address, I click the link below to add the domain name as trusted domain, then it loads, forever... The page then forwards to 'this webpage is not available' message, basically times out. It LOOKS like it's trying to forward to my internal IP, which won't work off my network of course.

My next attempt is to load the page on the iphone via the external IP directly. The same result as above occurs. Is this something with the trusted domain message it's stating, or could it be something else?

**Comment by javiergonzper** [comment]
Hello @layoric1 

If using safari with your iPhone have the same result but with a computer not... could be a problem at network level on iOS that not follow that redirections. You could try to use a different ddns provider like noip.com.
Maybe you can ask on the ownCloud forums, perhaps someone had a similar configuration.

Regards

**Comment by layoric1** [comment]
But the same result occurs on iPhone with external IP, doesn't matter if using ddns or external IP, same result. 

Isn't this the forum for those who purchased the IOS app?

**Comment by RealRancor** [comment]
@javiergonzper I think the issue can be closed as it seems the user fixed its setup by usin a VPN:

https://forum.owncloud.org/viewtopic.php?f=24&t=29031&p=90657#p90657

@layoric1 
> Isn't this the forum for those who purchased the IOS app?

This is the issue tracker of the iOS app where bugs within the app should be reportef.

**Comment by javiergonzper** [comment]
Thanks a lot for your help @RealRancor :beers:
