### ISSUE TITLE
when will ios 3.4.2 available

### ISSUE THREAD

**Issue by Froster** [owncloud/ios#402]
hi,

is there any releasedate for 3.4.2 (ios)?

**Comment by MorrisJobke** [comment]
cc @rperezb

**Comment by rperezb** [comment]
Hey @Froster , the next version will be the 3.4.4.
We sent it to Apple last Tuesday, 7 July. Now it is pending Apple approval. We expect it to be released next week, around July, 16th

**Comment by cdamken** [comment]
@Froster you can have it in ES. Give me a call to explain how to do obtain it.
