### ISSUE TITLE
Files don't load

### ISSUE THREAD

**Issue by felixbello** [owncloud/ios#403]
### Steps to reproduce
1. Start ownCloud App
2. Choose 1 File which is not yet downloaded (not txt, this ones seems to run)
3. nothing... that's all

### Expected behaviour
The File should be open

### Actual behaviour
Nothing.. there  is an text.. that is preparing to download, but it don't go forward

### Server configuration
**Operating system**: Debian 7

**Web server:** Apache/2.2.22 (Debian)

**Database:** 5.5.43-0+deb7u1

**PHP version:** PHP 5.4.41-0+deb7u1

**ownCloud version:** ownCloud 8.0.4 (stable)

**Updated from an older ownCloud or fresh install:** Updated from an older ownCloud

**List of activated apps:**

Enabled:
 - activity
 - files
 - files_external
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
Disabled:
 - external
 - files_encryption
 - files_locking
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

<?php
$CONFIG = array (
  'maintenance' => false,
  'instanceid' => 'oc7383b317c9',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
  'datadirectory' => '/var/www/data',
  'dbtype' => 'mysql',
  'version' => '8.0.4.2',
  'dbname' => 'behost_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxxxxxx',
  'installed' => true,
  'theme' => '',
  'trusted_domains' =>
  array (
    0 => 'ns1.behost.ch',
    1 => 'owncloud.behost.ch',
  ),
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'xxxxxxxxxxxxxxxxxx',
  'mail_smtppassword' => 'xxxxxxxxxxxxxxxxxxx',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'behost.ch',
  'secret' => 'xxxxxxxxxxxxxxxxxxxx',
);

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by ggdiez** [comment]
Hello @felixbello 

Your problem is very strange as you say the normal behaviour is that the file start to download. 

Some questions: 

- Are you having problems only with the files stored in the sftp or with all the files?
- Have you testing with the Android app?

Best,

**Comment by ggdiez** [comment]
Other possibility @felixbello 

Do you have files marked as a favorite? 
Right now the current version 3.4.1 have a bug related with this. The bug is fixed in the next version, coming this week I hope.

If you have a files marked as a favorite, un-marked these files and try again.

**Comment by felixbello** [comment]
Hi ggdiez

This Problem it is with every file from every folder.
And yes i had marked as favorite 2 files, but every other file has the Same issue.
Yeah i had from am friend an Tablet with android, and here was all Fine.

I will To reinstall the App and also To change an other Server.

**Comment by felixbello** [comment]
Strange... So i just reinstalled it, and Now it Runs well! This Time i dont Mark Andy file as favorite and Hope it will still run!

**Comment by ggdiez** [comment]
I'm happy to hear that the apps works, you can marked your files as a favorite in the next version.
