### ISSUE TITLE
[Help_guide] As a new OC user I want to see a help of what the app may do

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#404]
The first iteration for the iOS Help guide is available on: https://github.com/owncloud/ios/commits/help_guide

@jancborchardt what do you think?

**Comment by rperezb** [comment]
cc @nasli

**Comment by jancborchardt** [comment]
@rperezb @nasli can you post a link to the video of that here? :)

**Comment by rperezb** [comment]
done: https://s3.owncloud.com/owncloud/index.php/s/gZGWNu5AF3KUQWO
This link will expire next 22th of July

**Comment by jancborchardt** [comment]
Nice! (Why the expiration? ;)

Just a few improvements:
*  the cloud on the first slide should be in the exact same position as the one in the placeholder, if possible
* put the Share icon on the »Share« slide as well, maybe between the phone and the »Share« text
* »Multiple accounts«. And the text below »Connect to all your clouds«
* last slide:
  * »Your private files synced anywhere« (missing an s)
  * remove white border around filetype icons
  * remove the exclamation mark and red circle around the Log in button

I would also like to reduce it from 6 slides to 5 or 4. I’d say we should already show the log in button on the Multiple accounts slide and cut the last one. Then maybe also cut the first welcome slide and directly start with the features. That way people get to the app faster. (Also, on the bottom we should have a link to »Skip and log in«.)

cc @MTRichards

**Comment by nasli** [comment]
Thank you for your feedback @jancborchardt ;)
I agree with all your suggestions except the last one, I do not think 6 slide are too many, but let see what other think about.

**Comment by rperezb** [comment]
Done, this will be released within the next iOS version, 3.4.5
