### ISSUE TITLE
Instant upload does not work in background

### ISSUE THREAD

**Issue by melvincornelissen** [owncloud/ios#414]
The sync is only done when the app is opened.

**Comment by javiergonzper** [comment]
@melvincornelissen it works in background but only when the app detect a significant change of position. Is the only way that Apple allow us to do things in background.

**Comment by melvincornelissen** [comment]
Makes it even more strange because there where about 50 photos that needed to be synced? Isn't that significant enough? 

Thanks for the fast response!

**Comment by javiergonzper** [comment]
What I mean with change of position is a geographic position. We wakeup ownCloud iOS App when the user move himself to an other place. It is the only way to wake up the app in background.

**Comment by melvincornelissen** [comment]
Oh sorry, that position :-p. Guess I have to move my ass a little more. Thanks!

**Comment by javiergonzper** [comment]
Yes, a little bit more :walking: 

You are welcome :wink:
