### ISSUE TITLE
OWNCLOUD IOS APP on iphone 5 looses account configuration everyday

### ISSUE THREAD

**Issue by fuloperformer** [owncloud/ios#415]
Hello, im having an issue with owncloud ios app that looses account configurarion every days.

is there anything to do for solve this?

thanks

**Comment by javiergonzper** [comment]
It is a know problem. Apple have a bug related with the keychain, we are waiting until Apple approve a new version of the iOS ownCloud App that should fix it a little bit... but the main problem is on iOS8.

By now you can kill the app and open it again when the problem happen.

**Comment by fuloperformer** [comment]
Thanks Javiergonzper,

how do i kill the app?

**Comment by javiergonzper** [comment]
Look at this video:
https://www.youtube.com/watch?v=h_iEkOMEvAw

**Comment by fuloperformer** [comment]
thanks

**Comment by javiergonzper** [comment]
You are welcome :wink:
