### ISSUE TITLE
With a compiled App cannot navigate to folder

### ISSUE THREAD

**Issue by ranby** [owncloud/ios#417]
When a folder is pressed in the file list, the app tries to navigate to that folder but fails and goes back to the root folder. Any ideas why this happened? Have I missed doing something when setting up the project?
Also the app crashes when the settings tab is pressed.
Thanks!

**Comment by rperezb** [comment]
@ranby thanks for reporting this.
We'd appreciate further detail in order to be able to reproduce the error, since from our end it's working fine.
- Server version
- Device version
- ownCloud app version
- Is this a new installation or an update?
- Do you have more than 1 account registered?
- Is it possible to download a file?
There are 2 issues reported here, in general basis we'd rather 1 report per issue to have a better understanding.

**Comment by ranby** [comment]
I understand. I just hoped that someone would recognise the problem and knew a fix. 
But I was building the app from the develop branch and ran it on an iPhone 5S. This is the first time that I try to setup the project and I therefore suspect that I have missed something quite simple. 

When pressing a folder I get this error message in the console:
`CUICatalog: Invalid asset name supplied`

I suspect there is some problem with database communications since I find a lot of null values when I try to debug. Do I need to do anything special in order to get the database up and running. I have followed the steps in SETUP.md file and created app group with all the bundle IDs. 

Hope this helps, thanks you!

**Comment by markusphi** [comment]
Here is the Same... 

8.0.4 Server version
IPAD 4 MD522/FD Device version
3.4.4 ownCloud app version

Is this a new installation or an update?
Update Own Cloud APP

Do you have more than 1 account registered?
No

Is it possible to download a file? There are 2 issues reported here, in general basis we'd rather 1 report per issue to have a better understanding.

Yes, it ist possible to Download a file from the / folder
but "tab" a Subfolder changes to the Subfolder and "drop back" to /

Additional the App dont store Username / Password

App Version 3.4.1 work without this Problems
Server version
Device version
ownCloud app version
Is this a new installation or an update?
Do you have more than 1 account registered?
Is it possible to download a file? There are 2 issues reported here, in general basis we'd rather 1 report per issue to have a better understanding.
Sorry for my bad english
German: 
Beim tippen eines Unterordner wechselt die Anzeige in den Unterordner, verhält sich dann aber als ob man wieder zurück angewählt hat und landet wieder im / . Außerdem speichert die 3.4.4. App kein Username und Passwort.
Mit der App Version 3.4.1 davor geht es am selben Server einwandfrei.

**Comment by nasli** [comment]
Hi @markusphi, this issue is not the same.
I just moved it to a new one #419.

**Comment by nasli** [comment]
Hi @ranby, where do yo get null? Could you put some logs of them?
Take a look at the following issues #407, #329  maybe help you.

**Comment by rperezb** [comment]
Close for inactivity, if needed, please reopen
