### ISSUE TITLE
Activity Stream View in iOS

### ISSUE THREAD

**Issue by MTRichards** [owncloud/ios#422]
Ad an ownCloud user, I want to be able to see a list of my recent activities on the mobile device so I can quickly find files and actions that occur on the device.

Acceptance Criteria:
- Mobile app should query the activity stream API from the server
- Should be a separate tab, where the activity stream is shown in reverse chronological order
- Interface should look similar to the activity stream app on the server, but updated/ adjusted slightly for iOS

@karlitschek @jancborchardt @rperezb @javiergonzper @cmonteroluque 
owncloud/activity#349

**Comment by karlitschek** [comment]
looks good. :-) 
The App should also trigger a local iOS notification when a new activity appears on the server.

**Comment by jancborchardt** [comment]
Yup, as discussed before.

**Comment by ggdiez** [comment]
Maybe also is interesting that the activity appears in a widget with the last changes of the files accesible by the user and the possibility to open one of this in the ownCloud app.

**Comment by rperezb** [comment]
Another AC it could be to show this per account basis. 
- If you tab on a folder, you access to the folder content
- If you tab on a file
        + Being the file downloaded, you preview the file, being the previewd available if not access to the details view
        + If the file is not downloaded, it´s downloaded
Web interface:
![screen shot 2015-07-28 at 11 01 32](https://cloud.githubusercontent.com/assets/1846927/8927488/0c33f834-3518-11e5-8471-1dda3834b6d1.png)
Share link interface
![img_1619](https://cloud.githubusercontent.com/assets/1846927/8927547/7ba47dd8-3518-11e5-9930-c5b091d1a10b.PNG)

I would mix both of them, I mean, I will add the activity icon (shared, downloaded, uploaded..) over the file/folder icon.

Doubt: having this new view, it is needed the share link view? In both of them we are showing the share link info



The if

**Comment by jancborchardt** [comment]
The shared view should stay there, as it’s a static list. What we’re talking about is an activity list, something chronological. This is supposed to replace the currently existing »Uploads« tab.

**Comment by rperezb** [comment]
@jancborchardt the shared view, it´s dinamic too; there every file/folder by link on that account (no matter from where) are listed, they are listed in chronological order.
About the uploads tab, I would say that it´s still needed, from that view, failed uploads are handled.

**Comment by jancborchardt** [comment]
@rperezb I know, but it’s still different from the activity view and should be kept separate.

The activity view should include error handling. Errors should always show up top, see the related issue in the desktop client: https://github.com/owncloud/client/issues/1745

**Comment by onewaypub** [comment]
Some ideas: If the activity stream could appear in the lock screen there would be an nice combination with the announcment center app https://github.com/nickv-oc/announcementcenter

**Comment by jancborchardt** [comment]
@onewaypub every single activity is not as important that it warrants display on the lock screen. The only thing that we should display there are notifications where action is required, like accepting a share.

It’s not about all the things we _can_ show to people, it’s about what’s actually necessary and enough to help, but not distract people from their other more important things.

**Comment by CaptionF** [comment]
@MTRichards @rperezb @jancborchardt  prospect waiting - what can we share about implementation?

**Comment by MTRichards** [comment]
As of right now, it remains a roadmap item. Ideall by the end of Q2 we can put this in, but without more info on the prospect, we have to finish the sharing work first.

**Comment by MTRichards** [comment]
Returning to this issue again for the purposes of design and planning.

There is an activities view in the app
Activities include information from the server API, such as file activity, comments, shares
Activity window needs a size limit
Activity view needs a search bar / filter
Activity should show the name of file in large text, with smaller text showing the action taken and the name of the actor, as well as a thumbnail of the file that was affected
