### ISSUE TITLE
We shall not have failing continuous integration

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/ios#423]
As an ownCloud developer, I would like to actually see the builds passing instead of failing. Red is such a bad color. 

Acceptance Criteria:
- Builds are passing (https://travis-ci.org/owncloud/ios)
- Color green is back :green_heart: 
- Somebody actually takes care of what CI says

**Comment by LukasReschke** [comment]
https://travis-ci.org/owncloud/ios/builds - this does not look too good…

**Comment by LukasReschke** [comment]
@cmonteroluque FYI

**Comment by cmonteroluque** [comment]
@LukasReschke checking...

**Comment by LukasReschke** [comment]
This is just so ~~unprofessional~~ very much questionable:

![2015-07-27_20-24-51](https://cloud.githubusercontent.com/assets/878997/8914114/a79b068a-349d-11e5-93f3-c355395180e0.png)

**Comment by cmonteroluque** [comment]
assigned to @rperezb to assign within the iOS team.

As to the previous comment, I would prefer to have an explanation before discussing professionalism, but yes, let's figure this out.

**Comment by LukasReschke** [comment]
Apologize if this was taken as an offense. It was just barely meant as comment with regards to the public perception, I was not trying to refer to our team which does a great job. My point here is that as a potential contributors this will look quite unserious when they take a look at our repository. A red cross on each change is barely something very common in open source projects.

If we don't have CI on this repository: Fine as well. Then we should disable it completely instead of having an undocumented unexpected behaviour.

So let's all have a :beers: :speak_no_evil:

**Comment by rperezb** [comment]
@LukasReschke we do care about CI, it is usually green, this is our favorite status! :green_apple: 
The thing is that sometimes, we update the xCode version against the one we are compiling the app and travis it is not updated, so it fails till it is updated. Right now, not only we have to take into account the xCode version but also the swift one.
@ggdiez is working on it

Sure, let's have a :beers: but not a virtual ones, next ownCloud conference!

**Comment by rperezb** [comment]
fixed via: https://github.com/owncloud/ios/pull/424
