### ISSUE TITLE
[Share] As an OC user I want to be able to share data with ownCloud users

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#425]
AC:
- When I do swipe over a file/folder, it will be shown an option called: Share
- This implies that the Share Link option will be overwrittent
- Having selected the Share option a new view is shown, see mockup
  + The mimetype of the file is added
  + The file name is shown and the path where it is stored

  + There is an option, "share with user or group" same idea as the web interface, it is typed the name of the user with whom it will be shared, by tapping on the decided user, it will be shared with him
  + Below the search tool, those users with whom the file or folder is shared are listed
  + First iteration, it won't be possible to modify privileges neither to stop sharing with a user

  + Below of the shared users it will be offer a check button: Share link, once this button is enable, it will be generated the link
  + The user may device to share the link with password enable or with expiration time

NOTE: 
- This is a global issue, as we usually work, this has to be divided in vertical issues so that we split the job
- This is the very first idea, we need other users feedback

@MTRichards  @jancborchardt  @cmonteroluque @javiergonzper @ggdiez @nasli @purigarcia 

![screen shot 2015-07-28 at 17 54 14](https://cloud.githubusercontent.com/assets/1846927/8936301/b2120636-3551-11e5-90f5-4f4be1faaf17.png)

**Comment by rperezb** [comment]
https://github.com/owncloud/ios/issues/336

**Comment by jancborchardt** [comment]
@rperezb @javiergonzper @ggdiez @nasli @purigarcia looks good in general, but please use iOS 8 as base for your mockups? :D

**Comment by rperezb** [comment]
@jancborchardt yes :dizzy_face: it was the tool, http://pencil.evolus.vn/  it is not updated...
I have to look into other tools
The main thing was to start a discussion, @MTRichards wants to start working on it...pretty soon :+1:

**Comment by ggdiez** [comment]
Hi @jancborchardt  @rperezb  @nasli @purigarcia @MTRichards @cmonteroluque 

Using the Raquel idea these are my mockups. The structure of the view is the same but I have done some changes. 

- The search option better in other view as Google Drive. 
- The checkbox of the Shared Link, I prefer use a switch, you can also use the switch for un-share option.

My mockup: 

Shared 0 view, it's the view when the user tap in share option on a not shared file.

Shared 1 view, it's when the user have share the file with an user and shared by link with password and password protect options.

Find user view, it's when the user tap in "Add User or Group" button. In this view the user can search for the user/users or group/groups to share the file and the permissions. 

![shared 0](https://cloud.githubusercontent.com/assets/2051473/8953889/0244ffc4-35e2-11e5-87fb-fa5607d22933.png)
![shared 1](https://cloud.githubusercontent.com/assets/2051473/8953891/05b0948e-35e2-11e5-82e0-0d92be89471e.png)
![find user](https://cloud.githubusercontent.com/assets/2051473/8953894/0949a45a-35e2-11e5-8270-21fd26687c84.png)

**Comment by tobiasKaminsky** [comment]
I like the latest three mockups.
But the permission options has to be editable for every user individually.
So maybe these settings can popup when the user selects a user/group.
And after that it is shown by icons and can be edited via long-click

**Comment by ggdiez** [comment]
@cmonteroluque @MTRichards @PVince81 @DeepDiver1975 
Is there an API in the server side to search for users or groups with a filter?

**Comment by ggdiez** [comment]
@tobiasKaminsky  for the first iteration the part of the permissions is not included. So the mockup of the third image will be the same without the "options" section. 

But I'm thinking in a solution for the next iteration.  ;)

Thanks

**Comment by tobiasKaminsky** [comment]
@jancborchardt pointed me to this issue as I am developing for android and he said it would be good that both apps have a similar behaviour.
Therefore it would be great to think everything to the end :)

So, do you think it would work with a popup? With this the list of the user would not be truncated by the options menu.

**Comment by jancborchardt** [comment]
We can simplify this. The »Share with user or group …« section should not be a popup. It should be much like the web interface dropdown, with the »can edit« and »can share« sections in the same line of the username, to the right.

I’ll work on a mockup.

**Comment by ggdiez** [comment]
I have checked the Share API documentation and there are no way to know if a file shared by link have password protected enabled. 

As @schiesbn said me the only way for the moment is use the "share_with" column in the response. It's ugly but there are not other way.

**Comment by rperezb** [comment]
@ggdiez WIP the server API https://github.com/owncloud/core/issues/16646

**Comment by rperezb** [comment]
related to the desktop client: https://github.com/owncloud/client/issues/3537 and android: https://github.com/owncloud/android/issues/880

**Comment by tobiasKaminsky** [comment]
@jancborchardt 
> We can simplify this. The »Share with user or group …« section should not be a popup. It should be much like the web interface dropdown, with the »can edit« and »can share« sections in the same line of the username, to the right.
>I’ll work on a mockup.

A mockup would be great.

**Comment by DeepDiver1975** [comment]
consolidated server api spec is here - https://github.com/owncloud/core/issues/18117

**Comment by bsElyes** [comment]
Any New about this work ? :D

**Comment by rperezb** [comment]
Work in progress, first part is the OCS- Api, then we will update the iOS client.
In the meantime, we are working on the new view, https://github.com/owncloud/ios/tree/share_by_link_with_options

**Comment by guruz** [comment]
^^ FYI @dragotin @ogoffart @rullzer @jturcotte etc if we do this in the client, it could look similar

**Comment by rperezb** [comment]
Yes, it would be great!

Indeed, you are welcome to the mobile and pals room @ownclouders conference, we may talk about it and the flow :smile:

**Comment by jancborchardt** [comment]
BTW: As live mockup essentially, please look at how it is done on the server – this is always the master regarding design. For specific optimizations it will be mostly showing stuff directly (to not need to type on mobile), but we already talked about that @rperezb :)

**Comment by rperezb** [comment]
Yes, we talked about it, mostly we will follow https://github.com/owncloud/ios/issues/425#issuecomment-125887543
We will add and i, closed to the user name so that when it´s clicked it may be modified the privileges and remove the share

**Comment by rperezb** [comment]
For the next version, 3.4.5, the first step is done, add a new share view and add additional options for the sharelink (expiration date and password)
Share with other users will come in the next version

**Comment by rperezb** [comment]
Share with users in progress on: https://github.com/owncloud/ios/tree/sharee_with_user

**Comment by jancborchardt** [comment]
@rperezb @ggdiez @javiergonzper @nasli show screenshots as soon as you can please. :)

**Comment by rperezb** [comment]
![screen shot 2015-10-13 at 11 26 40](https://cloud.githubusercontent.com/assets/1846927/10451055/39519872-719e-11e5-89d0-8b803bf8ad0a.png)
![screen shot 2015-10-13 at 11 26 59](https://cloud.githubusercontent.com/assets/1846927/10451060/3e2f1a4a-719e-11e5-8cbf-588ec002110a.png)
![screen shot 2015-10-13 at 11 33 10](https://cloud.githubusercontent.com/assets/1846927/10451063/4429e5e2-719e-11e5-95f3-73f4e678767e.png)
![screen shot 2015-10-13 at 11 32 40](https://cloud.githubusercontent.com/assets/1846927/10451065/46d46678-719e-11e5-93c7-be0136383db0.png)

**Comment by rperezb** [comment]
another one to show how errors are handled: 
![screen shot 2015-10-13 at 17 36 37](https://cloud.githubusercontent.com/assets/1846927/10461694/efa59da8-71da-11e5-9c12-ab44decde05c.png)

**Comment by rperezb** [comment]
This is done and it will be available within the next ownCloud iOS versions
