### ISSUE TITLE
The Project compile error

### ISSUE THREAD

**Issue by mangorui** [owncloud/ios#427]
![2015-07-29 9 27 07](https://cloud.githubusercontent.com/assets/5945826/8948273/100c8a64-35d8-11e5-9a2d-7ef47e659f2d.png)

Hello, There are some errors when I compile the project:
No known class method for selector 'getUserSessionToken'
 No visible @interface for 'OCCommunication' declares the selector 'readFolder:withUserSessionToken:onCommunication:successRequest:failureRequest:'

**Comment by nasli** [comment]
Hi @mangorui, 
how you cloned the project? did you do the following steps?
```
git clone git@github.com:owncloud/ios.git
git submodule init
git submodule update
```

**Comment by mangorui** [comment]
i see，thank you very much！
