### ISSUE TITLE
Filename is not displayed entirely 

### ISSUE THREAD

**Issue by Kawohl** [owncloud/ios#428]
Hy there this is a feature request.

It should be possible to display the entire Filename.

Use case:

I have like 10 Files with a certain length x. The Filename differs in the middle of the filename.

eg.

testowncloudhappytes1.happytestgrumpycat.doc
testowncloudhappytes2.happytestgrumpycat.doc
.....
...
...
testowncloudhappytes9.happytestgrumpycat.doc

For the user the entire filename is only visible if he wants to change the filename. 
He should be able to see the entire filename.

**Comment by ggdiez** [comment]
Hi @Kawohl 

Yes would be perfect if we can see the full names of the files, but the space is limited by the device size. :(. 

An idea could be use marquees for longs file names. For example with a long press in the name start to move until the last of the name. 

@jancborchardt what is your opinion?

**Comment by jancborchardt** [comment]
@ggdiez can you research how others like Dropbox and Google Drive solve this problem?

**Comment by ggdiez** [comment]
@jancborchardt Dropbox and Box cut the name by the middle like us and Google Drive cut the name by the end.

**Comment by jancborchardt** [comment]
@ggdiez I know – but do they do additional stuff like marquee on long press if the filename is even longer?

**Comment by rperezb** [comment]
This is duplicated of: https://github.com/owncloud/ios/issues/180
Let's track it there, thx
