### ISSUE TITLE
password policy for public link sharing

### ISSUE THREAD

**Issue by CaptionF** [owncloud/ios#429]
this need to be covered not only on the web, but also on the sync client and the ios app.

https://github.com/owncloud/enterprise/issues/733 
@MTRichards, not just for web ui.

**Comment by javiergonzper** [comment]
This is also under develop. We are working on everything related with the share.

**Comment by rperezb** [comment]
Yes, this is currently being developed on the iOS side: https://github.com/owncloud/ios/issues/336
WIP: https://github.com/owncloud/ios/tree/share_by_link_with_options
