### ISSUE TITLE
LDAP User sharing on iOS app

### ISSUE THREAD

**Issue by CaptionF** [owncloud/ios#430]
@MTRichards any news ?
00003625

**Comment by MTRichards** [comment]
Yes - Currently working on it in this sprint to get it started. Expecting it to take at least 4 weeks, if not longer, but we are in development now.

**Comment by CaptionF** [comment]
Great!
thanks a lot!
Matthias 
Please excuse typos as this mail was created on smart device

**Comment by rperezb** [comment]
Thanks for opening this issue.

Let´s track it on this previous one: https://github.com/owncloud/ios/issues/425

It will take longer, pending server owncloud/core#16646
