### ISSUE TITLE
After update, App shows account setup screen

### ISSUE THREAD

**Issue by cycloon** [owncloud/ios#431]
After updating the owncloud app on an iPhone 6 it shows the account setup screen like on first start. If I put in my credentials, I can see, that there are now two accounts (identical ones) and I see every folder two times.

Looks like something is wrong with detection of the first startup screen. It should not show if I already have an account. There even isn't a button to cancel that screen...

I have seen this behavior for several times now (maybe after every update?)

**Comment by rperezb** [comment]
Thanks for reporting this.

There is a known bug related to the iOS keychain that ownCloud uses to securely store account credentials. If the app has not been used for a while and you open it, your credentials (server, user and password) will be required even though you have logged in previously. The short term fix is to close the app completely and open it again. By doing so, the file list will appear as expected without the need to log in again.

**Comment by cycloon** [comment]
The workaround you stated does not work. If I kill the app (double tap home button and flick app upwards) then the problem persists. I have no way accessing my data. The only way is filling out that form on the startup screen again and so creating a second account.

I am not sure if this really correlates to that iOS keychain bug.

Would it be possible to offer a cancel button on that first run screen? Please reopen this issue.

**Comment by cycloon** [comment]
Another problem makes this even more severe: if I provide my account again, I see my files. When I then press the settings button, app crashes. After restarting it shows the welcome screen again!
