### ISSUE TITLE
 It is not possible to come back from full screen in ipad

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#436]
- STEPS TO REPRODUCE IT
1. tap to see the pdf/video/image in full screen
2. tap to come back

- CURRENT BEHAVIOR
          -- unless you rotate, it's not possible to come back. Sometimes the pdf is not shown correct anymore

- EXPECTED BEHAVIOR
         -- it is possible to come back from full screen

- DEVICE
          -- it happens using ipad v.9
          -- it doesn't happen using iphone v.9

**Comment by rperezb** [comment]
Work on: https://github.com/owncloud/ios/commits/ios9_come_back_full_screen_ipad

**Comment by rperezb** [comment]
Ready to be reviewed and merged

**Comment by cdamken** [comment]
@MorrisJobke 

00003933

**Comment by rperezb** [comment]
fyi, this has been blocked due to a bug within iOS9 versions, we will fix it within the next ownCloud app version

**Comment by cdamken** [comment]
@rperezb Will be the solution in 3.4.6?

**Comment by rperezb** [comment]
@cdamken I'm afraid not, we have just postponed it for one version after

**Comment by rikirp** [comment]
Would like to get this fixed also. Any idea when this wil be done ???

**Comment by rperezb** [comment]
yes, we plan to freeze the code between this week and next one for the release 3.4.6
Full screen is expected for the following one, 3.4.7

**Comment by MorrisJobke** [comment]
@MTRichards Can we please schedule this for 3.4.7? Thanks ;)

**Comment by rperezb** [comment]
@MorrisJobke this has been fixed on https://github.com/owncloud/ios/tree/ipad_full_screen
It´s qa pending, our goal is to include it within 3.4.6

**Comment by MorrisJobke** [comment]
> @MorrisJobke this has been fixed on https://github.com/owncloud/ios/tree/ipad_full_screen
> It´s qa pending, our goal is to include it within 3.4.6

Nice :)

**Comment by rikirp** [comment]
Thanks !!!! Hope to see it soon 👍

Envoyé de mon iPad

**Comment by rperezb** [comment]
Done, this will be included within the next iOS versions 3.4.6
Regression test on going on https://github.com/owncloud/ios/tree/release_3.4.6
