### ISSUE TITLE
Number inside the red bubble is not correct

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#438]
STEPS TO REPRODUCE IT
    1. Select to upload two images
    2. once they are uploaded, select to upload them again

CURRENT BEHAVIOR
        1 is shown in the red bubble

EXPECTED BEHAVIOR
        2 is shown in the red bubble

DEVICE
        ipad v.9

**Comment by rperezb** [comment]
Not reproduable, needed to be checked again

**Comment by purigarcia** [comment]
I checked and I could not reproduce it either.
