### ISSUE TITLE
Owncloud project not running on my iPhone with iOS 7.1

### ISSUE THREAD

**Issue by harithahdasan** [owncloud/ios#444]
Hi..
While running the owncloud project on iOS 7 device I am getting many errors.One among them is "architecture not supported".I would like to know unto which iOS Version is own cloud compatible?

**Comment by harithahdasan** [comment]
Hi...Please someone give me an answer..

**Comment by ggdiez** [comment]
Hello @harithahdasan 

The project support iOS from 7.0 version so that should not be the problem.  

What Xcode version are you use?
Are you trying to launch the project on simulator or on real device?


![captura de pantalla 2015-08-14 a las 9 09 20](https://cloud.githubusercontent.com/assets/2051473/9268929/3cdee4cc-4264-11e5-8ff2-9fa312a2664a.png)

**Comment by harithahdasan** [comment]
@ggdiez :Hii..I am running the project on device...I am attaching the screenshot of the errors that I am getting
![screen shot 2015-08-14 at 1 07 29 pm](https://cloud.githubusercontent.com/assets/13059550/9269275/a5a3d028-4285-11e5-9b62-d816be0a1621.png)

**Comment by harithahdasan** [comment]
@ggdiez :And I am using Xcode 6..

**Comment by harithahdasan** [comment]
@ggdiez :Hi I am attaching the screenshot of another error..Please do check it...
![screen shot 2015-08-14 at 2 02 10 pm](https://cloud.githubusercontent.com/assets/13059550/9270172/2515f2ee-428d-11e5-863e-cbc6beda9ac0.png)

**Comment by ggdiez** [comment]
Hi @harithahdasan 

The three targets of the extensions are for document provider, document picker and  share in, these three extensions only works since iOS 8. The extensions does not exist until iOS 8.

You have to change the developer_target value to iOS 8 in these three extensions.

**Comment by harithahdasan** [comment]
developer_target??What is that?Is that Deployment target?.

**Comment by harithahdasan** [comment]
I changed the deployment target of those extensions to iOS 8.0..then still I am getting error on running in iOS 7 device...That error will come na coz now deployment target is iOS 8....Then is it possible to run it in devices with os versions prior to iOS 8.

**Comment by ggdiez** [comment]
Yes, the target "Owncloud iOS Client" should be work in iOS 7, the others not. 

Other question, I see some iOS library errors in your screen, Have you initialized the git submodule after clone the git project? 
For do that you have to enter in the console: 
git submodule init
git submodule update

**Comment by nasli** [comment]
If is still an issue, please reopen it.
