### ISSUE TITLE
Owncloud CALdav won't work for Iphone 6.

### ISSUE THREAD

**Issue by awkristensen** [owncloud/ios#448]
Just got a couple of new iphone 6s. Iv'e synched my caldav settings from my iphone 5 to the new 6, but it fails to connect to our owncloud caldav server. 

Iv'e tried resetting again following your guide, but this was futile. 

Port 80, no SSL and server: evozourcing.dk/remote.php/caldav/principals/evozourcing

I have also tried to caldav link used for desktops, but without succes.

**Comment by tflidd** [comment]
This seems not to be related to the oc-client itself. You should consider reporting such errors to the calendar-app: https://github.com/owncloud/calendar/issues

**Comment by enoch85** [comment]
@awkristensen I just tried to configure it on a brand new iPhone 6 and it works. It must be something with your settings that doesn´t add up.

I´m closing this, and if the error persists, please report it in the calendar app as @tflidd said. Thank you.
