### ISSUE TITLE
iOS Folder column width

### ISSUE THREAD

**Issue by uber-poutine** [owncloud/ios#451]
In the ownCloud iOS app, the folder column abbreviates the titles of the folders (as shown in the enclosed image). 

I was wondering if it would be possible to modify the column to be of an adjustable width, or to not abbreviate the folder titles and make it possible for them to scroll horizontally inside of the pane?

![ios owncloud issues](https://cloud.githubusercontent.com/assets/2460454/9499644/da12cae2-4bdd-11e5-9426-84c570ae6695.png)

**Comment by ggdiez** [comment]
Hello @uber-poutine 

I close this issue, we are talking about that here #129
