### ISSUE TITLE
Use new filetype icons

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#456]
From core master: https://github.com/owncloud/core/tree/master/core/img/filetypes

Preview:
![filetype icons new](https://cloud.githubusercontent.com/assets/925062/9544685/f5bf92e2-4d82-11e5-85cf-96d333c73eb6.png)

They are 16*16px but of course scale them up. Please only in multiples of 16px, for example 48px.

This should be done in sync with the release of 8.2 server. cc @rperezb @MTRichards @ggdiez @javiergonzper

**Comment by jancborchardt** [comment]
Same for Android: https://github.com/owncloud/android/issues/1118

**Comment by jancborchardt** [comment]
cc @tobiasKaminsky @AndyScherzinger @Stoyicker @Kernald too :)

**Comment by javiergonzper** [comment]
Nice icons! Sure we have to include them into the mobile apps

**Comment by javiergonzper** [comment]
@jancborchardt looks much better now! :smile: 

![screen shot 2015-09-04 at 14 01 54](https://cloud.githubusercontent.com/assets/1815050/9683295/01152da0-530f-11e5-9821-6d45d251c219.png)

**Comment by jancborchardt** [comment]
WOW, nice! :) A detail: The icons should move a bit more to the right, towards the text. Maybe centered between the left edge and the text.

**Comment by javiergonzper** [comment]
It is in the center because you have to take into account also the Favorite icons and the Download icons

![screen shot 2015-09-04 at 14 20 27](https://cloud.githubusercontent.com/assets/1815050/9683401/263136b4-5310-11e5-87d8-22818dfc7b77.png)

**Comment by karlitschek** [comment]
It really looks nice. Thanks guys. One think that always bothered me is that the icons on the bottom (Files, Upload, Share link,..) look a bit cramped. It would be cool to have a tiny bit of additional space at the bottom and top of the toolbar.
What do you think?

**Comment by joeplus** [comment]
I agree! Additionally, would it make more sense to have the "favourite" and "donwload" ovrlay also all the way on the top right where currently the "share" icon is over the file name? I think it would be cleaner and the filetype icons could move in towards the right.

Should the icon for "Files" on the bottom also be changed to the new icon for "Folder"? To me they look a little outdated and just not in line with the great new icons for the filetypes.

**Comment by jancborchardt** [comment]
@karlitschek @joeplus those are different topics, would be good to open separate issues for them. ;)

@javiergonzper I know, but it’s fine if the download and fav icons overlay the filetype icons a bit. It’s more important that the default layout looks fine. So please move the filetype icons a bit to the right.

**Comment by karlitschek** [comment]
@jancborchardt agreed. I tried to sneak this in here :-)

**Comment by karlitschek** [comment]
https://github.com/owncloud/ios/issues/469

**Comment by joeplus** [comment]
#470

**Comment by javiergonzper** [comment]
@jancborchardt I will close this issue and we can continue searching a solution on the https://github.com/owncloud/ios/issues/470 because this issue was just to update the icons with the new ones not to change the design of the Cell
