### ISSUE TITLE
Sync Folder in iOS

### ISSUE THREAD

**Issue by MTRichards** [owncloud/ios#463]
As an ownCloud user, I want to be able to sync a folder from my iOS mobile device to the server so that I can access and edit files easily across devices without thinking about it

Acceptance Criteria:
- The current Favorites star is to be renamed Sync
- The Sync star icon is to be replaced with a circular static sync icon (see  bad example here)
![sync](https://cloud.githubusercontent.com/assets/1818977/9688886/0859c8b4-5300-11e5-927e-348ee1f818eb.png)

- Sync icon is to be the same color as the star and found in the same location on the iOS device (yellow)
- Sync icon will automatically replace existing favorite directories on files currently set as favorites
- Sync for iOS can only occur when the app is open, as there is no service mechanism for initiating sync in the background. As a result, every time the app is opened, the local cache is refreshed, and any new files are synced with the server.
- Once the app is opened, sync of individual directories happens when the user navigates into the directory
- When a user is browsing files and pulls down to refresh the directory, any files and folders in that directory are synced automatically (including folder children).
- When a directory is syncing, if the app is blocked, a circular icon shows that the app is working on the sync

**Comment by rperezb** [comment]
@MTRichards I missed how to call the action: currently we have: Favorite and Unfavorite

Now, it would be: Sync and Unsync ?

**Comment by rperezb** [comment]
For tracking purposes this one is aligned with: https://github.com/owncloud/android/issues/1136

**Comment by MTRichards** [comment]
"Sync" and "Don't Sync".

**Comment by nasli** [comment]
Now sync folders called: Available offline.
Closed via: https://github.com/owncloud/ios/issues/665
