### ISSUE TITLE
spacing in toolbar buttons

### ISSUE THREAD

**Issue by karlitschek** [owncloud/ios#469]
One think that always bothered me is that the icons on the bottom (Files, Upload, Share link,..) look a bit cramped. It would be cool to have a tiny bit of additional space at the bottom and top of the toolbar.
What do you think?
@jancborchardt

**Comment by jancborchardt** [comment]
Yep, totally agree. If necessary we should even make the icons smaller (just in case the bottom bar gets too tall if we introduce proper whitespace).

**Comment by joeplus** [comment]
I agree! Additionally, would it make more sense to have the "favourite" and "donwload" ovrlay also all the way on the top right where currently the "share" icon is over the file name? I think it would be cleaner and the filetype icons could move in towards the right.

Should the icon for "Files" on the bottom also be changed to the new icon for "File"? To me they look a little outdated and just not in line with the great new icons for the filetypes.

**Comment by nasli** [comment]
We can reduce the size of the icons. 
The minimum size according to Apple guidelines for a tabbar icon:
@1x : about 25 x 25 (max: 48 x 32)
@2x : about 50 x 50 (max: 96 x 64)
@3x : about 75 x 75 (max: 144 x 96)
Look at the share icon in the following image, what do you think @karlitschek, @jancborchardt ?
![smallicons](https://cloud.githubusercontent.com/assets/6570505/9760398/ff7bc122-56f4-11e5-8b95-ff92b0005632.png)

**Comment by karlitschek** [comment]
i think the tiny bit more space on the top makes it better. what do you think @jancborchardt?

**Comment by jancborchardt** [comment]
Looks much better already :+1:

**Comment by nasli** [comment]
Will be within the next version 3.4.5
