### ISSUE TITLE
Bring overlay icons in line with share icon in file list

### ISSUE THREAD

**Issue by joeplus** [owncloud/ios#470]
Hi all, just an idea: Would it make more sense to have the "favourite" and "download" overlay also all the way on the top right where currently the "share" icon is over the file name? I think it would be cleaner and the filetype icons could move in towards the right.
![263136b4-5310-11e5-87d8-22818dfc7b77](https://cloud.githubusercontent.com/assets/7793652/9714352/51e60c58-554f-11e5-9e41-98b7c9919e96.png)

**Comment by javiergonzper** [comment]
@joeplus  I like it a lot! @jancborchardt what do you thing about do this and at the same time center the icons?

**Comment by jancborchardt** [comment]
I’m not really sure it’s good. The share icon is to the right so one can immediately discern shared from non-shared items. The other icons are not that critical though, and when we add everything to the right it just becomes a colorful bar of »find the tags for that file«. ;)

Also the biggest drawback of having it on the right is that it’s as far away from the filename as possible, meaning you need to move your eyes a lot to find out which file the attribute actually is about.

**Comment by joeplus** [comment]
I agree with the having to look all the way to the right to determine the different tags but right now you have to look in two different places.
Maybe there is a middle ground in positioning the overlays more towards to filetype icon like it is on Android?

![Android](https://cloud.githubusercontent.com/assets/1315170/9716941/bbcf7fb8-556e-11e5-9dcd-a2f62ac5ef29.png)

**Comment by jancborchardt** [comment]
Well – as said in https://github.com/owncloud/ios/issues/456#issuecomment-137719909

> A detail: The icons should move a bit more to the right, towards the text. Centered between the left edge and the text.

@javiergonzper ;)

**Comment by rperezb** [comment]
Let's track this feature on https://github.com/owncloud/ios/issues/456
thx
