### ISSUE TITLE
Duplicate folders in IOS app

### ISSUE THREAD

**Issue by Rivas-Z** [owncloud/ios#472]
Owncloud 7 Enterprise (7.0.4)

Owncloud in use for 8/9 months, the IOS app shows duplicate folders.
If we log on using the browser, folder exists only once.
Opening one of te duplicate folders, sometimes opens the folder but sometimes does nothing...

Anyone else having this problem?
The logging doesn't show anything useful..
Will try to get a screenshot from the concerning users.

Regards Mark

**Comment by ggdiez** [comment]
Hello @Rivas-Z 

Can you say me the specific steps to reproduce it?
What is the version of the iOS app?
What is your iOS device and IOS system are you using?

**Comment by Rivas-Z** [comment]
Hi ggdiez,

The users did reinstall the app, that did the trick.
Perhaps it reappears, but they had the latest version of the app.
Also version IOS version 8.4.1.

Thanks anyway!
Regards Mark
