### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by aplicret** [owncloud/ios#473]
I am getting this error while compiling iOS version of owncloud. My Xcode version is 6.1. Can you please tell me why I am getting this error and how to solve this issue? "Swift Compiler Error Expected type after 'as'.
![screen shot 2015-09-08 at 9 58 03 am](https://cloud.githubusercontent.com/assets/3398827/9726307/42012e5c-5613-11e5-8ebc-e7df8663bdba.png)

**Comment by ggdiez** [comment]
Hello @aplicret 

Swift is changing constantly. In each version of Xcode Swift change and we have to change the code to compile it. 

Right now with develop branch we are using Xcode 6.4, try this.

**Comment by rperezb** [comment]
If using Xcode 6.4 didn't work, please reopen

**Comment by gotaholen1** [comment]
agree, that xcode 6.4 does not compile.

**Comment by aplicret** [comment]
Now I am using Xcode 6.1 and app ios-version_3.4.2_signed, ios-library-oc-ios-library-1.1.2. It runs fine but there are some major issues. I have opened another issue https://github.com/owncloud/ios/issues/477

**Comment by javiergonzper** [comment]
Because Swift is getting updates in every update not all the branches compile with the same version.
develop compile with 6.4 right no but in a few days will works with 7.0 GM.
