### ISSUE TITLE
There is no link for a new user to register for an owncloud account in Login Page.

### ISSUE THREAD

**Issue by harithahdasan** [owncloud/ios#474]

**Comment by harithahdasan** [comment]
When a new user downloads this app from the App Store  how he will get the login credentials.I saw a button in Android Own cloud app which redirects to a website which gives them the details.In iOs what user should do?

**Comment by harithahdasan** [comment]
I am attatching my login page screenshot below
![screen shot 2015-09-08 at 1 53 49 pm](https://cloud.githubusercontent.com/assets/13059550/9729987/25769a9c-5631-11e5-811b-95cfb6611ad7.png)

**Comment by ggdiez** [comment]
Hello @harithahdasan 

Apple does not allow us to include this link in the iOs app. I suppose that using the link the user can see the subscription page and Apple does not like.

**Comment by rperezb** [comment]
There is nothing we may do here, we included this link in the past but we had to remove it.

**Comment by harithahdasan** [comment]
ok
