### ISSUE TITLE
iOS app 3.4.4 cannot connect to subdomain mapped to domain

### ISSUE THREAD

**Issue by r-r-liu** [owncloud/ios#483]
Hi,

The iOS app ver. 3.4.4 is installed on an iPhone 4s and an iPad 3, both running iOS 9.0.1.  I try to add a new account  giving as the server address "http://owncloud.pueo-owl.ch" and receive the message, "Server not found".  If I enter the same address into a browser, the host of my domain "pueo-owl.ch", hosteurope.ch, maps it to http://pueo-owl.owncube.com and an ownCloud login screen appears.  "owncloud" is a subdomain of "pueo-owl.ch" that maps to the subdomain "pueo-owl" of "owncube.com".

This would seem to be a bug, no?

Thanks.

**Comment by rperezb** [comment]
@r-r-liu i close this one, we have talked about it through the apps@owncloud.com mail
