### ISSUE TITLE
File share problem

### ISSUE THREAD

**Issue by aplicret** [owncloud/ios#485]
When I open an image and click on the share icon, it asks for a password (the message is- "To share the link you must enter a password to protect it."). After entering any password it shows a message "You don't have permission to complete the operation.". Can you please tell me what is the purpose of share, how does it work, and why it is not working?

**Comment by rperezb** [comment]
hey,
Thanks for contacting us.

Can you please check on your sever whether the sharing api is enable?

![screen shot 2015-10-01 at 9 34 47](https://cloud.githubusercontent.com/assets/1846927/10215202/afba5856-681f-11e5-97e2-db2f310a4ffd.png)

**Comment by rperezb** [comment]
Close for inactivity, if needed, please reopen
