### ISSUE TITLE
ownCloud mobile Text Editor

### ISSUE THREAD

**Issue by CWRoux** [owncloud/ios#486]
How about a simple text editor in ownCloud mobile? It will save the effort to open everything with another app and then check it back into ownCloud. And a text editor is useful for making notes while visiting a client.

**Comment by rperezb** [comment]
Thanks for your suggestion!
This feature is the backlog for possible inclusion in future versions of the app.

**Comment by nasli** [comment]
This feature is on going and will be within next releases

![simulator screen shot 11 may 2016 09 34 11](https://cloud.githubusercontent.com/assets/6570505/15173320/be0d7b2c-175b-11e6-9655-f41374272e10.png)
