### ISSUE TITLE
iOS 9.02 OC 3.4.4 bug on iPad

### ISSUE THREAD

**Issue by Froster** [owncloud/ios#487]
There is a bug with OC 3.4.4 on iOS 9.02 using on iPads. If you open a file by touching on it to close folder pane and zoom you can't close this view any more and return to normal view.

Only way will be to close the app and start it again to see the folders/files again.

**Comment by rperezb** [comment]
Thanks for contacting us.

We have just released the version 3.4.5, can you please check in this version?

Thanks

**Comment by Froster** [comment]
Christian Bremm schrieb am 02.10.2015 11:31
_____________________________________________________________________

Hi,

in 3.4.5 the problem is solved ☺ .

But know Fullscreen doesn’t work on ipad.

Freundliche Grüße
SIEGENIA GRUPPE
Geschäftsbereich Management & Support
i. A.
Christian Bremm
EDV / SAP-CC / BC

Tel.: +49 6503 917-303
Fax: +49 6503 917-190
E-Mail: christian.bremm@siegenia.com<mailto:christian.bremm@siegenia.com>
Internet: http://www.siegenia.com

Von: Raquel Pérez Bartolomé [mailto:notifications@github.com]
Gesendet: Freitag, 2. Oktober 2015 09:30
An: owncloud/ios
Cc: Bremm, Christian MDV-H
Betreff: Re: [ios] iOS 9.02 OC 3.4.4 bug on iPad (#487)


Thanks for contacting us.

We have just released the version 3.4.5, can you please check in this version?

Thanks

—
Reply to this email directly or view it on GitHub<https://github.com/owncloud/ios/issues/487#issuecomment-144942967>.
We like trees. Print me only if you need me. Thank you.

_________________________________
SIEGENIA-AUBI KG, Industriestraße 1 - 3, D-57234 Wilnsdorf-Niederdielfen
Kommanditgesellschaft, persönlich haftender Gesellschafter: Wieland Frank, Sitz der Gesellschaft: Wilnsdorf,
Registergericht: Amtsgericht Siegen, HRA 3741

Der Inhalt dieser E-Mail und etwaige Anhänge sind vertraulich und können urheber-, patent- oder in anderer Weise
rechtlich geschützt sein; sie sind deshalb ausschließlich für den bezeichneten Adressaten bestimmt. Sollten Sie nicht
der bezeichnete Adressat dieser E-Mail oder dessen Vertreter sein, so beachten Sie bitte, dass jede Form der
Kenntnisnahme, Veröffentlichung, Vervielfältigung, Weitergabe oder Nutzung des Inhalts dieser E-Mail oder der
Anhänge unzulässig ist. Wir bitten Sie, sich in diesem Fall mit dem Absender der E-Mail in Verbindung zu setzen und
jegliche Originale und Kopien der E-Mail und der Anhänge zu vernichten. Wir weisen ausdrücklich darauf hin, dass die
E-Mail-Kommunikation über das Internet unsicher ist, weil unberechtigte Dritte grundsätzlich die Möglichkeit der
Kenntnisnahme und Manipulation haben.

**Comment by rperezb** [comment]
@Froster yes, due to iOS9 changes, we had to block full screen mode.
The plan is to fix it within next version, there is an open issue on https://github.com/owncloud/ios/issues/436
Let's follow its status there
