### ISSUE TITLE
Uploading photos from IOS to ownCloud <only> into the oC user root folder

### ISSUE THREAD

**Issue by mmattel** [owncloud/ios#488]
I have identified following bug:

owncloud 8.2 beta1 (git), using files external with SMB, no encryption
iPad2, IOS8.4.1 oC App 3.4.4, WLAN connection in the same network

When I want to upload a photo from the iPad photo app, I can do this problem free if I chose the default root folder (owncloud), but if I select another folder either local or mounted, it does not upload.

Picture size 5.7 MB

The problem is, that on non root folders, the oC App waits for a server connection ??

location | folder | status
-----------| --------- | -------
local | root | immediate
local | folder_name | no upload (1)
mount | root | no upload (1)
mount | folder_name | no upload (1)

(1) The oC App tells me that even I was able to chose the folder in the mount, it waits for the connection to the owncloud server

Additional note: when selecting the target folder in the oC App where the picture should be uploaded to, I always get and only there when chosing a mount (not local), a message that the connection to the server is not possible. With the second try, it is selectable.

The bad thing is, you do not recognize this up to th point you go into the oC App and to Uploads and see what is going on. You think that things are uploaded, but they arn´t.

**Comment by mmattel** [comment]
#386 (Improve Sharing data between iOS apps and OwnCloud app)

@nasli Referencing the above issue because I see room for improvements.

eg, the suggestion for the german translation text is easy to implement.
The oC App upload window would have been a big help identifying the issue and see if data has been uploaded or not, the selection of the account when having multiple accounts ect

**Comment by nasli** [comment]
@mmattel, Thanks for the information, we taking it into account for the new stable version 8.2. 

We doesn't give support to beta server version until they are in stable version. We have tested this bug over today master branch and iOS App 3.4.4 and works fine in all folders and SMB. 

The share in option, when you send the files to upload, they remain in the queue of uploads until you open the app, then they start to upload.

**Comment by mmattel** [comment]
Interesting...
Would be great if you consider to have the upload window opened after selecting the owncloud target folder, because this is very strange from a user experience point of view...

I have a prod environment running too and I will do a test and give you feedback.
