### ISSUE TITLE
PIN switch is flickering when switching accounts

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#489]
### Expected behaviour

PIN switch shouldn't flicker when switching accounts
### Actual behaviour

PIN switch is flickering when switching accounts

![pin-flickering](https://cloud.githubusercontent.com/assets/214010/10248374/6b2e6730-691f-11e5-835a-81fe25ec718c.gif)
### Steps to reproduce
1. Open settings screen
2. Configure 2nd account
3. Switch accounts
### Environment data

iOS version:
9.0.2

Device model: 
iPhone 6

ownCloud app version:
3.4.5

ownCloud server version:
8.0.x

**Comment by rperezb** [comment]
Thanks for the report, we will take this into accont for future versions of the app.

**Comment by michaelstingl** [comment]
no longer relevant with [new ownCloud iOS App](https://github.com/owncloud/ios-app) in the making
