### ISSUE TITLE
[3.4.5] Audio player controls missing at previously played/downloaded audio files

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#497]
### Expected behaviour
The iOS app should display audio player controls for previously played/downloaded audio files

### Actual behaviour

<img width="1334" alt="movie_recording_5" src="https://cloud.githubusercontent.com/assets/214010/10616993/4ca40cd2-7768-11e5-8c00-b3976a767385.png">

### Steps to reproduce
1. Tap audio file in portrait orientation => regular audio player controls
2. Tap "< Back" button => file has "downloaded" indicator
3. Tap same audio file again => audio player controls are gone
4. Rotate device to landscape orientation => audio player controls are still gone and layout is broken
5. Rotate device back to portrait orientation => audio player controls are still gone and layout is fully broken

### Environment data
iOS version:
9.0.2

Device model:
iPhone 6

ownCloud app version:
3.4.5

@rperezb

00003946

**Comment by rperezb** [comment]
@michaelstingl yes, this has been reported on: https://github.com/owncloud/ios/issues/426
@ggdiez is currently checking it

**Comment by michaelstingl** [comment]
**Workaround:**
Using the controls from the iOS Control Center or delete the local copy of the file, then play (and download) again.

**Comment by rperezb** [comment]
Working on https://github.com/owncloud/ios/tree/media_player_screen_size

**Comment by rperezb** [comment]
tested and working fine!
pending pr cc @ggdiez

**Comment by rperezb** [comment]
Closed via https://github.com/owncloud/ios/pull/503
