### ISSUE TITLE
Server data lost every now and then...

### ISSUE THREAD

**Issue by pequesan** [owncloud/ios#506]
Hi all,

I've just installed owncloud 8.2 at home with no much issues. Windows and Android clients are working just right, but I can't get IOS app work as expected in a new Iphone 6s with last IOS available.

I start the app, enter my server settings (http, no https at the moment) successfully, and configure instant upload. This works for some hours, but suddenly, when I reenter the app it asks again for server settings. The thing is that if I reenter them, and go to config, I can see my server twice, so config is not lost, but every now and then app stops working (so no instant upload).

I've seen a report in the forum two months ago, but nothing else...

Is my fault? Should I test https maybe?

Thanks a lot.

**Comment by farmio** [comment]
Same problem here with https and without instant upload activated. After some days i have to reenter account-credentials. They appear as duplicates in the settings tab then.

**Comment by pequesan** [comment]
Good. I'm not alone... but obviously this is not a bug that affects everyone, because then the app is almost useless... ¿?

I've tested https and no instant upload, same thing.

bye!

**Comment by rperezb** [comment]
Thanks for contacting us.

yes, we are aware of this issue as my colleague @ggdiez explained https://github.com/owncloud/ios/issues/344#issuecomment-135344177 it´s related to the access to the keychain. 

For the moment, when this happens the workaround is to kill the app and open it again. Certainly, we plan to work on fixing this after finishing the favorite folder feature (on going), we expected it to be fixed within iOS9. 

Let's track its status on #344

**Comment by pequesan** [comment]
Ok. Thanks a lot.
