### ISSUE TITLE
Upload problem from Safari: OwnCloud "Doesn't support file type"

### ISSUE THREAD

**Issue by Vitcho** [owncloud/ios#508]
Hello

My organisation is considering OwnCloud but I am having trouble uploading from OwnCloud. It is represented on the list, but it is not usable as a source because it "Doesn't support file type" (see picture). Is this a problem with the app or the website. I hoped for the latter and have tried many different sites but it is the same everywhere. Even ownclouds own demo page fails to activate the option when you try to upload a file as you can see. 

Can anyone here explain this behaviour? :-)

![2015-11-03 12 07 42](https://cloud.githubusercontent.com/assets/15629413/10906928/e6ae8150-8225-11e5-8571-ac1be6cec228.png)

**Comment by nasli** [comment]
Hello @VicDeo, thanks for contacting us. 

Since iOS9 Apple allows to upload more type of files than photos from Safari. Currently we do not support but we will taking into account for future versions.

If you try to use ownCloud as a source from other app, the ownCloud app is available as a manage locations.

**Comment by VicDeo** [comment]
@nasli I have no  devices running iOs ;)

**Comment by Vitcho** [comment]
Hello @nasli - thanks for the answer. It gets weird now, though. Because I tried it on gmail.com and there it is actually possible to use ownCloud to upload. I am confused.

![2015-11-03 17 13 52](https://cloud.githubusercontent.com/assets/15629413/10913489/70c734ae-824e-11e5-9b36-d3b1950c279f.png)

**Comment by nasli** [comment]
Sorry @VicDeo I mistook your name :)

@Vitcho, in the document picker extension are configurable the supported file types, currently we are using a generic UTI, and we need to add other UTIs more specific

Whitin next iOS OC app version you will be able to use ownCloud as a source also in ownCloud website ;)
