### ISSUE TITLE
Default typefaces on app on iOS 9

### ISSUE THREAD

**Issue by raghunayyar** [owncloud/ios#509]
Ideally, the iOS App should be using the default iOS typefaces if not the ownCloud's own. Then why not to display San Francisco on iOS 9 and similar system defaults on previous versions? cc @jancborchardt @owncloud/designers

**Comment by jancborchardt** [comment]
This is related to the Android issue https://github.com/owncloud/android/issues/1132

@ggdiez @javiergonzper can you show screenshots with the iOS app with San Francisco, as well as with Open Sans so we can see how it looks?

**Comment by javiergonzper** [comment]
The typeface are not centralice as a constant so right now it is impossible change it fast just to check how it looks like... we need put everything in common first.

**Comment by jancborchardt** [comment]
Yeah, so that’d certainly be an important first step.

**Comment by javiergonzper** [comment]
Sure :+1:
