### ISSUE TITLE
[3.4.5] [Transifex] [nl] First letter of menu item "verplaatsen" (Move) should be capitalized

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#510]
All menu items begin with upper-case character, but "verplaatsen" (Move) starts with lower-case character.

![image005 2](https://cloud.githubusercontent.com/assets/214010/10925864/24a50292-8292-11e5-8184-7f2dc8920bd4.jpg)

This could be easily fixed in Transifex, but I haven't got permissions to help with the Dutch translation yet:

![owncloud___transifex_editor_and_downloads_and_os_x_10_11](https://cloud.githubusercontent.com/assets/214010/10925895/6e7c9df8-8292-11e5-9b56-df08a26e9bd6.png)

https://www.transifex.com/owncloud_robot/owncloud/viewstrings/#nl/mobile-ios/38858491?qt=verplaatsen

@MorrisJobke Who can help here? /cc @DeepDiver1975 @rperezb 

Please also see my suggestions for using hints about the context of a string in Transifex in https://github.com/owncloud/client/issues/3519#issuecomment-126695367 .

00004083

**Comment by MorrisJobke** [comment]
@rullzer @Xenopathic @jospoortvliet Is one of you in the dutch transfix team and fix this quickly
?

**Comment by MorrisJobke** [comment]
> @rullzer @Xenopathic @jospoortvliet Is one of you in the dutch transfix team and fix this quickly?

cc @icewind1991 too

**Comment by rperezb** [comment]
@davivel have you changed this? thx

**Comment by davivel** [comment]
@rperezb , done.

**Comment by rperezb** [comment]
thanks! 

For tracking purposes, this is related to: https://github.com/owncloud/android/issues/1245

**Comment by Xenopathic** [comment]
@MorrisJobke As much as I'd like to help, I don't actually speak Dutch at all :smile:

**Comment by MorrisJobke** [comment]
> @MorrisJobke As much as I'd like to help, I don't actually speak Dutch at all

I don't really have any clue why I mentioned you :confused:

**Comment by rperezb** [comment]
fixed https://github.com/owncloud/ios/blob/2025cb28526505cfd308075b6dbd146247da383a/Owncloud%20iOs%20Client/SupportingFiles/Languages/nl.lproj/Localizable.strings#L206
