### ISSUE TITLE
File is Missing OCShareUser.h 

### ISSUE THREAD

**Issue by matt60400** [owncloud/ios#513]
Hello,

I downloaded the last version of own cloud iOS apps and when compile it , he says "OCShareUser.h" is missing.

Can you help me please?

**Comment by matt60400** [comment]
in package iOS-develop

**Comment by nasli** [comment]
Hello @matt60400, 
seems you need to init the OClibray, how you cloned the project? did you do the following steps?
```
git submodule init
git submodule update
```

**Comment by matt60400** [comment]
Problem solved.

I downloaded iOS-library download full folder library.
