### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by matt60400** [owncloud/ios#516]
How can i change app icon?

**Comment by javiergonzper** [comment]
It is an image... you can change it for you if you want.

**Comment by matt60400** [comment]
Where can i change this app icon?

If i change this app icon in "App icon Source" , the app isn't adaptative with the screen.

**Comment by javiergonzper** [comment]
The icons and splash are here:
ios/Owncloud iOs Client/SupportingFiles/Images/ImageBranding/

**Comment by javiergonzper** [comment]
Open the issue if you need more help
