### ISSUE TITLE
Failed Archive Submission iOS

### ISSUE THREAD

**Issue by Godine** [owncloud/ios#518]
I am working on an iOS owncloud app. Everything is working fine on the emulator and ad hoc; however, when trying to submit to App Store, things get a bit messy. I get those 3 errors:

ERROR ITMS-90363:"Invalid info.plist key. The key 'NSExtensionPointName' in bundle example.app/Plugins/exampleShare.appex is invalid."

ERROR ITMS-90363:"Invalid info.plist key. The key 'NSExtensionPointVersion' in bundle example.app/Plugins/exampleShare.appex is invalid."

ERROR ITMS-90361:"Invalid info.plist value type. The value type for the key 'NSExtensionActivationSupportsText' in bundle example.app/Plugins/exampleShare.appex is not boolean."

This post seem to resolve my first two errors, but I am still Stuck with the third one:

App store submission issue with sharing extension: http://stackoverflow.com/questions/26101806/app-store-submission-issue-with-sharing-extension

What I am thinking about right now is that in the previous versions of my code, this field used to be a boolean and now is an integer and has a value of 3, so how can I change its type to integer or how can I take it back to boolean.

Thank you.

**Comment by hodyroff** [comment]
Is this your own independent iOS app or is it based on GPL licensed code in this repository? If the later, it can't be uploaded to the store without a license violation, see: https://owncloud.org/contribute/iOS-license-exception/

**Comment by Godine** [comment]
Thank you for your reply.

Actually it is based on the code in this repository, but wouldn't it prompt a message about GPL license violation? and I can't figure out the link between what you are stating and the third exception concerning the boolean variable. Can you please clarify?

**Comment by hodyroff** [comment]
Those are two independent items, the license violation would not be easy to trigger I suppose.
So in any case the use case you describe does currently need a license from ownCloud, Inc. please get in touch with sales@owncloud.com to discuss.
Why it doesn't work technically I don't know, but please understand that we aren't able to help in such cases.
