### ISSUE TITLE
Fullscreen mode on iPad missing

### ISSUE THREAD

**Issue by byEkedahl** [owncloud/ios#525]
iPad mini
iOS 9.1
owncloud app 3.4.5

Since the last update the app can't show photos or documents in fullscreen mode. This error only occur on iPad on iPhone 6 it works fine. This is how it looks on the iPad.

![img_0130](https://cloud.githubusercontent.com/assets/15943587/11370093/560d0d94-92c2-11e5-9fa9-04c12af99081.jpg)

**Comment by rperezb** [comment]
Thanks for reporting this.

We have fixed it and it will be released within the next iOS version, 3.4.6, expected at the beginning of Dec
