### ISSUE TITLE
"Accounts" title is displayed behind the top bar

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/ios#532]
On the newest iOS app after reopening it (closing using double pressing on home and swiping to close it) and then going to settings this looks like following:

![photo-2015-12-04-01-55-33_3020](https://cloud.githubusercontent.com/assets/878997/11585748/77a48fbe-9a6e-11e5-8dd5-f9f2cd08ad65.PNG)

**Comment by nasli** [comment]
Hi @LukasReschke, thanks for report
we can not reproduce it here, which device and version are you using?

**Comment by LukasReschke** [comment]
iPhone 5S, 3.4.6 from yesterday.

Do you happen to have two accounts configured as well? Also you did you restart the application?

**Comment by nasli** [comment]
Ok, saw the error, added to backlog, thx!

**Comment by nasli** [comment]
This bug is fixed and will be within next release
