### ISSUE TITLE
Wrong plural spelling

### ISSUE THREAD

**Issue by Commifreak** [owncloud/ios#534]
Just noticed on latest app-version:

Locale/Language: German

1 Monate
2 Monat

is wrong.

should be

1 Monat
2 Monate

Days (Tage) and minutes (Minuten) are working properly.

**Comment by javiergonzper** [comment]
Hello @Commifreak 

You can change and check all the texts on: https://www.transifex.com/owncloud_robot/owncloud/language/de/

You just have to join the team :smile: 

Thanks for your help!

**Comment by rperezb** [comment]
as @javiergonzper said translations are handled from transifex, please update there

**Comment by michaelstingl** [comment]
fixed with https://github.com/owncloud/ios/commit/e9a5e2e3da0b6dbff78417737d46a1b927ad0fd5
