### ISSUE TITLE
Viewing the share link of a shared folder shows "-1"

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/ios#535]
1. Share a folder via Web
2. Go to the iOS app
3. Go to the list of the existing shares
4. Slide to get the sharing link

![photo-2015-12-07-21-16-40_3071](https://cloud.githubusercontent.com/assets/878997/11638575/f25293e4-9d27-11e5-9445-5588894552f1.PNG)

**Comment by nasli** [comment]
Hi @LukasReschke, 
We could not reproduce it here. 
What type of file are you sharing? For the icon seems is a file without extension and not a folder. 
What is the path to this folder?
is the name of the file "byte"?
Which server are you using?
thanks!

**Comment by rperezb** [comment]
Close for inactivity, if needed, please reopen
