### ISSUE TITLE
Position of the file listing has shifted by few pixels

### ISSUE THREAD

**Issue by supportreq** [owncloud/ios#539]
Hi, I did some modifications to the Asset icons to be taken from the Image Asset tool. Due to this it seems that the file listing has left some space from the top.. If I open an image and return back to the file listing the files start from the top position..

any clue??

**Comment by nasli** [comment]
@supportreq could you send us some screenshots of the issue?
Thanks!

**Comment by rperezb** [comment]
Closed for inactivity, please reopen if needed
