### ISSUE TITLE
[Sharing] Preview full name

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#540]
AC:
- Preview the full name of the file/folder within the share view

![image1 3](https://cloud.githubusercontent.com/assets/1846927/11693281/4ba43aec-9ea4-11e5-9901-0d00057604f1.PNG)

Idea:
- It could be used 2 lines instead of 1 to show the name

**Comment by rperezb** [comment]
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
Hm, I think that especially in this case the thumbnail is much much more important than showing more of a filename which is not really telling. ;)

**Comment by rperezb** [comment]
@jancborchardt, yes thumbnails will work for images and videos, however, what about other extensions?

**Comment by nasli** [comment]
Yes, I agree @rperezb, we have plenty of space at the top, we could show the name within a couple of lines

**Comment by jancborchardt** [comment]
Thumbnails have priority over this: https://github.com/owncloud/ios/issues/149 & https://github.com/owncloud/ios/issues/385 ;)

**Comment by nasli** [comment]
No doubt @jancborchardt, and the first part, thumbnails for download images, it is already developed and it is right now under QA process.

**Comment by nasli** [comment]
This issue will be within next release 3.4.7
