### ISSUE TITLE
Federated sharing support in mobile devices

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#543]
Sharing in mobile devices does not support federated sharing with other servers' users.

**Comment by cmonteroluque** [comment]
@MTRichards

**Comment by MTRichards** [comment]
At this time, it is a matter of the sharing API being able to reach beyond the current server to other servers.

This means really this is a server side challenge, captured here:
https://github.com/owncloud/core/issues/21328

@rperezb something for the backlog for when server side is completed, so we can check.

**Comment by MTRichards** [comment]
I stand corrected, looks like we need to handle this entirely on mobile. Closed the server side issue.

**Comment by rperezb** [comment]
- Work in progress: https://github.com/owncloud/ios/tree/federated_sharing
- QA: https://github.com/owncloud/QA/pull/143

**Comment by rperezb** [comment]
https://github.com/owncloud/ios/pull/594
