### ISSUE TITLE
Tabbar overhead the last row at Settings Menu

### ISSUE THREAD

**Issue by caraldel** [owncloud/ios#544]
When I navigate to the settings menu, I can´t access to the last row (Send feedback) because the tabbbar (OCTabBarController) its overhead. I 'fixed' it by adding additional height to footer section (sectionToShowFooter). I don't know if you are aware of this issue.

Thanks.

**Comment by ggdiez** [comment]
Hello @caraldel 

Thanks for the report.
This problem is related with #532, it is theme of edges. It will be resolved in the next release.
