### ISSUE TITLE
Failed uploads, no retry option

### ISSUE THREAD

**Issue by enoch85** [owncloud/ios#545]
On my girlfriends iPhone 6 there are occasionally failed uploads, sometimes because of failed credentials (Why? The credentials are correct - maybe another bug?) and sometimes due to "File Error".

The File Error failure doesn't give the user another try to upload the pictures, and it doesn't say why the upload failed - is it because it's duplicated, lost connection, or something else?

So I would like two things;
- More verbose output of why the upload failed.
- A retry option so that you can manually retry to upload the failed file - and if the file exists then overwrite the old one to be sure that it's uploaded. The overwrite part could be an option.

Linking the Android issue here: https://github.com/owncloud/android/issues/340

**Comment by nasli** [comment]
Hello @enoch85, thanks for reported it. 
Could be related with a keychain issue fixed, we will review it.

**Comment by rperezb** [comment]
Hey @enoch85 thanks for reporting this, it's expected to be fixed within next version: https://github.com/owncloud/ios/pull/560
It it weren't please, reopen the issue

About the retry option, how the app is designed:

- Those uploads that failed due to network/server connection, they are retried automatically
- Those uploads that needs user interaction, they are not retried, such as: permisions error,...login credentials.

In this concrete situation, it was a login credentials error

**Comment by enoch85** [comment]
Thanks for the fix guys!

**Comment by enoch85** [comment]
Failed uploads due to "credentials error" (even if the credentials are correct) still occurs.

**Comment by javiergonzper** [comment]
This could be related with access to the keychain.
@enoch85 I am not sure if we will check it before 3.4.9... maybe the right milestone it is "backlog".

cc: @rperezb

**Comment by rperezb** [comment]
@enoch85 we'd need to know first of all, how to reproduce this error. From our end, it's working just fine.

As @javiergonzper has said, it's better to move it to the backlog, at least, we need to be able to reproduce to fix it.

**Comment by enoch85** [comment]
@rperezb Sorry, I should know better. :)

I just checked the failed uploads a few days ago and saw that the same error as I reported in the first post. Have not been able to reproduce it as I have to travel 500 meters for each photo taken. ;)

**Comment by rperezb** [comment]
@enoch85 there is another trick, kill the app and open it again, it should enforce the instant uploads or switch the device to airplane mode

**Comment by enoch85** [comment]
@rperezb Ok, thanks! Will try when I get some time over, thursday maybe.

**Comment by enoch85** [comment]
Opened a new issue here instead with fresh details: https://github.com/owncloud/ios/issues/622

Haven't seen the credentials error lately.
