### ISSUE TITLE
[Share options] I want to decide whether share with users is shown or not

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#548]
AC:
- Include 2 independent branded options
 + Show share with users: yes/no
 + Show share with link: yes or not 

NOTE:
- this will imply to modify the current one https://github.com/owncloud/ios/blob/develop/Owncloud%20iOs%20Client/Branding/Customization.h#L137

Related to:
- https://github.com/owncloud/client/issues/4325
- owncloud/android#1397

**Comment by supportreq** [comment]
@rperezb @nasli any update for this?

**Comment by rperezb** [comment]
@supportreq Just created the branch to work on it, https://github.com/owncloud/ios/tree/share_with_privileges

**Comment by rperezb** [comment]
done via: https://github.com/owncloud/ios/pull/590
