### ISSUE TITLE
Bottom part of file list and settings cut off by bottom bar

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#554]
Scroll down to the bottom of settings, and the bottom part will be below the bottom action bar. Instead it should of course scroll further up to be fully visible. Same for the file summary at the end of the files list.

**Comment by nasli** [comment]
Hi @jancborchardt,
you mean that the content of the views are behind the tapbar as seen in the screenshot of this issue #532?

**Comment by jancborchardt** [comment]
Yeah, except for me it occurs with the bottom bar instead of the top bar. cc @LukasRescke can you reproduce this?

**Comment by nasli** [comment]
Yes, the problem was in both, on top of the view in the navigation bar and also in the bottom of the view in the tap bar.  
Both are already fixed in the previous sprint and the fix it is already on develop.
The problem will be fixed within next released ;)

**Comment by jancborchardt** [comment]
Thanks!
