### ISSUE TITLE
[PR 515] The connection must be checked twice to enable the "Add" button

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#557]
Related to the PR 51: https://github.com/owncloud/ios/pull/515

When the credentials gaps are populated, the add button is not enabled until the connection is forced to be checked again:

STEPS TO REPRODUCE

1.- Paste or type a URL with form "http://user:password@server:port"
2.- The user and password fields are filled up

ACTUAL BEHAVIOUR

The "Add" button keeps on disabled spite the connection is stablished. A new attempt to stablish enables it.

EXPECTED BEHAVIOUR

When the connection is stablished and user/password fields are filled, the add button gets enabled.

This testings were performed with iPhone v8.4 and iPadAir v9

**Comment by mnutt** [comment]
I believe I have fixed this with https://github.com/mnutt/ios/commit/9c7643dac2cf1b4299a497c68993ee597a3f37f8.

**Comment by jesmrec** [comment]
Nice! i've checked and it works correctly. Thanks!
