### ISSUE TITLE
[PR 515] Protocol prefix in URL not compatible backwards

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#558]
Related to PR 515: https://github.com/owncloud/ios/pull/515

Typing in mobile device the URL connection string without the protocol prefix ("http://") or ("https://"), the connection string becomes malformed and is not accepted.

This is happening also when the URL does not contain the credentials. Until now, if the prefix was omitted, the connection was too stablished (if not malformed). So, in order to keep backwards compatibility, the URL should be validated also without prefix. This behaviour is happening with URLs containing "user:pass", but also with URL with no credentials.

STEPS TO REPRODUCE

1.- Type a URL without "http://" or "https://". For example: "my.server.org:54264"

ACTUAL BEHAVIOUR

The URL is not accepted, a error message is displayed, and in the URL text area appears: "http:54264/" 

EXPECTED BEHAVIOUR

The URL is accepted as usually (protocol is not mandatory)

Tested with: iPhone 6Plus v8.4, iPad Air v9

**Comment by mnutt** [comment]
Ok, I'm fairly sure I have fixed it with https://github.com/mnutt/ios/commit/ad49c82deb0242115543dc8c5fab4b8bb5ea114c. My local test server is actually an http server rather than https, so when I put in `192.168.1.3:8000` it then converts it to `https://192.168.1.3:8000`. I believe this is the correct behavior?

**Comment by jesmrec** [comment]
yes, this behaviour is correct. Although you do not input the "http://" the URL is validated if the port is correct according the protocol.

After your last commit it's working better but if the protocol is http. Inputing "my.server.com:8100" or "user:password@my.server.com:8100" try to validate it as https. If the port is http, the url is not accepted although it is correct. With "https" urls is working correctly. 

It is close to be fine at all :)

**Comment by mnutt** [comment]
@jesmrec thanks for the feedback. I tracked it down to here:

https://github.com/owncloud/ios/blob/develop/Owncloud%20iOs%20Client/Login/Login/LoginViewController.m#L1696-L1699

This seems to say that if `isNeedToCheckAgain` is `true`, then switch to https, even if it wasn't https before. It looks like `isHttps` just never bubbled back up to the UI before. Do you know why it would be doing that?

**Comment by jesmrec** [comment]
I do not really know why. The things is ensure that the last else is reachable. Now i think if the URL has not prefix, this piece of code is never used because `isNeedToCheckAgain` stays as true whatever the value of `isHttps`

**Comment by nasli** [comment]
Hi @jesmrec thanks for your contribution!
 I have cloned your branch here #569 and added some changes in order to fix this bug.

**Comment by mnutt** [comment]
Hi @nasli, unfortunately your branch doesn't seem to work for me, for some reason it fills in the username and password but doesn't actually use them.

I've updated my branch to remove the automatic switch to https, now if you type `my.server.org:54264` and move to the next field it'll switch to `http://my.server.org:54264` and leave username and password blank.

**Comment by nasli** [comment]
@mnutt we can not change that flow. 
First we tried to log as if the server was https and if not possible we tried with http.
Lets @jesmrec check the latest changes over #569 and verify that all works correctly.

**Comment by nasli** [comment]
@mnutt Why does not work for you? what you mean with does not use the credentials? the log button is not enabled? it is trying to login with wrong credentials?

**Comment by mnutt** [comment]
@nasli I couldn't figure out what that code was doing, but that makes sense. I will revert and see if there is another way.

The login button was not enabled for me; I will try to add some logging information to that branch and see if I can figure out why.  I also have some concerns about doing index-based string manipulation on the URL. It looks like it should work, but I would worry about the potential for bugs down the road.

**Comment by jesmrec** [comment]
@mnutt @nasli thanks for your contribution. Now it's working correctly.
