### ISSUE TITLE
iPhone app share on LDAP owncloud server

### ISSUE THREAD

**Issue by volure** [owncloud/ios#564]
We have Ldap setup on our owncloud server, and when adding a share to a user using the iphone app. The GUID is shown for the user instead of the name.

This goes for New and Existing Shares.

**Comment by nasli** [comment]
Hi @volure, within next version 3.4.7, the user will be listed by their display name instead of their username, and if there are some users with the same display name it will be show also their username to differentiate them.

**Comment by scolebrook** [comment]
@nasli By username, do you mean the internal username seen in the database? If so, for an AD backed system that is the objectGUID attribute by default. For this purpose, it's doesn't help to differentiate one Smith, John (displayname) from another. It would be good if the attribute used for this purpose could be brandable as the best one won't be the same for all systems, but a good default maybe to use email address. That will definitely be unique and will at least stand a good chance of being more useful than an string of chars that appears completely random to a human.

**Comment by nasli** [comment]
An example of current behavior:
displayname: Smith, John
username: jsmith
to distinguish between users with same display name:
Smith, John (jsmith)
Smith, John (johnsmith)

but if the users has random chars in their username, yep, we can not distinguish them even with the username

cc: @MTRichards

**Comment by MTRichards** [comment]
I understand the problem. I also think it is a server issue first, because the server can't differentiate either. Once that server work happens, then we would use the API in iOS to resolve the challenge. Of course we do this in steps, first the above, then the more special cases where usernames are different.

@scolebrook any chance you can open an issue in core to talk about this one? This is interesting.

**Comment by sidey79** [comment]
I have exact the same issue as volure on 3.4.7.
I looked at the core issues and it seems that there is something changed.

Are there any updates on the IOS app also?
