### ISSUE TITLE
Share icon hidden after adding picture file

### ISSUE THREAD

**Issue by vrignaie** [owncloud/ios#574]
### Expected behaviour
Click on **+** icon to add new file or directory. Choose picture. Select one or more pictures and click **Charge**.
The picture file is upload on owncloud server. 
Click **Share** icon to share picture.

### Actual behaviour
Click on **+** icon to add new file or directory. Choose picture. Select one or more pictures and click **Charge**.
The picture file is upload on owncloud server.
The share icon is hidden on right corner and when sliding on files or directories.
Nothing can make share icon appear again. Except switch  to new account.

Device model:
Ipad IOS 9.2.1

ownCloud app version:
3.4.6

ownCloud server version:
7.0.12

**Comment by rperezb** [comment]
Thanks for reporting it.

We are not able to reproduce the error, can you please upload a screenshot?

On the other hand, can you please check whether the Sharing api is enable of the server?

**Comment by vrignaie** [comment]
Here's two snaphots
We can reproduce issue on only two Ipad.

![photo-2016-02-11-10-55-16_0075](https://cloud.githubusercontent.com/assets/16944174/12974324/51adc0b6-d0b3-11e5-9d29-637ce47865c8.PNG)
![photo-2016-02-11-10-55-35_0076](https://cloud.githubusercontent.com/assets/16944174/12974327/5444ed90-d0b3-11e5-9a8c-28d1aebebbfa.PNG)

**Comment by rperezb** [comment]
Thanks for the images.

Did you have the chance of checking the Sharing api? is it enable of the server? 

![screen shot 2016-02-11 at 12 28 51](https://cloud.githubusercontent.com/assets/1846927/12975339/1ceb1eac-d0bb-11e5-8d3c-9f4ae46d4c2c.png)

If the sharing api is not enable on the server, the share option is not shown. iOS app checks whether the sharing api status changes when changing account or when opening the app

**Comment by vrignaie** [comment]
Yes apps are allowed to use Share API

![capture d ecran de 2016-02-11 13 55 30](https://cloud.githubusercontent.com/assets/16944174/12976859/294ac5ce-d0c7-11e5-908b-b22131de6bdd.png)

**Comment by rperezb** [comment]
ok, can you please provide to us a test account on your server to check it, please send it to: apps@owncloud.com

**Comment by vrignaie** [comment]
mail sent

**Comment by vrignaie** [comment]
__I have tried to reproduce the error...however, I have not been able. Can you give me further details? such as iPad model and version?_

Ipad air 32Go (MD789NF/B)
Version 9.2.1(13D15)

**Comment by mRoRo** [comment]
@vrignaie . Thanks for your report! We've tried to reproduce it again, but unfortunately we couldn't. As @rperezb commented, the app checks the share API availability when changing account or when opening the app after it's killed, so you should see the icon after any of this actions. Are you getting any server log related to this?

**Comment by vrignaie** [comment]
Thank you for your reply and spending time for testing. 
I realise that the problem is hard to reproduce. Issue was only seen on two differents Ipad.
The process to change account resolve the issue.
I close the issue

Thanks a lot
