### ISSUE TITLE
Filenames are truncated and not discernable on iPad in file list

### ISSUE THREAD

**Issue by MTRichards** [owncloud/ios#575]
As a user, when I look at the owncloud file list and I have lots of files with the same first names, but the last few are different, I can't read or differentiate the filename.

@michaelstingl @jancborchardt @rperezb linked for your convenience.

**Comment by jancborchardt** [comment]
And my reply:

> As mentioned previously, and also what other apps do (afaik), to a certain point we could reduce the text size of the filename if it’s otherwise ellipsized. The minimum size should be that of the date/size line below.

I would not go for making the sidebar resizable just for this case. Also, having 2 lines makes folders with long names unnecessarily more important than others. Reducing the file size will probably alleviate the problem already.

**Comment by rperezb** [comment]
I'd start with the resize of the file name font.

Certainly, I'd avoid resizing the cell size, a little bit weird..

cc @owncloud/ios-developers

**Comment by javiergonzper** [comment]
What do you think? I setted an scale factor of 0.7

![img_0236](https://cloud.githubusercontent.com/assets/1815050/13008813/00ced66c-d199-11e5-8579-fc6c8e3ba9c1.PNG)

**Comment by jancborchardt** [comment]
Nice, very cool! :)

**Comment by rperezb** [comment]
@michaelstingl FYI, this will be included within the next iOS app version

**Comment by rperezb** [comment]
done via: https://github.com/owncloud/ios/pull/591
