### ISSUE TITLE
Getting clients for testing

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/ios#579]
Hellos! I need beta clients for testing & writing up docs for new releases. It would be lovely if I could have new docs completed by the release date :) Not sure how to get pre-releases; is there a daily build somewheres? I don't have a Mac, and don't really want to get bogged down in learning to build them. Thanks!

@rperezb @ggdiez @javiergonzper

**Comment by rperezb** [comment]
@carlaschroder sent an email to ask for info to provide to you the ipa for writing up docs :)

**Comment by carlaschroder** [comment]
Thanks @rperezb
