### ISSUE TITLE
IOS web client requires RC4 cipher, which is insecure

### ISSUE THREAD

**Issue by maxfieb** [owncloud/ios#581]
I am connecting form owncloud IOS version, from an iphone 6, with latest released update.

If i configure my apache with perfect forward security, there are no ciphers available and the client fails to connect. This apache config fails :

SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS

But if i weaken it by adding RC4, it works normally (but i fail ssl labs cipher tests - as RC4 is now considered insecure, and basically broken - RC4-SHA is the least broken RC4) :

SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:RC4-SHA:!aNULL:!MD5:!DSS

The above ciphers are generally ones which are known to not leak entropy. The windows browsers are fine, just the apple SSL API seems to be way begins the times, cipher-wise. Is there a list of the better ciphers that apple platforms support ?

As a IOS software vendor, do you have a choice of different SSL libraries or ciphers ?

**Comment by maxfieb** [comment]
Most browser vendors are universally removing RC4 (http://www.infoworld.com/article/2979527/security/google-mozilla-microsoft-browsers-dump-rc4-encryption.html) by "early 2016", so it wont be much longer before most web servers will start doing that by default. Most security guides already suggest disabling RC4, as it's been demonstrated as being insecure.

**Comment by javiergonzper** [comment]
Hello @maxfieb 

I think that this could be related with the deprecation of NSURLOperation. We have to work in migrate to the NSURLSession that it is the new way to manage the network requests.

**Comment by tflidd** [comment]
I don't know if this is different for iphone6, but on iphone5s (iOS 9.2.1) I can use owncloud without RC4 (and still get a A+ on ssllabs). I use this cipher suite (on apache):
`SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH EDH+aRSA ECDH+AES256 DH+AES256 DH+AES256 !RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS"`

**Comment by maxfieb** [comment]
I tried that cipher list tflidd, it it a good work around, if my server does not provide RC4, then the client can't use it. Your list must include a cipher that iOS can use instead of RC4.

**Comment by guruz** [comment]
The latest release has a new network library, how is the situation now?

**Comment by ofus** [comment]
Is there a way to find out what the TLS requirements are for a certain ownCloud client?

**Comment by tflidd** [comment]
There is a apache-module: https://github.com/ssllabs/sslhaf

**Comment by maxfieb** [comment]
this seems to have gone away for me, at least since upgrades to IOS and maybe to client libraries

**Comment by nasli** [comment]
Thanks for the update @maxfieb !!
