### ISSUE TITLE
Improve sharing: split filename and extension to different fields

### ISSUE THREAD

**Issue by sronline** [owncloud/ios#586]
Sharing data between IOS apps and the OwnCloud app for uploading purposes should be improved:
- It would be better if Filename and extension where splitted to two different field, so that the user does not accidentally remove the file extension

![owncloud_split](https://cloud.githubusercontent.com/assets/17158346/12953347/500c4db6-d01a-11e5-939d-1d16c2d6aeb1.png)

**Comment by sronline** [comment]
#386

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
