### ISSUE TITLE
Cannot click "Send Feedback" link on iphone5s

### ISSUE THREAD

**Issue by jamesfawcett** [owncloud/ios#588]
### Expected behaviour
Unable to click the Send Feedback link on iPhone 5s, it's off the bottom of the screen. Trying to click it clicks the "uploads" button click point.

### Actual behaviour
Unable to click Send Feedback via the IOS latest app

### Environment data

Device model: Apple Iphone 5s

ownCloud app version: Latest

ownCloud server version: Latest

**Comment by rperezb** [comment]
Thanks for your feedback, this will be fixed within the next version.
If it weren't for you, please reopen
