### ISSUE TITLE
Iphone Full after just one day's use

### ISSUE THREAD

**Issue by jamesfawcett** [owncloud/ios#589]
### Expected behaviour
I would like to be able to remove all viewed images, my iphone is only the small capacity, and soon full from viewing images. A "Clear all downloads" or "remove all images from device" would be greatly appreciated.

### Actual behaviour
Phone fills up after just one days use checking camera MJPEG feeds via OwnCloud IOS app.

### Environment data

Device model: Apple Iphone 5s

ownCloud app version: Latest

ownCloud server version: Latest

```

**Comment by rperezb** [comment]
Thanks for your request, this feature is already on the backlog: https://github.com/owncloud/ios/issues/301 lets track there the status.

In the meantime, you may take advantage of removing the downloaded data from a certain folder, for that just select to remove a folder and then select locally
