### ISSUE TITLE
App keeps saying "The user or password is incorrect"

### ISSUE THREAD

**Issue by netanyahusanta** [owncloud/ios#595]
So I'm trying to use the ownCloud Ios app on the most recent develop branch (commit 0be0fb8805eaae48091622b9598a76babaa80220 from Mr.Jenkins) but the issue is that the app keeps asking me to re-enter my username password whenever I'm trying to open a folder (opening a file works but I can't open a folder without getting this error).

`2016-02-22 16:12:21.656 Owncloud iOs Client[367:41967] <0x18407e00 FilesViewController.m:(1778)> error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" `

I'm totally sure that the password is correct since I use the Android version flawlessly, but the iOS keeps giving back an `unauthorized (401)`.

**Comment by edanedison** [comment]
I'm also getting this error. Spent the best part of the day trying to find out what's going on. I'm not sure, but it may be because it expects a secure https connection. Hopefully someone from the dev team can shed some more light on this?

**Comment by nasli** [comment]
Hi @edanedison, we have not noticed here, could you send us a test account to apps@owncloud.com. Thanks!

**Comment by edanedison** [comment]
I will sort this out for you in a little while. Thanks. Just a question though.. should I be able to build and use the IOS app without the need for an ssl connection?

**Comment by nasli** [comment]
@edanedison Yes, you should without any issue.

**Comment by edanedison** [comment]
Ok, I did wonder. Everything seems to be fine with the build except for the keychain error in xcode, which forces the app to continually ask for username and password. This is the output from the log.

2016-03-14 22:04:16.122 Owncloud iOs Client[5962:2309036] <0x100424bd0 OCKeychain.m:(79)> (getCredentials)Error Code -25300
2016-03-14 22:04:16.122 Owncloud iOs Client[5962:2309036] Unable to get the item with id =1 

I've followed the install instructions and they don't mention any additional libraries other than App, FileProvider, and Share sheet. All of the bundle identifiers are correct. Have I missed a step, or is this something you've seen before? I really appreciate your quick responses. Thanks

**Comment by nasli** [comment]
This is a different isssue. It seams that you do not have permission to write on the keychain. Check all your bundle ids and your keychain group. 
The following links could help you:
https://doc.owncloud.com/branded_clients/branded_ios_app/publishing_ios_app_3.html#create-app-group
https://github.com/owncloud/ios/issues/407

**Comment by nasli** [comment]
If need more help you can open a new issue. Thanks!

**Comment by edanedison** [comment]
ok, thanks. I've followed all this already. Your IOS setup instructions seem flawed because they do not address the keychain issue. I've tried these instructions on two different machines now. Out of interest, could you try connecting the app to my hosted solution to see if you can replicate the problem. http://104.155.14.238 username: user, password: mRnbLA2Z  (I will be destroying this instance at some point anyway so don't mind posting the details here for now) thanks.

**Comment by nasli** [comment]
Yes, I can log in without any issue. Check your certificates.

**Comment by edanedison** [comment]
and you could click around without it re-asking for them and kicking you out? If, so that helps narrow down the problem. Thank you.

**Comment by edanedison** [comment]
I can see you made a test folder. I'm unable to do that, so there must be an issue with my build.

**Comment by netanyahusanta** [comment]
@edanedison The problem (as you said) are with the keychains. In the Owncloud documentation not much is mentioned about keychains. What I did in order to resolve the issue is to change the 'keychain sharing' values in infoplist as nasil explained.
