### ISSUE TITLE
owncloud Pictures in the App for iOS don´t in a preview

### ISSUE THREAD

**Issue by Randolph15** [owncloud/ios#596]
owncloud Pictures in the App for iOS don´t in a preview, can you update this or help me? Thanks

.

.
![photo-2016-02-24-08-51-27_2950](https://cloud.githubusercontent.com/assets/17454925/13291241/4b272caa-db17-11e5-9d5b-70ae385d765e.PNG)

**Comment by javiergonzper** [comment]
Do you mean the thumbnail on the left? Will be on the next release in one or two weeks :wink:

**Comment by Randolph15** [comment]
yes, perfect, its very well - Thank you

**Comment by nasli** [comment]
Thumbnails for downloaded images will be within next release, for remote thumbnails let's keep traking here #385
