### ISSUE TITLE
Place downloaded pictures into albums under Photos

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/ios#610]
I know Apple's closed system is a pain but isn't there a way to place downloaded pictures under Apple's Photos app, using albums for the same folder structure?

Make it a bit more convenient for the user. I have tons of images in Owncloud but have to open the Owncloud app every time and to search for them ...

**Comment by nasli** [comment]
@binarykitchen, thanks for your suggestion! 
We keep in mind for a future roadmap, but for now there is not a plan to add that in a near future.
Of course, Contributions are welcome!!

To easily find files there is a plan to add favorites tags on files

**Comment by binarykitchen** [comment]
@nasli i am afraid i can't contribute, no ios coding skills here.

but can you tell me for now if this is possible at all? i mean, wouldn't this break apple's closed system if other apps can place pictures in the native photo app?

**Comment by nasli** [comment]
@binarykitchen Yes, it is possible to create new albums and save new assets on them, indeed right now you can save your ownCloud pictures to the camera roll.
Go to the preview of a pictures, tap on the share button, and select save image
![saveimage](https://cloud.githubusercontent.com/assets/6570505/13945108/125b2daa-f00b-11e5-9dcd-3138ed41d814.png)

**Comment by binarykitchen** [comment]
@nasil thanks for the screenshot but that's not what i am after. basically, i want to sync all photos within all subfolders to iCloud without manually clicking on "save image" for each one. i've got over 2000 photos ...

basically, how can i sync anything on owncloud to icloud? pictures and documents in the same folder structure? that's the big question

**Comment by nasli** [comment]
@binarykitchen, Save a full multimedia folder into the Photos app as a new album using the name of the folder it is possible, but this feature is not on the OC app and there is not plan for it in our current roadmad.

Inside the ownCloud app you can downloaded a full folder, and for future versions will be added multiselect option to do some actions.

Sync a full downloaded folder of Owncloud into iCloud it is not a good idea as Apple Data guidelines suggests, we should store only essential data in iCloud. Bandwidth, network availability, and storage are limited resources and have real, financial consequences for the users, any content possible to be downloaded again should not be store into iCloud.

To understand better your needs, what is your user case? You need to sync your files with other device?

**Comment by binarykitchen** [comment]
The use case is simple: I want all my photos I have on my own ownCloud server to appear on my iPhone's photo app.

I have over 5GB of photos in lots of subfolders on ownCloud and do not want to manually download each one on the iPhone. Just have them all appear in the photo app, automatically. Where the albums are named exactly like the photo foldes on ownCloud.

Probably you do not support this yet or have planned this for a future release?

**Comment by nasli** [comment]
Sorry @binarykitchen, but there is not plan to add that in next releases.

**Comment by binarykitchen** [comment]
@nasli understand and respect that. but tell me, how can i sync tons of photos on my iPhone via owncloud very easily? Is there any trick?

**Comment by nasli** [comment]
To sync full folder of photos into your device:
* inside your ownCloud app:
You can download a full folder into the ownCloud app and keep all the content available offline and in future versions will be possible multiselect option to select more than one folder at same time.

*inside your Photos app:
Actually it is not possible and there is no plan ftm. cc:@rperez
A workaround to do that is to sync them through iTunes: Use ownCloud desktop app, sync your data into your computer and through iTunes select Sync photos and select the folder you want sync.

**Comment by binarykitchen** [comment]
@nasli right, can download one folder. thanks!

yep, that's what i am doing now. owncloud desktop app -> sync -> import into itunes -> import to iphone. works but is very cumbersome and doesn't automatically sync.

**Comment by nasli** [comment]
You are welcome! 
If you want to keep up to date all your files in a folder you can set this folder as favorite. This way all the files inside it will keep sync, downloaded and safe inside your ownCloud app.

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
