### ISSUE TITLE
3.4.8: Upload does not start when shared from Photos App 

### ISSUE THREAD

**Issue by nona00** [owncloud/ios#617]
When sharing an Image from the IOS "Photos" App to the OwnCloud App the upload does not start. You have to manually open the OwnCloud Client.

**Comment by CorneelDragon** [comment]
Same here on 3.4.10, any idea when this will be fixed?

**Comment by jesmrec** [comment]
Duplicated issue

You can track it in https://github.com/owncloud/ios/issues/722
