### ISSUE TITLE
iOS Owncloud app not connecting at all

### ISSUE THREAD

**Issue by DanielMalmgren** [owncloud/ios#620]
The iOS Owncloud app doesn't want to connect to my Owncloud at all any more, no more files are synchronized to the app. When I go into the account settings in the app it just says "Testing Connection" forever. Same thing if I try to add another account, after entering the url it's "Testing Connection" forever. It's the same on two different devices (one iPhone and one iPad). Opening Owncloud in the web browser (Safari) on the same device using the exact same url works fine. Also synchronization using Android app or Windows client works fine, it's just the iOS app that doesn't work.

App version: 3.4.8
Server version: 8.2.3 (Debian 8.3, PHP 5.6.17)

I don't want to put the server url here, but if anyone wants to try you can get it directly from me.

**Comment by nasli** [comment]
@DanielMalmgren, Sorry for the inconvenience, could you send us a test account to apps@owncloud.com?

**Comment by mRoRo** [comment]
@DanielMalmgren. Please send us the iOS version you're using too.

**Comment by DanielMalmgren** [comment]
I haven't got access to the iPhone at the moment, but the iPad is iOS 9.2.1.

You won't need a test account to reproduce the error, just entering the oc url makes the problem appear. I'll send you the url by mail. If you still need a test account, just tell me and I'll set one up.

**Comment by nasli** [comment]
Ok @DanielMalmgren we'll check it and let you known, thank you!!

**Comment by DanielMalmgren** [comment]
Closing this issue since everything seems to work again after uninstalling and reinstalling the app on the affected devices.
