### ISSUE TITLE
iOs Client/ManageTouchID.m is not branded properly.

### ISSUE THREAD

**Issue by gig13** [owncloud/ios#629]
### Expected behaviour
Owncloud iOs Client/ManageTouchID.m in the ios repo is not branded properly. When the little touch id thing appears on screen for you to unlock the app, it says Unlock ownCloud just like line 50 tells it to do. The localizedReason variable on that line should be:
```
[NSString stringWithFormat:@"Unlock %@", [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleDisplayName"]]
```

This will pull the branded app name from the info.plist just like it's pulled everywhere else. So instead of always saying "Unlock ownCloud" it'll say "Unlock Your Branded App". 

### Actual behaviour
The branded app will show "Unlock ownCloud"

### Server configuration
**Web server:** OC8.2.3

**Database:** MySQL

**PHP version:** php5.6

### Client
**iOS version:** latest

**ownCloud app version:** latest

### Tell us what could be improved:

@MorrisJobke @rperezb @michaelstingl

**Comment by rperezb** [comment]
thanks!

This will be fixed within the next version

**Comment by rperezb** [comment]
Done on https://github.com/owncloud/ios/pull/630
