### ISSUE TITLE
How long until Transifex changes occur?

### ISSUE THREAD

**Issue by gig13** [owncloud/ios#631]
### Tell us what could be improved:
How long to verify changes have been made to Transifex after making modifications? When will the ownCloud app be updated?

@MorrisJobke @michaelstingl @rperezb

**Comment by michaelstingl** [comment]
@gig13 The Transifex change should show up in the [commit list](https://github.com/owncloud/ios/commits/master) within 24h. 

The change will be released with the next version of the iOS client. (3.4.9?)

**Comment by gig13** [comment]
@michaelstingl Where is the schedule for 3.4.9 release date?

**Comment by michaelstingl** [comment]
> Where is the schedule for 3.4.9 release date?

@rperezb ^ ?

**Comment by rperezb** [comment]
@gig13 not sure how the changes have been done
I have checked the transifex file: https://github.com/owncloud/ios/blob/master/Owncloud%20iOs%20Client/SupportingFiles/Languages/pt-BR.lproj/Localizable.strings and changes are not there

plus, i have checked the transifex and I have seen any changes on the strings that I'd expect, the disconnect for instance

Can you double check with tthe customer.

About the new version, we plan to send it to the Apple Store in 2 weeks, cc @MTRichards

**Comment by gig13** [comment]
@rperezb @MTRichards So for an ownBrander user, when would these be available? In 3 weeks? -- provided the Transifex changes are made and approved soon (next 5-7 days)?

**Comment by rperezb** [comment]
@gig13 I'd say 4, we have to take into account around a week for Apple to approve it, plus the week extra that we add from where the app is released

**Comment by MorrisJobke** [comment]
@gig13 Are your questions answered? Could this be closed?
