### ISSUE TITLE
Upload limited to 20 photos? Give "upload all" option?

### ISSUE THREAD

**Issue by markley268** [owncloud/ios#642]
### Steps to reproduce

1.select 20 photos from photos app to 'share' and press share button
2.see oc listed
3.add one more photo, and see oc disappear from the list
### Expected behaviour

Tell us what should happen
Oc should be able to handle more than 20 files to be shared/uploaded
### Actual behaviour

Tell us what happens instead
The oc share option disappears
### Server configuration

**Web server:**

**Database:**

**PHP version:**
### Client

**iOS version:**
9.3:2 beta 
**ownCloud app version:**
Latest 
**Device model:**
6plus
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

**Comment by mRoRo** [comment]
@markley268 Thanks for your issue! This is really a planned app behaviour to avoid that too much files have to be managed at once.

**Comment by markley268** [comment]
Then how are people supposed to upload LOTS of photos, or other files?  There's no 'upload all' option in the photo sync, so i'm left with uploading 20 photos at a time, for my 3,000+ photos?

That seems like a deficiency to me somewhere...

**Comment by enoch85** [comment]
I agree with @markley268

**Comment by nasli** [comment]
Of course we can increase this number, but what is the limit will fit your needs? 
Selecting manually 3000 photos is also not worthy. Instead of increase this number should be an option to upload all your photos.

**Comment by nasli** [comment]
Related multiple photo upload #271

**Comment by enoch85** [comment]
@nasli 

>  Instead of increase this number should be an option to upload all your photos. 

Yes please.

**Comment by SkyHK** [comment]
Thank you for making this great app.
If it is able to upload large number of photo, say 1000+ , or upload all, it will be very helpful.
Please consider to implement this feature.

**Comment by tvapait** [comment]
@nasli iOS lets me select all photos on a certain day, I think even if it's 3000.

It's also quite annoying to figure out the limit yourself. I remember that I selected a lot of pictures manually, tapped the share icon, and owncloud didn't show up. Wondering if something was broken. And then having to deselect and select pictures until I knew how it works. Still, I have no way of syncing all of my pictures to my server. Please fix this, thanks.

**Comment by hodyroff** [comment]
Just tested, the limit doesn't seem to be 20 anymore. And yes, a select all button makes a lot of sense, lets include that in the next sprint, please - if nothing speaks fundamentally against it.
@michaelstingl

**Comment by michaelstingl** [comment]
Limit of 20 is still in the _Photos_ app. 3.5.2 has been already released. Need to check 3.5.3 with @owncloud/ios-developers .

**Comment by UnitedMarsupials** [comment]
> Just tested, the limit doesn't seem to be 20 anymore.

The limit is, evidently, the total size of the selected collection. When choosing from videos, the ownCloud icon can disappear from the list of sharing option after selecting only 4 items, but when choosing photos, one can select many more.

Frankly, for me at least, this is a major handicap -- my entire reason for installing oC (and paying for the iPhone app) was to replace the Dropbox, which uploads all photos and videos immediately. Why can't oC do the same?

**Comment by michaelstingl** [comment]
> Why can't oC do the same?

Did you configured "Instant Uploads" on the Settings page?

**Comment by UnitedMarsupials** [comment]
> @markley268 Did you configured "Instant Uploads" on the Settings page?

Not sure about @markley268, but I certainly do:
![oc-instant-uploads](https://cloud.githubusercontent.com/assets/1486340/23308142/23776662-fa78-11e6-98e6-82e0382ec930.png)
Dropbox-client will automatically start syncing the entire collection of images (and videos) when started -- and not stop upon losing focus (without the need to enable "Location Services"). Why wouldn't oC -- is Dropbox using some proprietary API, that Apple would not disclose to smaller developer-teams?

**Comment by michaelstingl** [comment]
@UnitedMarsupials The initial commenter opened the issue because of the upload-limitation in the "Photos" app. I think we are mixing too many things in this issue. I opened a new issue to find a good solution for the use case "upload ALL photos": https://github.com/owncloud/ios/issues/846

**Comment by nasli** [comment]
For limitations and performance reasons we should add new feature inside the app that allow the user enabled it and upload all your photos.

Close this one in favor of #847, please keep tracking there.

**Comment by michaelstingl** [comment]
FYI "Select all" got implemented in the successor of this ownCloud app. You can test with the TestFlight beta. We'd love to hear your feedback!

Here you can find more information:
- https://owncloud.org/news/working-brand-new-ios-app-sdk/
- https://central.owncloud.org/t/there-are-new-features-for-the-ios-beta-app/16992
