### ISSUE TITLE
Location tracking required?!

### ISSUE THREAD

**Issue by joshk03** [owncloud/ios#643]
I just put owncloud on my server and paid the 99c for the iPhone app so I could sync my pictures. However, it forced me to turn on location services to use the instant upload feature. I grudgingly said yes. Today my phone gave me a warning I have never seen, it said the owncloud app has been tracking me even when it was not in use. Doesn't this go against the whole privacy thing that makes owncloud what it is? And what the heck is it doing with that data anyway?

**Comment by tflidd** [comment]
ref: https://github.com/owncloud/ios/issues/370

**Comment by joshk03** [comment]
Ok, I read it and understand the honorable intentions.  But it's a fail, because it drains my iPhone battery and still does not upload my photos.  That suggestion they made last year on #370 was excellent, you need two options, 1-automated uploads 2-automatic wake.  
Here's why- 

Dropbox:
I take some pictures at home.  When I'm done I click Dropbox, and my pictures greet me on my laptop, ready for whatever comes next.

owncloud:
I take some pictures at home.  When I'm done I click ownCloud and NOTHING HAPPENS.  So I begrudgingly activate location services.  The pictures greet me on my laptop.  Then I drive to the store for printer paper, ownCloud runs constantly, draining my battery.
