### ISSUE TITLE
What is the purpose of k_multiaccount_available being available in Customization.h?

### ISSUE THREAD

**Issue by Jon-Schneider** [owncloud/ios#647]
The implementation purpose is clear - you can disable multiple-account support by setting it to NO. But I was curious if this is something that was put in for development reasons when multiple-account support was first being developed and is no longer needed, or if it is a feature that is actively used and should remain - I know it's a feature that is currently shipped with the App Store version of the app. I'm interested in adding Wifi-only photo upload to the project, and because it increases the complexity of the SettingsViewController significantly (doubling code paths) I'm curious if providing the option to explicitly disable multiple-account support is no longer desired by the maintainers because I'll remove it from the project first if this is the case.

**Comment by nasli** [comment]
@Jon-Schneider Thanks for your interest and Wellcome to ownCloud!! 
You’re also very welcome in our IRC channel #owncloud-ios (freenode IRC)
To start contributing we just need you to sign the contributor agreement https://owncloud.org/contribute/agreement/

The purpose of k_multiaccount_available is to disable multiaccount. If this is set to "NO" the app not allow multiaccount. Please, keep it as it is, some users are using it.

**Comment by Jon-Schneider** [comment]
Thanks!

**Comment by nasli** [comment]
Related to instant uploads wifi option there is an open issue #352, you can made update there. I will add an screenshot how it looks in the Android app to keep equality if possible.
