### ISSUE TITLE
Regression: Fixes from "version_3.4.8_oem" aren't included in "version_3.4.9"

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#651]
Two commits are missing:

- Setted the text color of the navigation bar on the share cells: https://github.com/owncloud/ios/commit/13f9725da0381568c019dd7b3200932e53497735
- Fixed a problem on the branding colors of the buttons on the share view: https://github.com/owncloud/ios/commit/9330366dfa734eafdf5d6a29aebde67388c1edb3

@javiergonzper Could I get a quick "version_3.4.9_oem" and could you make sure this goes into "version_3.5.0"? /cc @rperezb @jvillafanez 

00005145

**Comment by rperezb** [comment]
@michaelstingl checking this

**Comment by javiergonzper** [comment]
Hi @michaelstingl done. We created a new tag version_3.4.10 and Raquel it is working on it 👍

**Comment by rperezb** [comment]
done, https://github.com/owncloud/ios/tree/version_3.4.10 (not released to store) this will be part of 3.5.0 version
