### ISSUE TITLE
OCCapabilities.h file not found

### ISSUE THREAD

**Issue by tobitech** [owncloud/ios#653]
Hello! I just download the zip for this repo and with the first build in Xcode, i'm getting this error:
OCCapabilities.h file not found. where could the file be?

**Comment by mRoRo** [comment]
@tobitech This file is part of the OC library: [https://github.com/owncloud/ios-library](url). It seems it hasn't been added properly. Have you followed the setup file instructions [https://github.com/owncloud/ios/blob/master/SETUP.md](url) ?

**Comment by tobitech** [comment]
Thank you i've got it resolved

**Comment by maimalash** [comment]
Hi i have same issue how can i resolve it i try to add iOS-library again and it contains OCCapabilities.h

**Comment by tobitech** [comment]
Read the readme file or better follow the PDF included in the zip file download... you get to see a page that includes terminal command to add the sub module to the repository you cloned locally
