### ISSUE TITLE
iOS 10 

### ISSUE THREAD

**Issue by MTRichards** [owncloud/ios#654]
We are expecting the release of the new iOS 10 later this year, and we are starting to prepare for the release of this new version.

We are not clear at this point in time what might be changing, so the first step will be to look at the xcode deprecation warnings. We will start addressing those warnings and removing deprecated thins until we get to the release of the beta.

This is now a placeholder for discussing the warnings that are being worked on.

@javiergonzper

**Comment by MTRichards** [comment]
We will also need to look into what happens with iOS 10 and ownCloud re: Mobile Iron.

**Comment by guruz** [comment]
-> https://github.com/owncloud/ios/issues/760
