### ISSUE TITLE
Add search feature to ownCloud iOS app

### ISSUE THREAD

**Issue by vonflynee** [owncloud/ios#660]
### Client
9.3.2

3.4.9 (2c8cf9e)

iPhone 6S 128GB

 ownCloud app in iOS should have the search option. Sometimes i need to find a file on my server and I must go through all the directories in search of desired item. Could you implement search for ownCloud on iOS?

**Comment by javiergonzper** [comment]
Hi @vonflynee 

We need that the people of the server side develop an API to search the file on any folder. By now on the iOS app we just store on the DataBase the information of the folders where the user navigate.

As fas as I know they will implement it on the server in future updates but I do not know when it will be...

**Comment by rperezb** [comment]
In the short term we plan to include a search option so that It will be possible to search within the current folder, info on: https://github.com/owncloud/ios/issues/17#issuecomment-209293255

**Comment by nasli** [comment]
Duplicated, let's follow the state here #17
