### ISSUE TITLE
When selecting to upload an image within the ownCloud app not all the images available on the device are shown

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#667]
#- Starting point ( 😟 ) we have not been able to reproduce this, after having tried on several devices
- STEPS:
  + Check the number of images available on the device from the photo app
  + Select to upload an image from the ownCloud app, check that the number is not the same, less images are shown
  + However, if you access to the photp app and select to upload to ownCloud any of the non-shown images/videos, it's uploaded just fine
   + Note, all images are shown just fine on other apps
   + Note2, it was reporting on an iPhone6 iOS9.3.1

- To try to fix this we will modify what files are shown within the upload view to show everything, currently, we are not showing all the folders available on the photo app

- [x] [GIT] Create branch "use_photo_framework_insetad_assets_library" @javiergonzper 
- [X] [GIT] Merge branch "use_photo_framework_insetad_assets_library" @nasli
- [X] [QA] Create Test plan [not needed]
- [X] [QA] Validate Test plan
- [X] [DEV] Update the ELCAlbumPicker with this fork:https://github.com/amitbobade2007/ELCImagePickerController @javiergonzper
- [X] [DEV] Modify the ELCAlbumPicker to get all the albums @javiergonzper
- [X] [DEV] Modify the library to temove the IS_IOS_8 to avoid conflicts with out IS_IOS_8 @javiergonzper
- [X] [DEV] Add the Select folder button @javiergonzper
- [X] [DEV] Center the images @javiergonzper
- [X] [DEV] Add the overlay with the duration of the videos @javiergonzper
- [X] [DEV] Send the seleced items to be uplaoded @javiergonzper
- [X] [DEV] Fix the internationalization problems @javiergonzper
- [X] [DEV] Create a method to get the filename of the image or video @nasli
- [X] [DEV] Check style title navigation bar @mRoRo

PR: #679

**Comment by rperezb** [comment]
The company who reported this has confirmed that the issue is fixed 💃

**Comment by nasli** [comment]
Great!! 👍
