### ISSUE TITLE
Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#668]
**\* checking the tool ***

Hola! @rperezb has created a [ZenHub](http://www.zenhub.io) account for the **owncloud** organization. ZenHub is the only project management tool integrated natively in GitHub – created specifically for fast-moving, software-driven teams.

---
#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.io?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.
#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:
- Real-time, customizable task boards for GitHub issues;
- Multi-Repository burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- Time-saving shortcuts – like a quick repo switcher, a “Move issue” button, and much more.
### [Add ZenHub to GitHub](https://www.zenhub.io?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.io/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @rperezb._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by rperezb** [comment]
@owncloud/ios-developers  worthy to try on this tool to check what it's going on the ownCloud iOS development?
@owncloud/android-developers what do you think?

![screen shot 2016-05-24 at 13 54 55](https://cloud.githubusercontent.com/assets/1846927/15502922/27379834-21b7-11e6-9129-85126513f533.png)

**Comment by AndyScherzinger** [comment]
Looks nice and gives you a way better overview of the actual status of a release/sprint/*

**Comment by davivel** [comment]
Might work; let's see if we get to define an open workflow that fits in it.

**Comment by jabarros** [comment]
Really cool! :)

**Comment by mRoRo** [comment]
Let's try it!

**Comment by davicente** [comment]
Trying in core repository. Seems to work really slow due the amount of issues.

**Comment by davivel** [comment]
>  Seems to work really slow due the amount of issues.

:'( :'( :'( :'( :'( :'( :'( :'( :'(

**Comment by davicente** [comment]
Pluging is using 600Mb and 40% of CPU

**Comment by MTRichards** [comment]
Yeah, I tried it on core it is super slow. Still, good to use here...

**Comment by malkomich** [comment]
It seems they are currently working on its performance: https://github.com/ZenHubIO/support/issues/580

**Comment by jancborchardt** [comment]
Bummer about the performance issue, hope it’s fixed soon. Would be nice to have Github be used as primary project management instead of Jira to ensure stuff is in the open. (Except confidential stuff of course.)

**Comment by rperezb** [comment]
@jancborchardt that's what we are doing! we encourage you and all @owncloud/ios-developers and @owncloud/android-developers to download ZenHub to have access to the board. It's very helpful to get a visual view of the development current status

![screen shot 2016-05-27 at 8 58 03](https://cloud.githubusercontent.com/assets/1846927/15600264/38891d0e-23e9-11e6-8da3-8595f6fb2379.png)

Our plan is to check how this works and then update our readme file with it, you know continuous improvement, check --> do  --> act --> plan

**Comment by tobiasKaminsky** [comment]
I am getting "Thank you for trying ZenHub! This organization's ZenHub account is currently frozen. To unlock your Boards and stay connected with your team, please purchase licenses." when trying to access the dashboard via https://dashboard.zenhub.io/#/organizations/owncloud

**Comment by davivel** [comment]
I get that same page too, but the board keeps working correctly. You installed the extension for Chrome / Firefox, right?

I don't know what's the reason of the message, according to the page of pricing Zenhub is free for open source projects.

**Comment by zhaofengli** [comment]
I've shot ZenHub's support an email about this.

**Comment by rperezb** [comment]
@tobiasKaminsky that message is shown because on the ownCloud project we have a mix of public and private repos. Certainly, ZenHub is free for the public ones, such as the iOS or Android ones. We are in touch with ZenHub people with this regard.

Despite this message, having installed the ZenHub plugin you should be able to see the Board, when you access to the Android repo, do you see the new taps on the top? Just by clicking on the board one, you have access to it

![screen shot 2016-05-30 at 8 31 46](https://cloud.githubusercontent.com/assets/1846927/15641822/c2944896-2643-11e6-93fe-e2918918dde2.png)

**Comment by tobiasKaminsky** [comment]
@rperezb thanks for the clarification. The way you described it is working!

**Comment by rperezb** [comment]
nice!
