### ISSUE TITLE
[BUG-583] [iPad] Message "Updating file" is not displayed

### ISSUE THREAD

**Issue by mRoRo** [owncloud/ios#677]
Severity: Minor

STEP TO REPRODUCE
1.- In app, download a txt file
2.- In web, modify the file
3.- In app, pull down to refresh (new version available is shown)
4.- Tap on the file

ACTUAL BEHAVIOUR
File is updated but the message "Updating `file`'" is not shown

EXPECTED BEHAVIOUR
As in iPhone, the message is shown while the file is being updated.

Tested with iPad Air v8.4

**Comment by mRoRo** [comment]
#538

**Comment by mRoRo** [comment]
Probably it's related to the updated file size. In order to show the notification, the updating should take more than a second.

The used colors have been changed to: 
colorOfNavigationBar-> For the bakground of the notification
white/black according to "k_is_text_status_bar_white" constant

**Comment by jesmrec** [comment]
@mRoRo The one second delay causes that the updating message remain for the uploads that take less than one second. 

Please have a look
