### ISSUE TITLE
[BUG-583] Message "Updating file" is not correctly view with some branding options

### ISSUE THREAD

**Issue by mRoRo** [owncloud/ios#678]
Severity: Minor

STEPS TO REPRODUCE:

In Customization.h: (no much relevant)
#define k_is_text_status_bar_white YES

In UiColors+Constants.m:
//NAVIGATION AND TOOL BAR

//Tint color of navigation bar
(UIColor*)colorOfNavigationBar
{ return [UIColor colorWithRed:255/255.0f green:255/255.0f blue:255/255.0f alpha:1.0]; }

**Rest of the colors without change**

With these settings, if a txt file (for example) is updated in server side, a pull down in the app detects the changes (grey arrow), and by tapping on it the message from the upper side can not be read, because the letter and the background color are both white.

**Comment by mRoRo** [comment]
@jesmrec Now the background is the "opaque version" of colorOfNavigationBar, and the text color is black or white according to k_is_text_status_bar_white cosntant.

Please, try and let us know.

**Comment by jesmrec** [comment]
Right. Now the colors of letters and the bar are set up separately.

Fixed.
