### ISSUE TITLE
it is not possible to connect to the server at this time

### ISSUE THREAD

**Issue by kaslanq** [owncloud/ios#688]
login problem "it is not possible to connect to the server at this time"
ownCloud 9.0.2 (stable) AGPL on vultr
ios last version 3.4.9: https://itunes.apple.com/us/app/owncloud/id543672169?ls=1&mt=8

**Comment by joehell** [comment]
Same issue, so i re-installed the owncloud ios client, but impossible to re-connect to my server.

**Comment by nasli** [comment]
Thanks for reporting it, we could not reproduce here, could you send us a test account to apps@owncloud.com? Thank you!

**Comment by nasli** [comment]
Still an issue @kaslanq , @joehell ?

**Comment by kaslanq** [comment]
no problem. I changed config.php installed='true' to installed='1' 
thanx @nasli

**Comment by nasli** [comment]
You're welcome! thanks for share your fix!

**Comment by andrewhillman** [comment]
I am having same issue. I changed... config.php installed='true' to installed='1'
