### ISSUE TITLE
proper feedback on unability to view file

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#69]
Currently, if a file is not viewable, people are just left hanging as to what happens. Say for an SVG file, it simply shows the icon in big.

Instead, below the icon it should say »This file type is not viewable. Sorry about that.«

**Comment by hodyroff** [comment]
Actually it should say: "This file type is not viewable, please open it in an app which supports this file type".
Just tested it in the newest, with a .odt.

**Comment by hodyroff** [comment]
@michaelstingl maybe there is even better wording

**Comment by michaelstingl** [comment]
What about "This file type can't be displayed, please open it in a compatible app"

Could we use a "Open in…" button there that triggers the iOS system menu?

**Comment by rperezb** [comment]
````Could we use a "Open in…" button there that triggers the iOS system menu? ```

Yes, this option is in place, if you select "open in" those apps which can handle that file are shown

**Comment by michaelstingl** [comment]
This is how it works in 3.5.2:

![open-in](https://cloud.githubusercontent.com/assets/214010/21350058/a1e4d8e6-c6b5-11e6-9677-94a4eaeaab65.gif)
