### ISSUE TITLE
Resumed uploads do not end

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#695]
### Steps

1. Upload a file
2. Before it finishes, the connection is lost 
3. Connection is restablished 

### Actual Behaviour

Upload is resumed but not finished, at the end it remains "Waiting for connection"

### Expected behaviour

Upload is resumed and finishes correctly

* If several files are uploaded at time, one of them remain "Waiting for upload". The others are uploaded correctly

Tested with iPhone6 v9. A huge file was used to reproduce ir
ownCloud Version: 3.4.9

**Comment by rperezb** [comment]
@jesmrec is this a regression?

**Comment by jesmrec** [comment]
no, it's not regression, so it is reproduced in the market version.

**Comment by rperezb** [comment]
@jesmrec thanks

**Comment by nasli** [comment]
Other steps: from https://github.com/owncloud/ios/issues/662#issuecomment-226167010

In a shibboleth server, try tu upload a huge file (a video, for example). When the session expires and the file is not completely uploaded, input the credentials.

The upload is not resumed

**Comment by nasli** [comment]
Checked, and at the end the file is uploaded correctly

**Comment by jesmrec** [comment]
Checked and working

**Comment by nasli** [comment]
Closed as not reproducible
