### ISSUE TITLE
title moved slightly to the right

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#70]
In the detail view of a file, the title is not centered but rather slightly moved to the right. See https://s3.owncloud.com/owncloud/public.php?service=files&t=dff68a475c391f42246c26294424e47e

This seems to be because it’s centered according to the space left in the header, with the back button taken into account. Instead, it should be centered absolutely (but of course not overflow with the back button).

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
