### ISSUE TITLE
SAML session expires when share view is opened

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#700]
### Steps to reproduce
1. Open a session in a SAML server v9.1
2. Try to share a file/folder

### Expected behaviour
Usual behaviour of share view

### Actual behaviour
Session expires, no matter how long it was opened.

### Server configuration
{"installed":true,"maintenance":false,"version":"9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"}

Tested with iPhone6 v9.3.2

**Comment by SergioBertolinSG** [comment]
cc @DeepDiver1975

**Comment by rperezb** [comment]
waiting for server info

**Comment by jesmrec** [comment]
Server problem fixed, working fine on mobile clients.

**Comment by rperezb** [comment]
@jesmrec please check in on the desktop client too

**Comment by jesmrec** [comment]
@rperez 

checked also in desktop and works fine.
