### ISSUE TITLE
Can not decrypt file on mobile client

### ISSUE THREAD

**Issue by team-alpeinsoft** [owncloud/ios#701]
### Steps to reproduce
1. Install owncloud.
2. Enable encryption.
3. Share file with user.
4. Try download file from mobile client 
### Actual behaviour

Cannot download file from mobile client when using server side encryption
1. Web interface - working
2. Problem actual not only for ios .
https://github.com/owncloud/android/issues/1711
### Server configuration

**Web server:**
apache2                        2.4.10-10+deb8u4                 amd64

**Database:**
mysql-server-5.5               5.5.47-0+deb8u1                  amd64

**PHP version:**
PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 11:26:05) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
### Client

**iOS version:** All versions

**ownCloud app version:** All versions

**Device model:** All models
#### Web server error log

[10/Jun/2016:14:45:33 +0200] "GET /owncloud/remote.php/webdav/community.txt HTTP/1.1" 500 1630 "-" "Jakarta Commons-HttpClient/3.1"
#### ownCloud log (data/owncloud.log)

{"reqId":"m01\/psu9n5hlK1KbxI1\/","remoteAddr":"37.17.19.59","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-06-10T12:45:34+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/community.txt","user":"C96C88E4-9F71-4E45-9D6D-4FF46F01AEB6"}
{"reqId":"m01\/psu9n5hlK1KbxI1\/","remoteAddr":"37.17.19.59","app":"webdav","message":"Exception: {\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Exception\":\"OC\Encryption\Exceptions\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(459): OCA\Encryption\Crypto\Encryption->decrypt('NB2yToafXnn8ROy...', '0end')\n#1 \/var\/www\/owncloud\/lib\/private\/files\/stream\/encryption.php(290): OC\Files\Stream\Encryption->readCache()\n#2 [internal function]: OC\Files\Stream\Encryption->stream_read(8192)\n#3 \/var\/www\/owncloud\/3rdparty\/icewind\/streams\/src\/Wrapper.php(83): fread(Resource id #83, 8192)\n#4 \/var\/www\/owncloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(91): Icewind\Streams\Wrapper->stream_read(8192)\n#5 [internal function]: Icewind\Streams\CallbackWrapper->stream_read(8192)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php(78): stream_copy_to_stream(Resource id #86, Resource id #88, '861')\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(470): Sabre\HTTP\Sapi::sendResponse(Object(Sabre\HTTP\Response))\n#8 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#9 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\DAV\Server->exec()\n#10 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#11 {main}\",\"File\":\"\/var\/www\/owncloud\/apps\/encryption\/lib\/crypto\/encryption.php\",\"Line\":360,\"User\":\"C96C88E4-9F71-4E45-9D6D-4FF46F01AEB6\"}","level":4,"time":"2016-06-10T12:45:34+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/community.txt","user":"C96C88E4-9F71-4E45-9D6D-4FF46F01AEB6"}

**Comment by rperezb** [comment]
@PVince81 does this make you ring any bell?
@SergioBertolinSG FYI

**Comment by PVince81** [comment]
Question is whether this user ever logged in before at the time the share was created ?
Or was this user added to a group recently and the file was shared with that group ?

Best is to try unsharing the file again, ask that user to log in (if not already) and then share the file again.

**Comment by team-alpeinsoft** [comment]
It`s not working not only for share file, but and other files( for example for my own files and folders ).

**Comment by team-alpeinsoft** [comment]
For new user(from LDAP) all works ( share & downloads ).

**Comment by PVince81** [comment]
@team-alpeinsoft are you able to log out then log in again the user who has trouble with the decryption ? Maybe something went wrong with the current session.

**Comment by team-alpeinsoft** [comment]
@PVince81 I logout - no result,  remove and add account  in mobile version - no result.

**Comment by PVince81** [comment]
@team-alpeinsoft can that user download files using the web UI ? Or any other Webdav client ? (goal is to find out whether there is something with the mobile client or something is wrong with this account)

**Comment by team-alpeinsoft** [comment]
1. Web interface + 
2. Windows client +

**Comment by PVince81** [comment]
"+" meaning it works ? Or getting the same error ?

**Comment by team-alpeinsoft** [comment]
Works :)

**Comment by PVince81** [comment]
Hmmmm... what about a mobile IOS from another device ? So far I think the IOS client has always worked with encryption so I'm not sure what would be wrong with that user apart from maybe a session that isn't cleared/reset properly.

**Comment by team-alpeinsoft** [comment]
We login in new ios device - no result.

Error on mobile:

<?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>OC\Encryption\Exceptions\DecryptionFailedException</s:exception> <s:message>Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.</s:message> </d:error>

Error on server side:

{"reqId":"z19T\/GcaqR+aSQQ4ObBp","remoteAddr":"80.249.84.82","app":"webdav","message":"Exception: {\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(459): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('NB2yToafXnn8ROy...', '0end')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(290): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #117, 8192)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#5 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #120, Resource id #122, '861')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php\",\"Line\":360,\"User\":\"96DB31B3-7E84-4C2D-B640-7FC2EF61A0BF\"}","level":4,"time":"2016-06-13T13:56:06+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/community.txt","user":"96DB31B3-7E84-4C2D-B640-7FC2EF61A0BF"}

**Comment by PVince81** [comment]
Okay thanks. So this means that the IOS app is doing something differently with the session/cookies.

**Comment by team-alpeinsoft** [comment]
And thank you. p.s. Problem actual not only for ios .

**Comment by team-alpeinsoft** [comment]
Additional information. Via mobile client i can create folder and files, upload on the server. Only downloading options with error.

**Comment by muppeth** [comment]
I can confirm the same issue on my instance with Android app. I can upload, but no download. Works perfect with desktop client and web insterface.

**Comment by muppeth** [comment]
@team-alpeinsoft do you think it's LDAP related? 
I've created new users with default backend (no Ldap) to see whether the error persist, and it was gone. All users not in LDAP can download files with mobile app. The issue only affects LDAP users. 
Did you get any further with your investigation?

**Comment by team-alpeinsoft** [comment]
@muppeth  We have a 50/50 result. Some LDAP users are all well, others - does not work.

**Comment by muppeth** [comment]
@team-alpeinsoft AS far as I checked on accounts I have access to, none of them work. Same applies to newly created LDAP users. Only non-ldap users can decrypt data via android app.

It seems strange that in your case you have 50/50 result. Do you see a pattern there?

**Comment by team-alpeinsoft** [comment]
Yes. It`s strange and we don`t know how fix this problem.

**Comment by rperezb** [comment]
@team-alpeinsoft thanks for reporting this, currently @owncloud/qa team is checking this

**Comment by muppeth** [comment]
@team-alpeinsoft when did you realized the problem started? I've only realised after one of our users reported the problem, but it might be as long as oc8 > oc9 update.

I've checked if problem stays when upgrading to Nextcloud (both core and android app) and it is still there.

My only guesses atm are:

 - something broke when updating to owncloud9.
 - some recent OS update is causing the error.

I'm also looking for people running similar setup (oc+encryption+ldap) to see if this problem is affecting more ppl.

@rperezb thanks for taking time looking into this issue.

**Comment by team-alpeinsoft** [comment]
@rperezb  And thank you!

@muppeth  When we realized the problem? At random, when we can`t downloud files via mobile apps.

**Comment by muppeth** [comment]
@team-alpeinsoft I meant when was the first time you spotted problem exist.

**Comment by jesmrec** [comment]
Checking this issue with the following set up:

Server: 

`{"installed":true,"maintenance":false,"version":"9.1.0.9","versionstring":"9.1.0 beta 2","edition":"Enterprise"}`

Clients:

Android v5.0.1
iOS v9.1

Test cases:

1. User1 shares some docs with User2 (LDAP user)
2. User1 & User2 download the files and view them

1. User1(LDAP) shares some docs with User2 (LDAP user)
2. User1 & User2 download the files and view them

Checked also with folders

All downloads work fine.

**Comment by muppeth** [comment]
@jesmrec Did you use encryption module?

**Comment by jesmrec** [comment]
@muppeth yes, i used the default encryption module in order to encrypt server side files as you can check in my previous message.

**Comment by muppeth** [comment]
@jesmrec sorry I saw your msg before the edit. 

> Any input related to the doc type? Which kinds did you check? Were there in any external mount point stored?

In my case I checked jpg, pdf, png. All fail. User can create and upload files via android app but can't download (as stated before).

**Comment by team-alpeinsoft** [comment]
@muppeth : I meant when was the first time you spotted problem exist. ---> when open access( share folders) for few users.

**Comment by team-alpeinsoft** [comment]
>  input related to the doc type? Which kinds did you check? Were there in any external mount point stored?

Doc, pdf, txt , jpg and etc. 
No, we use local storage on debian system.

**Comment by jesmrec** [comment]
thanks for the feedback, but i could not reproduce it. Now, these steps:

1.- New server with LDAP auth (no encryption enabled)
2.- User1 and User2 add to the mobile app
3.- User1 shares with User2 images and a folder which contains several doc types (doc, xls, pdf..) -> User2 can download and view all files
4.- Enable encryption in server side
5.- Two new users User3 and User4 added to the app
6.- User3 shares with User4 images and files -> User4 can download and view all of them
7.- User1 shares with User4 images and a folder which contains several doc types (doc, xls, pdf..) -> User4 can download and view all files

All users are LDAP users. 

So, users added before enabling the encryption and after enabling encryption can download. 

Tested with server v9.0 and v9.1 and same devices as above message.

**Comment by team-alpeinsoft** [comment]
Our last steps:
1) Update owncloud to 9.0.2
2) Create few two local users and User1 shares with User2 images and files -> User2 can not download and view all of them
3) Disable encryption on server side: 
sudo -u www-data php occ maintenance:singleuser --on
sudo -u www-data php occ encryption:decrypt-all
Old files not download. New files - no problem.
4) Enable encryption, then old and new files not download.

In all steps we have single error message: Can not decrypt this file, probably this is a shared file.

**Comment by muppeth** [comment]
My tests:
### Deploy New owncloud instance on the same host. 
I deployed fresh install of Owncloud on the same host, but creating new database.
1.Enable LDAP backend
2.Enable encryption
3.Login as a LDAP user
 - Upload files via WebUI (works)
 - Download files via Android App (doesnt work)
 - Upload files via Android App (works)

4.Login as Admin (non-LDAP)
 - Upload via WebUI (works)
 - Upload via Android App (works)
 - Download Web/Android (works)

### Deploy Owncloud on new Virtual Machine
Deploying fresh install on fresh virtual machine results with the same errors.

**Conclusion:**
- Bug in Owncloud core / mobile client
- Missing dependency package
- Wrong version of dependency package

**Comment by team-alpeinsoft** [comment]
**Our php-modules:**
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by jesmrec** [comment]
<currently trying to reproduce the problem> with these modules:

`[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
ldap
libsmbclient
libxml
mbstring
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache`

**Comment by team-alpeinsoft** [comment]
@jesmrec  Our diff:
![image](https://cloud.githubusercontent.com/assets/19687602/16407684/ab608248-3d1d-11e6-9304-649dfc76c20c.png)

**Comment by jesmrec** [comment]
i will add the `mcrypt` and re-test

**Comment by jesmrec** [comment]
Both decrypted and encrypted download fine, this is like a poltergeist :)

If you want, you can send us a LDAP test account of your server to `apps@owncloud.com` in order to check the problem in situ.

**Comment by team-alpeinsoft** [comment]
@jesmrec : We wanted grant access to owncloud system copy . We create new users in LDAP, but for new users all worked.

**Comment by jesmrec** [comment]
another question, from which version did you upgrade?

**Comment by team-alpeinsoft** [comment]
@jesmrec : 

> another question, from which version did you upgrade?

9.0.1.3

**Comment by team-alpeinsoft** [comment]
@muppeth 

> 4.Login as Admin (non-LDAP)
Upload via WebUI (works)
Upload via Android App (works)
Download Web/Android (works)

Confirm. For local users all works.

Can you try test for old ldap users?

**Comment by muppeth** [comment]
@team-alpeinsoft 
In my case seems like all Ldap users are affected. I cant access all of them of course, but I have few accounts on the server created on different occasions (spread in time) that I have access to (including the first account created on the server), plus all new test accounts I created since the problem was discovered.
As I mentioned I deployed both clean Owncloud and Nextcloud with clean databases to test whether something might have broke during the update on my production server. The only thing that stayed the same was LDAP server. To be sure I used ldap admin account to bind with owncloud so that it would have all the rights, both read and write to all ldap accounts. Still the problem is there. 

I compared all the php modules posted by you guys and we seems to use pretty much the same setup.

I will now try out with clean LDAP setup to make sure this isn't the root cause (or it is, so at least we know what is the problem).

Just to mention I use debian jessie.

**Comment by team-alpeinsoft** [comment]
@ muppeth  and other guys from owncloud team : thank you for research. 

We also use debian jessie.

We try recreate this problem ( install few new vm, ldap databases ) - all  works fine. Problem with only one instance. And why it`s not work on mobile version? Web and mobile application have cardinal differences in code?

**Comment by team-alpeinsoft** [comment]
May be interesting : https://github.com/owncloud/core/issues/18000

**Comment by muppeth** [comment]
Yet another update form my side, though not in anyway fixing the problem unfortunately.
First maybe some info that I haven't post previously about our setup.
We run Database, owncloud and ldap as seperate vms.

Here is what I did last night (great way of seeing sun rise btw :P)
I've found some old backup dating march (pre oc9). I deployed databse, ldap and owncloud vms. Tested the ldap users with android app and it all worked fine. Now:

1. I then copied the oc code into that older vm, and I migrated db to old db vm. Running new OC on old setup (old system packages etc), was causing the issue.
2. I reverted database back to the old one (oc8.2 i belive), and run owncloud update to oc9. That resulted in the issue appearing again.
3. I removed all users from ldap vm, leaving only one for testing. Problem persisted.
4. I moved old oc code and database to new/current vms (to see if it breaks with new packages). Everything worked fine so we can dismiss server setup at this point.
5. I installed oldest owncloud client i could find on f-droid (1.9.1) but the problem is still there when using it against oc9.

Next step is to install everything on single vm, as I'm now running out of ideas.

**Comment by team-alpeinsoft** [comment]
@muppeth:

> 
Here is what I did last night (great way of seeing sun rise btw :P)
Yes :)

> 
Next step is to install everything on single vm, as I'm now running out of ideas.

In our case all servrices on a single vm.

**Comment by muppeth** [comment]
> Next step is to install everything on single vm, as I'm now running out of ideas.

That didnt work either. 
I'm now pretty sure the problem must be related to some little silly package missing in my template. I will install Full Debian 8 and see if that changes anything, otherwise seems like I'm cursed and even when installing owncloud from scratch, I'm forbiden to use Android app :P.

**Comment by team-alpeinsoft** [comment]
We migrated to another VM:
uname -a
Linux nxt-hst 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u2 (2016-06-25) x86_64 GNU/Linux

**php -v**
PHP 5.6.22-0+deb8u1 (cli) (built: Jun  9 2016 07:14:06) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**apache2 -v**
Server version: Apache/2.4.10 (Debian)

**php -m**
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

No results.

**Comment by team-alpeinsoft** [comment]
p.s. https://github.com/owncloud/android/issues/1711  -> silence

**Comment by muppeth** [comment]
@team-alpeinsoft 
I also did some more tests and whatnot and so far got to conclusion that something must have gone wrong with database when updating from OC8 to OC9. I will focus on this tonight.

**Comment by jvillafanez** [comment]
@team-alpeinsoft @muppeth Did you run the "encryption:migrate" occ command?

Steps should be as follow:
1. Enable files_encryption app in OC 8.2
2. Create files, user accounts, etc (normal usage of ownCloud)
3. Download and upgrade to OC 9
4. Enable encryption app: `occ app:enable encryption`
5. Enable default encryption module: `occ encryption:enable`
6. Migrate encryption keys: `occ encryption:migrate`  (This step is what might be missing)
7. Normal usage

If you did everything through the web UI is very likely that the key migration didn't happen. I'm not sure if it's possible to execute it from the web UI.

**Comment by muppeth** [comment]
@jvillafanez I'm pretty sure I've done that, though cannot be 100% sure as I updated to oc9 in April. I am about to redo the update process on my test machine since i seem to have backup (i think.).
I only dont understand if key migration was not done, why is my encryption working in webui and desktop client, but fails with mobile clients. Also non-ldap users work without problem.
Also why are new users affected by it. 

In any case @jvillafanez  thanks for advice. I will play around with pre oc9 backup and let you know if I find anything. 

As I was comparing both my production db with just freshly installed oc instance, I haven't seen anything related to encryption. All ldap replated entries in both instances seem to be in order. I even deleted all entries in oc_filecache to see if this is related, but did not change anything besides not being able to generate thumbnails etc. Anyone has any idea what to look for? Again it seems to be only related to ldap users.

**Comment by FloFra** [comment]
Could you check if any of you file actually do no have a key? You could use a script similar to this one:
```
#!/bin/sh

if [ $# -ne 1 ]; then
    echo "usage: $0 <user>"
    exit 0
fi

files=/var/www/html/owncloud/data/$1/files
keys=/var/www/html/owncloud/data/$1/files_encryption/keys/files

find $files | sed "s:^$files::" | sort > /tmp/a
find $keys | sed "s:^$keys::" | grep -v OC_DEFAULT_MODULE | sort > /tmp/b
diff /tmp/a /tmp/b 
```

**Comment by neuhausjulian** [comment]
I also have the same problem. And it is also only related to ldap-users (Owncloud9 - Android-Client)

**Comment by muppeth** [comment]
@neuhausjulian sad at the same good to see more of us, maybe we can pin point the issue.  When did you notice the issue? Was it any particular thing you did (update, installing/removing app, changing any config?).

I haven't paid too much attention to this issue as I was busy with other things on my todo list. However according to my planning I should be done with all of them by the end of the week, so the next thing on the list is solving that issue. If everything goes well I will dedicate all my free time next week to finally fix it (or at least go further with it). 

Last resort would be dropping encryption I guess.

**Comment by neuhausjulian** [comment]
@muppeth 

I installed and started running owncloud 2 weeks ago. At first I only used the admin account with no problems on every client.
On monday I installed a ldap-server and yesterday (2016-08-30) I added my ldap-server as login-authentication to owncloud.

With my first ldap-account I checked the encryption behaviour if I change the password. No problems on web- and desktop-client bevor and after. I didn't checked the mobile-client before.
I added also a new ldap-user uploaded a single picture and added the new user on my mobile-client. Also broken without any password changes.

The admin-account (not-ldap) is still working 

Error-log:

Exception: {"Message":"HTTP\/1.1 404 File with name Dokumente\/ich.JPG could not be located","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(79): OCA\\DAV\\Connector\\Sabre\\ObjectTree->getNodeForPath('Dokumente\/ich.J...', 0)\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","Line":170,"User":"2b1bd114-0309-1036-9a86-435a68297ecb"}

**Comment by muppeth** [comment]
After long while I finally have time to take care of that issue.
I decided to check if anything happend.
**Owncloud server side.** I haven't update the core nor any of the apps.
**Mobile client**
I installed fresh nextcloud beta and owncloud beta to see if the issue is still there.
**Nextcloud beta** - Just works! \o/ It uploads files without problem.
**Owncloud beta** - at first. When uploading straight from gallery app I was getting errors, but after selecting a file via "Upload" it also did upload the file. 

@neuhausjulian @team-alpeinsoft could you guys check and confirm?

**Comment by muppeth** [comment]
eeeh scratch that.. So much time has passed I forgot it was download that was the issue and not upload. 

There is still problem downloading. :(

What I also noticed is that notes gives the same error.

**Comment by team-alpeinsoft** [comment]
Hi!
@muppeth We  reinstall from scratch owncloud 9.1 and problems have disappeared.

**Comment by neuhausjulian** [comment]
I will try the same as solution. After reinstall I will post my result.

**Comment by muppeth** [comment]
I found the problem, though I don't know why is it happening.

Basically removing mail attribute form "Email Field" solves the problem. I don't know why is that happening.

The down side is that new user email fields are empty now.
Anyone has thoughts on this one?

**Comment by muppeth** [comment]
@team-alpeinsoft does your current setting have "Email field" filled in?

**Comment by PVince81** [comment]
Hmmmm, there was a known issue with the LDAP email field. Basically every time the user logs in in OC it would get the email value from LDAP and then set it to the local user, and that itself would trigger some change events even when the email did not change. Maybe these change events were causing additional side effects. See https://github.com/owncloud/core/pull/25553

Please update to OC 9.0.5 or 9.1.1 and see if the problem is solved there.

**Comment by muppeth** [comment]
You are probably right. I'm still running owncloud 9.01. Yesterday night
I've updated my test instance to nextcloud 10.01 and the issue is gone,
and it was. I will test it with up to date owncloud as well tonight to
see if it helps.

**Comment by neuhausjulian** [comment]
Hi guys, I updated to owncloud 9.1.1-1.2 and the problem is also gone.

The problem in the android-mobile client disappeared immediately after update

**Comment by team-alpeinsoft** [comment]
Hi! We reinstall owncloud and can`t diagnose problem.
@muppeth: may be you?

**Comment by muppeth** [comment]
I'm quite certain it was a bug in LDAP settings, where "Email Attribute" was the root cause. I haven't test it on latest owncloud (didnt have time), but I did on latest nextcloud, which should be quite similar in this regard

**Comment by team-alpeinsoft** [comment]
May be other can repeat error?

**Comment by muppeth** [comment]
@team-alpeinsoft I don't think it's an issue anymore when using latest version of owncloud/nextcloud.

I did not install from scratch but found the root cause and when upgrading to latest nextcloud (form owncloud) the issue was solved. I assume when updating the instance to the latest owncloud the result would be the same. They are using the same LDAP auth plugin.
