### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by tflidd** [owncloud/ios#706]
### Steps to reproduce
1. Select picture
2. Send to owncloud (-> then owncloud-window opens)
3. On the bottom, select location (a folder)
4. Press on "upload to"

### Expected behaviour
Picture is uploaded to this folder (and it was working before).

### Actual behaviour
Nothing happens.

### Server configuration
**Web server:** Apache 2.4

**Database:** Mysql

**PHP version:** PHP 7.0 (dotdeb)

### Client
**iOS version:** 9.3.2

**ownCloud app version:** 3.4.9

**Device model:** iPhone 5S

#### Web server error log
When selecting a folder, I see that the client is doing something.
```
ip - username [20/Jun/2016:17:18:00 +0000] "PROPFIND /owncloud/remote.php/webdav/folder/subfolder/ HTTP/1.1" 207 1656 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.4.9"
```
but when I submit the picture, nothing happens.

#### ownCloud log (data/owncloud.log)
```
nothing
```

**Comment by nasli** [comment]
Hi @tflidd, thanks for your feedback,
That it is the expected behaviour, the files are added into the queue and start uploading once you open the app.

**Comment by tflidd** [comment]
Ok, that's right.

Was it always like that? This behavior is not very intuitive, I would 
prefer a direct upload or at least a small feedback/note that says that 
the file will be uploaded when I start the app.

**Comment by nasli** [comment]
@tflidd yes, we could improve with an alert message , could you open a new enhancement issue with this? Thanks!
