### ISSUE TITLE
All iOS Apps To Work in IPv6-ONLY Networks - Does this mean we cannot to our IPv4 OwnCloud?

### ISSUE THREAD

**Issue by supportreq** [owncloud/ios#712]
Starting from 1st June it seems apple requires all ios apps to work in ipv6-only networks.
Will this change stop access of the owncloud app to our ipv4 owncloud servers?

Please advice..
thank you

**Comment by philthy22** [comment]
I have never been able to get OwnCloud to work on iPhone 5s...absolutely ridiculous !!!

**Comment by nasli** [comment]
@supportreq Thanks for remember this, we will take into account for the new release an let you known.

@philthy22 sorry to hear that, could you give us more details in order to help you?
What problem do you have? you can not log in? navigate?
What type of server are you using?

**Comment by Relequestual** [comment]
@supportreq Apple requiring apps to work within IPv6 only networks does not mean that IPv4 will then not work. That would be totally crazy and unworkable.

**Comment by nasli** [comment]
As @Relequestual said, should not affect OC app.

**Comment by Relequestual** [comment]
3.5.0 is closed... WOO!
**eagerly awaits 3.5.0**

**Comment by nasli** [comment]
Expected for next week!
