### ISSUE TITLE
Add notification in the "share in" window

### ISSUE THREAD

**Issue by tflidd** [owncloud/ios#722]
If you pass a file from a different app to the ownloud app, you can choose where to upload the file but you have to open the owncloud app to start the upload.

Feature request: Put a notification on the upload page that you need to start the application manually in order to upload the file.

ref. https://github.com/owncloud/ios/issues/706

**Comment by nasli** [comment]
Thanks for your suggestion @tflidd

**Comment by hodyroff** [comment]
Is this possible? Effort?

**Comment by nasli** [comment]
Yes @hodyroff and should be minor

**Comment by nasli** [comment]
A notification has been added and will be available within next 3.5.3 release.
