### ISSUE TITLE
How about appending Chinese(zh-Hans/zh-Hant) support in localization strings

### ISSUE THREAD

**Issue by ljysdfz** [owncloud/ios#735]
### Tell us what could be improved:
There've been a large number of Chinese developers who care for owncloud. How about appending Chinese(zh-Hans/zh-Hant) support in localization strings?

**Comment by nasli** [comment]
@ljysdfz thanks for your feedback!

We use transifex to translate the project, https://www.transifex.com/owncloud-org/owncloud/dashboard/  right now the percentage for Chinese:

Chinese(china) zh_CN (61%)
Chinese(Taiwan) zh_TW (89%)

You are more than welcome to join our transifex community and help with these and other languages ;)

**Comment by nasli** [comment]
@ljysdfz what about add  these for the next release Chinese(Taiwan) zh_TW (89%)?

@DeepDiver1975 could you add "Chinese(china)" zh_CN, "Chinese (Taiwan)" zh_TW , "Albanian" sq, "Norwegian Bokmål (Norway)" nb_NO and "Slovenian" sl  ?

**Comment by nasli** [comment]
Added with correct xcode conversions via https://github.com/owncloud/ios/commit/50af765c3711217177c146afaa01d9dc0f8aa4b8

**Comment by DeepDiver1975** [comment]
> could you add "Chinese(china)" zh_CN, "Chinese (Taiwan)" zh_TW , "Albanian" sq, "Norwegian Bokmål (Norway)" nb_NO and "Slovenian" sl in Jenkins ?

done - nb_NP was already setup to be pushed to the ios repo

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/ios/commit/8476d95072ab2570e2de388ad3492932920fabd8

**Comment by nasli** [comment]
Thanks @DeepDiver1975 ! 

@ljysdfz  zh-Hans-CN  and zh-Hant-TW will be within next release 3.5.0, I encourage you to join our transifex community to increase the percentage of these languages ;)
