### ISSUE TITLE
InstantUpload only works when the "Uploads" tab of the app is opened

### ISSUE THREAD

**Issue by andreasba** [owncloud/ios#736]
Hi there,

I have a similar issue to https://github.com/owncloud/ios/issues/573 but not quite the same. Basically the InstantUpload only uploads when I check the "Uploads" tab of the app which belies the name of the feature ;-)

Please let me know if you need more details!

Thanks
Andreas

### Steps to reproduce
1. Take a picture
2. Open the (already launched) app
3. Authenticate via PIN or TouchID
4. Go to the "Uploads" tab and wait a few seconds - the app will then recognize, that new pictures have been taken, add them to the queue and upload them

### Expected behaviour
The pictures should be uploaded automatically without manual intervention

### Actual behaviour
They only get uploaded if I open the app and go to the "Uploads" tab

### Server configuration
**Web server:** Linux (?)

**Database:** MySQL 5

**PHP version:** 7?

### Client
**iOS version:** 9.3.2

**ownCloud app version:** 3.4.9

**Device model:** iPhone SE

**Other:** Location, Bluetooth and WiFi are always on

**Comment by nasli** [comment]
Hi  @andreasba ,

could you check it with the latest 3.5.0 version?

Within 3.5.0 has been refactored network process as well as instant uploads process.

If needed reopen it. Thx!
