### ISSUE TITLE
[App icons] Update the app icon

### ISSUE THREAD

**Issue by rperezb** [owncloud/ios#744]
Following: https://github.com/owncloud/android/pull/1594
- [X] Update the app icon 
- [X] the login screen 
- [X] splash image
- [X] preview in ipad 
- [X] help guide

PR: #766

**Comment by jesmrec** [comment]
@nasli if the splash image and the cloud image in the wizard was also community-blue, the theming would be more consistent.

**Comment by nasli** [comment]
All images updated @jesmrec, try again :)

**Comment by jesmrec** [comment]
I have reviewed it, and noticed this:

- The splash image changes to the new colour when is close to disappear.
- In iPadPro, the image resolution should be improved in the rigth side of files view.
- In the intro wizard, only the 5th slide has the new cloud colour.

cc @nasli

**Comment by nasli** [comment]
More images updates, try again @jesmrec . But personally I prefer the previous light blue for the cloud in help intro guide, splash and preview view.
![simulator screen shot 05 sep 2016 08 47 07](https://cloud.githubusercontent.com/assets/6570505/18239394/5d827302-7345-11e6-9ee9-d01ed9e73a03.png)

**Comment by rperezb** [comment]
@nasli can you please add some transparency to the cloud image so that the file images are previewed better?
on the other hand, perhaps it'd be good idea to change the log in button background color to the ownCloud community one, as it's on Android

**Comment by jesmrec** [comment]
The lighter image fits better with this slide, so it can be used for the wizard and the darker one for the other icons in the app.

**Comment by nasli** [comment]
Ok, updated images to keep light blue for intro guide.

**Comment by jesmrec** [comment]
All the icons are ok. 

I will suggest an enhacement for the login view. As you can see in the Android login view, the colour  of the "Connect" button is the same as the icon colour:

<img width="273" alt="screen shot 2016-09-13 at 12 05 43" src="https://cloud.githubusercontent.com/assets/14894746/18470005/d36907e6-79aa-11e6-84f3-44a1ca072ebe.png">

i think it looks better than different colours as the iOS app. 

Opinions, thougths... ?

cc @nasli

**Comment by nasli** [comment]
@jesmrec for now I will suggest leave with this color and think for next release on this.

**Comment by jesmrec** [comment]
Ok, let's check the connect button colour in a different PR. This one approved.
