### ISSUE TITLE
Instant Upload does not recognize file again if you close the app during of the download

### ISSUE THREAD

**Issue by payam-huemer** [owncloud/ios#745]
So after the instant upload got refactored the following issue has occurred:

### Steps to reproduce
1. Take a picture
2. Open App, in uploads tab you will see the new photo "waiting for upload" status
3. wait till the app starts to upload a bit
4. close the App DURING the upload process
5. Open the App again, you will not see the photo in the instant upload folder nor under uploads

### Expected behaviour
App should re-try to upload the photo

### Actual behaviour
Tell us what happens instead
App does not recognize the failed image again

**iOS version:**
9.3.3

**ownCloud app version:**
Branch master

**Comment by Jon-Schneider** [comment]
I would guess that this was also an issue before Instant Upload was refactored, as the last upload date was simply set when the uploads were started before I refactored it. Currently in the app there's no way to hook into queued file downloads so the app can keep track of their success/failure so the app can requeue Instant Uploads that failed.

**Comment by payam-huemer** [comment]
Well, I tested it numerous time (even once more before i'm writing this comment) with the old one, it is working fine.

**Comment by nasli** [comment]
Hi @payam-huemer, thanks for your feedback, could you try with "release3.5.0" branch?
Master is not an stable branch and within release3.5.0 branch have been made some fixes
Thanks!

**Comment by payam-huemer** [comment]
@nasli hello, I just switched branches and tested again. Unfortunately still not working.

**Comment by nasli** [comment]
@jesmrec @Jon-Schneider  could you reproduce it?

**Comment by jesmrec** [comment]
@nasli @payam-huemer I could not

I performed these steps:

1. Enable instant uploads
2. Five pics taken
3. When two of them were uploaded, i killed the app and rebooted the device.
4. Booted again the device and opened the app. 

Initially the remaining three uploads did not appear, but after two or three seconds they did and were correctly upload.

Set-up:

iPhone6 v9.3
Enabled passcode&touchId
Enabled device passcode
Server version:{"installed":true,"maintenance":false,"version":"9.1.0.15","versionstring":"9.1.0","edition":"Enterprise"}
Branch: `release3.5.0`

Do you notice any difference with your performance?

**Comment by payam-huemer** [comment]
hmmm, I'm gonna close this since no one can reproduce it. I'll leave a comment if I find out what the problem is.

my setup:

iPhone5 v9.3
disabled passcode&touchId
Enabled device passcode
Server version:{"installed":true,"maintenance":false,"version":"8.2.5.2","versionstring":"8.2","edition":""}
Branch: release3.5.0
