### ISSUE TITLE
SAML multiaccount expires accounts when are switched

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#747]
### Steps
1. In a SAML server, sign in two accounts (same or different server)
2. Open one of them
3. Switch to the another one
### Actual behaviour

The first operation makes the session expire although the time is not expired.
### Expected behaviour

Session does not expire until the lifetime is expired

Device: iPhone6 v9.3.
Server 9.1

- [x] [GIT] Create branch fix_exp_after_login
- [X] [DEV] Debug to discover what it is happening
- [x] [DEV] Resolve the bug
- [x] [QA] Perform test plan
- [ ] [GIT] Merge branch fix_exp_after_login

**Comment by davivel** [comment]
@jesmrec , we need to retest this in the context of #875

**Comment by jesmrec** [comment]
In the current status of `master` branch, this bug is not happening. Closing.

**Comment by nasli** [comment]
Reproducible again within 3.7 version
