### ISSUE TITLE
Mobile Device Management and OwnCloud App

### ISSUE THREAD

**Issue by VikDex** [owncloud/ios#748]
Hello together,

thanks for this great app.

One question from many companies using OwnCloud.
Please make it possible to preconfigure the ios App via a "MDM profile".
like: username, serveraddress, special settings ...
This is a "state of the art" solution for preconfiguring managed Apps over the air:
described here: 
-> https://developer.apple.com/library/ios/samplecode/sc2279/Introduction/Intro.html

I found the following in the board .. no solution yet.
https://forum.owncloud.org/viewtopic.php?t=20382

**Comment by hodyroff** [comment]
@nasli What would it take to make this happen? We do some of this through ownBrander, or?

**Comment by nasli** [comment]
We have to take into account that these are **sensitive data.** 

What we do through ownBrander is to set up some config constant previously to compilation of the app.

If we use this, we will hardcode credentials in the code, no good.

And using NSUserDefault as https://developer.apple.com/library/ios/samplecode/sc2279/Introduction/Intro.html suggest, is also not recommended as OWASP suggest in his top 1 iOS security risk.

We have to investigate deeply in order to find the better approach to set up all this data

@VikDex , to understand better your need:
How do you want to distribute the app to your users, via Ad hoc, Play Store?
What other special settings do you need to set up?
Do you want that the user only can log in with the preconfigured username account?
The password will be enter for the user?
Do you plan to configure individually for each user?

Thanks

**Comment by VikDex** [comment]
Ich kehre zur�ck am 05.09.2016.

Ihre Nachricht wird nach meiner R�ckkehr beantwortet.
Wenden Sie sich in dringenden F�llen an den DBL IT-Support: +49 911 965858
777
Meine Vertretung �bernimmt Herr Welscher.



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[owncloud/ios] Mobile Device Management and OwnCloud App (#748)" gesendet
am 24.08.2016 13:59:46.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.

**Comment by nasli** [comment]
vikDex I removed your automatically mail responds.
Waiting for your feedback, thanks

**Comment by VikDex** [comment]
Ich kehre zur�ck am 05.09.2016.

Ihre Nachricht wird nach meiner R�ckkehr beantwortet.
Wenden Sie sich in dringenden F�llen an den DBL IT-Support: +49 911 965858
777
Meine Vertretung �bernimmt Herr Welscher.



Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[owncloud/ios] Mobile Device Management and OwnCloud App (#748)" gesendet
am 25.08.2016 08:56:34.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.

**Comment by VikDex** [comment]
nasli, thanks for your feedback.
to answer your questions. 

How do you want to distribute the app to your users, via Ad hoc, Play Store?
-> via Apple App Store (iOS), AD-HOC installation pushed by the MDM vendor

What other special settings do you need to set up?
Additional Accounts allowed (yes / no )   -> if an additional account is not allowed, the user should not be all able to put additional credentials to it

Do you want that the user only can log in with the preconfigured username account?
yes the username should be preconfigured, but changeable if needed

The password will be enter for the user?
Usually the user puts in the password

Do you plan to configure individually for each user?
yes

this is an example of a configuration set:
com.owncloud.serverURL=https://myowncloudserver.com:443
com.owncloud.user=bill@microsoft.com
com.owncloud.pass=gates  <--------- OPTIONAL
com.owncloud.canAddAccount=false <-------- User is not able to add more Accounts to the Managed Owncloud App

**Comment by VikDex** [comment]
By the Way:
A payload is signed by the MDM server and will be sent fully encrypted to the device.
![2016-09-06 16_05_26-token_trust_2x png png-grafik 1012 x 634 pixel](https://cloud.githubusercontent.com/assets/16401611/18276681/175f9e38-744c-11e6-91be-ec3f5f316727.png)

**Comment by michaelstingl** [comment]
@VikDex Is this something where implementing http://appconfig.org/ would be useful? This is a open standard from most of the MDM vendors according to Apple specs.

**Comment by VikDex** [comment]
Hello! yes this is what i'm talking about. All big MDM vendors use this standard for configuration over the air. Best practice in the Enterprise use. I guess Owncloud is getting even more popular in big companies, when the app provides this interface.

**Comment by davivel** [comment]
If I understand correctly, the provisioning of the app will be done dynamically, right? ownBrander wouldn't be enough then.

If Appconfig allows integration with MDM vendors seems a good option to prevent that extra development is needed also in the OC server.

**Comment by VikDex** [comment]
Hello Davivel,
yes indeed.

The app gets pushed by the mdm server to the IOS device. It's called a managed app, because it's separated from the "private" apps on the ios device by default.
When I start the app, it should check for appconfig information setup by the mdm server. So it's not required to setup the host, name, etc.

this is an example of a configuration set:
com.owncloud.serverURL=https://myowncloudserver.com/owncloud:443
com.owncloud.user=bill@microsoft.com
com.owncloud.pass=gates <--------- OPTIONAL
com.owncloud.canAddAccount=false <-------- User is not able to add more Accounts to the Managed Owncloud App

this enables to configure the app automatically over the air.
in most cases the app gets pushed with servername and username und the client have to enter his password. others do it with a certificate, but it affords many work to run it smoothly.


this is  a scenario with IBM Traveler (Messaging App) and an MDM vendor MAAS360:
https://www-10.lotus.com/ldd/dominowiki.nsf/dx/Using_MaaS360_with_IBM_Verse_for_iOS_Devices

Popular MDM vendors are listed in this article:
https://www.gartner.com/doc/reprints?id=1-390IMNG&ct=160608&st=sb

**Comment by Froster** [comment]
*push same Szenario here for MDM by MobileIron, we don't really need the OwnBrander it would be more helpfull if the app could managed by our MDM itself..

**Comment by davivel** [comment]
Sure, but pretending to adapt the mobile apps to every MDM solution out there is a titanic job. Each of them has their own set of "small details" that need integration to avoid breaking the app.

**Comment by squigulum** [comment]
hi, what's the status of this issue ?
old thread, 2 years 'old' but still 'open' ? 
where is the solution ?

![image](https://user-images.githubusercontent.com/26377802/54532686-b1dde500-4988-11e9-89d1-4eb213a76703.png)

as of owncloud.com, there should be a solution ?!

Marc

**Comment by michaelstingl** [comment]
> as of owncloud.com, there should be a solution ?!

The ownCloud mobile apps can be distributed with various MDM solutions. Some of them can "wrap" the `*. IPA` or the `*.APK`, so they can apply policies to the apps.

The ownCloud team started with a new iOS app from scratch, that will be available in the public app store soon. You already can join the TestFlight beta:
https://owncloud.org/news/working-brand-new-ios-app-sdk/

The new ownCloud iOS app supports MDM configuration with [appconfig.org](https://www.appconfig.org/) from day 1:
https://github.com/owncloud/ios-app/tree/master/MDM/AppConfig

Here you can find an easy `specfile.xml`:
https://github.com/owncloud/ios-app/blob/master/MDM/AppConfig/minimal-specfile.xml

But there are many more parameters that can be configured:
- https://github.com/owncloud/ios-app/blob/master/MDM/AppConfig/specfile.xml
- https://github.com/owncloud/ios-app/blob/master/doc/CONFIGURATION.md
- https://github.com/owncloud/ios-sdk/blob/master/doc/CONFIGURATION.md

@squigulum What is your use case? What would you like to configure first? It would be awesome if you could help testing and provide feedback! Please open a new issue in the [new iOS GitHub.com repository](https://github.com/owncloud/ios-app/) with the details, and we'll continue there:
https://github.com/owncloud/ios-app/issues/new
