### ISSUE TITLE
file just uploaded from device is not available offline

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#75]
A photo I just uploaded from my device does not have the downloaded badge indicator. When I open it, it needs to load first.

Since I just uploaded it from this device, it should just be available offline, and have the downloaded badge.

**Comment by doomi** [comment]
As this is the behavior now, I suggest to close this issue.

**Comment by michaelstingl** [comment]
This got implemented in the successor of this ownCloud app. You can test with the TestFlight beta.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
