### ISSUE TITLE
Login view in SAML freezes after expiration if there are av. offline files

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#757]
### Steps to reproduce
1. In a SAML server, set a file as av. offline
2. Wait until session expires. 
3. Input credentials
### Expected behaviour

After input credentials, the files view is displayed.

### Actual behaviour

Login view freezes. The app has to be killed and opened again to start working

### Server configuration

{"installed":true,"maintenance":false,"version":"9.1.4.1","versionstring":"9.1.4 RC2","edition":"Enterprise"}

### Client

iPad v9
iPhone 6 v10

- [x] [GIT] Create branch login_freeze_after_expire_with_available_offline
- [x] [DEV] Debug to discover what it is happening
- [x] [DEV] Resolve the bug
- [X] [QA] Design test plan @jesmrec 
- [X] [QA] Validate test plan @jesmrec
- [x] [DEV] Code Review

PR:https://github.com/owncloud/ios/pull/850

**Comment by nasli** [comment]
Hardly to reproduce, we will check it @jesmrec

**Comment by jesmrec** [comment]
I was not able again to reproduce it. Closing.

**Comment by jesmrec** [comment]
I reopen this issue, so i can reproduce it with some steps. I set them in the first message.

**Comment by jesmrec** [comment]
Approved 

CC @nasli
