### ISSUE TITLE
Uploaded Videos have no sound

### ISSUE THREAD

**Issue by payam-huemer** [owncloud/ios#759]
### Steps to reproduce
1. Upload a video (I only tried with mp4 and mov format)
2. Download the video and play

### Expected behaviour
Video should be played within the App with sound

### Actual behaviour
Video plays, but there is no sound

### Client
**iOS version:**
9.3.4

**ownCloud app version:**
Branch release3.5.0 commit 2ea08da33e815676faf31b9fb79f27ed5d66ed92

**Device model:**
Iphone 5

Can someone reproduce this or am I doing a mistake?

**Comment by nasli** [comment]
Hi @payam-huemer,

video sound should work, please make sure you don't have your device in a silent mode with the lateral button.

**Comment by vistarikov** [comment]
I had the same problem. iPad 4 iOS 10.2.1, iPad mini 2 iOS 9.3.5. 
Switching off the silent mode solved the issue. Thanks.
