### ISSUE TITLE
offline behavior

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#76]
Currently it’s not possible to upload anything when you’re offline. Also you permanently get the modal telling you you’re offline.

The modal should only come once per »session« (per opening the app, or once after coming from sleep). But not on every navigation inside the app.

Uploading and creating folders should work offline, and be queued for sync as soon as there’s connection again.

Same on Android https://github.com/owncloud/android/issues/162

**Comment by michaelstingl** [comment]
> Uploading and creating folders should work offline, and be queued for sync as soon as there’s connection again.

This got implemented in the successor of this ownCloud app. You can test with the TestFlight beta.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
