### ISSUE TITLE
As an user I want to be able to select if I want to instant uploads videos or images

### ISSUE THREAD

**Issue by nasli** [owncloud/ios#762]
AC:

Within 3.5.0 instant uploads for video was supported. 
First to start with wifi only option let's give the user the chance to select what they want to save automatically.

Add settings options to separate instant uploads of images and videos.
The user will have the option to only upload images, videos or images & videos
Background instant uploads will work for the selected options

Android settings state: https://github.com/owncloud/ios/issues/352#issuecomment-218702095

@Jon-Schneider would you like to help with this one?

**Comment by Jon-Schneider** [comment]
It wouldn't be that hard to implement separate video and image uploading, I can do that fairly easily. However, I think we should wait until an option for wifi-only Instant Upload (blocked by #753) is implemented before doing so.

**Comment by nasli** [comment]
Thank you @Jon-Schneider, 
Due the refactor of uploads, instant video uploads for video was added within 3.5.0. 
Since there are some user asking for a long time for this feature, and since it is already released, I would suggest to start with the quick one and at least let the user decide to uploads video or not

**Comment by Jon-Schneider** [comment]
Wait, it's in via bug? Crap. I'll add a switch for both.

**Comment by nasli** [comment]
Great!!  :wink:

**Comment by rperezb** [comment]
QA in progress, test plan available on https://github.com/owncloud/QA/issues/321

**Comment by jesmrec** [comment]
Merged. Closing...

**Comment by rperezb** [comment]
@carlaschroder new feature on the iOS app!

**Comment by settermjd** [comment]
Hey folks. I installed 3.5.2 (21dfb82) and there's no wifi-only option for either photos or videos. Is that to be expected?

**Comment by jesmrec** [comment]
@settermjd https://github.com/owncloud/platform/issues/53

P3

**Comment by settermjd** [comment]
No wifi-only option available, as per owncloud/ios/issues/352.
