### ISSUE TITLE
ownCloud Client 3.5.1. crashes when tapping "Settings"

### ISSUE THREAD

**Issue by workflowsguy** [owncloud/ios#789]
The client will reproducibly crash when tapping "Settings" (="gear symbol").

iOS 9.3.5

**Comment by jesmrec** [comment]
Could you tell us the steps to reproduce? 

Besides of that,  if you give us further info:

- Settings (including number of accounts)
- Install from scratch or upgrade (from which version)?
- Device you use

i can not reproduce the crash with a 9.3.5

**Comment by workflowsguy** [comment]
Steps to reproduce:
1. Open ownCloud client by tapping it's icon
2. tap on "Einstellungen" (="Settings") in main screen

Settings:
As I can not access them, I cannot give any more details than that I have one account pointing to the ownCloud installation on my NAS.

Installation type: upgrade from version 3.5.0
Device type: iPad 2

I have attached the crash log if that is of any help to you.

Thanks!
[Owncloud iOs Client-2016-09-30-115303.crash.txt](https://github.com/owncloud/ios/files/502641/Owncloud.iOs.Client-2016-09-30-115303.crash.txt)

**Comment by nasli** [comment]
@workflowsguy how you did the upgrade? through App Store or compiling with Xcode?

**Comment by workflowsguy** [comment]
I upgraded through App Store.

**Comment by jesmrec** [comment]
Checked with iPad Pro v9.3 and no crash by tapping on Settings. Not easy to reproduce.

**Comment by nasli** [comment]
@workflowsguy try to send us more logs following next steps:
1-connect your device to your laptop
2-open Devices Window
3-open owncloud app and go to setting
4-copy the logs generated in this console window

Thanks

**Comment by workflowsguy** [comment]
I have deleted and reinstalled ownCloud (through the App Store). The problem is gone now.

Thanks!

**Comment by nasli** [comment]
You are wellcome @workflowsguy ! Thanks for the updated.

**Comment by blacking** [comment]
Hello i have the same problem here. After recompiled the project (branch master) the build works fine, but when tapping 'Settings' icon the program crash.

Any help is appreciated
Marco

**Comment by jesmrec** [comment]
@blacking 

which device, iOS version, app version are you using?

**Comment by blacking** [comment]
Hello, sorry for delay

testing both with simulator and iphone5(c)
Xcode 8.2.1 (8C.1002)
app versione is 3.5.2
git a29fd2e (master)

I suppose the problem is associated with the provisioning profile, possible? If compile the original version for local (simulator) keeping the bad team reference of owncloud the project run and setting not crash when tapping.
My bundle identifier is com.example.owncloud.ios

**Comment by nasli** [comment]
Hi @blacking , thanks for your input, your issue looks different, it seems an issue to access to your accounts users, please take a look of this issue https://github.com/owncloud/ios/issues/462.

Check carefully all extension to update all your provisioning profiles properly.

Please if needed open a new issue with more logs details https://github.com/owncloud/ios/issues/789#issuecomment-252596724  and git command used to clone the repository , thanks!

**Comment by blacking** [comment]
Hello @nasli, thanks for your reply.

_Check carefully all extensions to update all your provisioning profiles and group name properly_.

I read your note but, can you explain with more detail as create and configure this files into **General** pane and **Capabilities** pane 

many thanks

**Comment by nasli** [comment]
This may help you https://github.com/owncloud/ios/issues/462#issuecomment-137715895

**Comment by nasli** [comment]
https://github.com/owncloud/ios/blob/master/SETUP.md
https://github.com/owncloud/ios/blob/master/OCC2015_iOS_workshop.pdf
