### ISSUE TITLE
Instant Upload improvements (post #782)

### ISSUE THREAD

**Issue by mmattel** [owncloud/ios#805]
### Tell us what could be improved:
After #782 (Instant Upload now offers selective upload of Videos and Images) is now merged, I propose the following suggestions:

- If there are multiple accounts present, the account for the instant upload should be selectable. Else things get distributed around.
- Having the above, it would be great if the account selected will not explicitly need activation (aka switched to) to instant upload.
- A switch to upload depending on 3G/WLAN access. (This is necessary for roaming when using 3G ect)

Q: is it possible to have another target for instant uploading? The default home location is often not useful. An external definable mount (folder) would be great.

**Comment by Jon-Schneider** [comment]
I know that Wifi-only Instant Upload is coming, but the upload system needs modified to allow some sort of wifi-only upload mode, or to all the Instant Upload manager to queue/cancel/resume uploads so it can upload based on the wifi status.

**Comment by mmattel** [comment]
@nasli, because I do a lot of travelling outside my home country, the rollout of the release containing #782 would be really helpful to turn instant uploding off avoiding roaming - up to the point when my suggestions above get coded and rolled out, then I turn it on again :smile: 

@nasli @Jon-Schneider can you tell me if my question above is possible and if how, or is this another feature to be implemented?

**Comment by mmattel** [comment]
Path for Instant Upload: from that what I have read in the code, the path is currently hardcoded to the users home/Instant Upload.

Feature Request:
- Make the Instant Upload Path selectable with a default fallback

**Comment by nasli** [comment]
@mmattel , Yes, these are new improvements to the instant uploads feature.

For better tracking:

>If there are multiple accounts present, the account for the instant upload should be selectable. Else things get distributed around.
Having the above, it would be great if the account selected will not explicitly need activation (aka switched to) to instant upload.
Q: is it possible to have another target for instant uploading? The default home location is often not useful. An external definable mount (folder) would be great.

 Let's keep tracking here #453 

>A switch to upload depending on 3G/WLAN access. (This is necessary for roaming when using 3G ect)

 Let's keep tracking here #352
