### ISSUE TITLE
As an iOS user I would like to decide if the "Available offline" feature will use my mobile data

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#808]
**Available offline** is a awesome feature, but it could consume a big amount of mobile data. At the moment a user decides to make a folder "Available offline", he don't really know the amount of data this will use. Perhaps downloading starts with WiFi connection, but continues later with mobile data. Or other users are adding more data to this "shared" folders, and they all will download when the user will open the app the next time.

A setting would be useful, which let users configure if "Available offline" downloads shall use mobile data?

**Comment by ChrisEdS** [comment]
Customers also frequently ask for this feature. Would be nice to integrate that.

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/ios/issues/465
