### ISSUE TITLE
splash screen image

### ISSUE THREAD

**Issue by faustperic** [owncloud/ios#809]
Is this possible to change splash screen image? I deleted previous splash image and added mine splash image, but when I start owncloud app the first was shown owncloud splash image (own cloud logo) and after that my splash image? I also checked Launch screen.xib file and there is just mine splash screen image, but app still showing first owncloud image and mine after that on startup of app.

Thanks in advance.

**Comment by f4111222** [comment]
Hey, @faustperic  ,
You can try to delete the owncloud app in your simulator or iphone, and close the Xcode and restart again, also remember to "Clean" your project before you build.  After these steps it should be ok for showing only your splash image. Hope it will help :)

**Comment by nasli** [comment]
@faustperic thanks for following up!

@faustperic If need more help reopen it please, thanks!
