### ISSUE TITLE
Some UI improvements

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#817]
Gathering some tiny things related with UI of the app:

- In iPads, the app icon does not fit with the frame width:

https://github.com/owncloud/ios/issues/755#issuecomment-247972326

- In iOS 10, browsing back in folder structure, the upper marker to the parent folder is darker as in previous versions, so it is less visible

https://github.com/owncloud/ios/issues/760#issuecomment-248682039

- In login view, the "Add" button background color should be the same as the icon color and the upper bar color (dark blue).

**Comment by nasli** [comment]
Closed for split each improvement in different issues:
https://github.com/owncloud/ios/issues/868
https://github.com/owncloud/ios/issues/871
https://github.com/owncloud/ios/issues/870
