### ISSUE TITLE
User '(null)' is used for login instead of the correct one

### ISSUE THREAD

**Issue by AndreaGiardini** [owncloud/ios#824]
### Steps to reproduce
1. Download / Upload a file (not all the times)
2.
3.

### Expected behaviour
Tell us what should happen
The file should be downloaded

### Actual behaviour
Tell us what happens instead
The file is downloaded after several tries, causing failed login attempts with username '(null)'

### Server configuration
**Web server:**
Nginx 1.6.2

**Database:**
mysql  Ver 14.14 Distrib 5.5.53

**PHP version:**
PHP 5.6.29-0+deb8u1

### Client
**iOS version:**
10.2

**ownCloud app version:**
3.5.2

**Device model:**
iPad Mini 2

#### Web server error log
```
not relevant
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"5VeFW1C1AvgUIwB6wZHL","remoteAddr":"X.X.X.X","app":"core",
"message":"Login failed: '(null)' (Remote IP: 'X.X.X.X')","level":2,
"time":"2016-12-24T14:59:49+01:00","method":"GET",
"url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares?path=&subfiles=true","user":"--"}
{"reqId":"IpZ8eYUpfMqGA5UYDxy4","remoteAddr":"X.X.X.X","app":"core",
"message":"Login failed: '(null)' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-12-24T14:59:50+01:00","method":"PROPFIND",
"url":"\/remote.php\/webdav\/","user":"--"}
{"reqId":"oswk\/OENMPtZGMzVqMAY","remoteAddr":"X.X.X.X","app":"core",
"message":"Login failed: '(null)' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-12-24T14:59:50+01:00","method":"GET",
"url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares?path=&subfiles=true","user":"--"}
{"reqId":"mwJb7WZPnMpGzmKwQWWL","remoteAddr":"X.X.X.X","app":"core",
"message":"Login failed: '(null)' (Remote IP: 'X.X.X.X')","level":2,"time":"2016-12-24T14:59:50+01:00","method":"GET",
"url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares","user":"--"}
```
![img_20170108_231914](https://cloud.githubusercontent.com/assets/3543138/21754145/8254ef12-d5fa-11e6-8052-2f572a59e2eb.jpg)

**Comment by fcturner** [comment]
From core issue:

> @PVince81
> Hmm, maybe the ios app is trying to authenticate using the OCS endpoints and it somehow fails ?

**Comment by peterforeman** [comment]
I have the same issue with the iOS app and ownCloud, but only with "Instant Upload". It keeps failing when used in background. Opening the app gives the same (null) messages and "Failed". Pressing the item brings me to the login screen where I simply press "login" and then it works, until next time I want to auto-add photos.

**Comment by nasli** [comment]
Thanks for your update @peterforeman 

This is always failing for you? 
Could you provide us more info:
model device
iOs version
OC version
server version

If you could provide us a test account to apps@owncloud.com that will help too. 

Thanks!

**Comment by peterforeman** [comment]
Oops - I just saw this question now ...... sorry! For me this is not happening anymore, can be closed I guess.
