### ISSUE TITLE
[Feature request] Add video streaming for mp4

### ISSUE THREAD

**Issue by maxxmka** [owncloud/ios#841]
Client

iOS version: 10.1.x and above

ownCloud app version: 9.x.x

Device model: iPad and iPhone

Tell us what could be improved:

Add mp4 video streaming, currently it takes ages (and a lot of phone storage) to download HD video to play it.

**Comment by jesmrec** [comment]
@maxxmka the streaming feature is scheduled and will start to be developed in short term. You can track it in the following issue: https://github.com/owncloud/ios/issues/787

Closing this, duplicated.
