### ISSUE TITLE
Support for client certificates 

### ISSUE THREAD

**Issue by luozengbin** [owncloud/ios#842]
for security reason owncloud app should support client certificates as other apps like caldav sync and carddav sync already do.
This topic is also mentioned in nextcloud.
https://github.com/nextcloud/android/issues/603

**Comment by michaelstingl** [comment]
@luozengbin Could you provide some background? Is https://github.com/owncloud/android/issues/163 the same for the Android platform?

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/ios/issues/222
