### ISSUE TITLE
Feature-request: detecting and eliminating duplicate files

### ISSUE THREAD

**Issue by UnitedMarsupials** [owncloud/ios#847]
Accidentally I have uploaded a large video _again_ -- after already moving the earlier-uploaded version into a subfolder. ownCloud did not notice and the two files on the filesystem are independent.

On multi-user systems (which mine is not) this is like to be an ever pronounced problem, because people share files with each other and then move/copy them around.

Although one can use [ZFS' deduplication feature](https://blogs.oracle.com/bonwick/entry/zfs_dedup) to eliminate this problem on the filesystem level, ownCloud can, probably, do it itself. Does it not already maintain checksums of the files uploaded?

**Comment by michaelstingl** [comment]
@UnitedMarsupials What I understand, this should be solved on the server side. That's why I will close this issue in the ownCloud iOS repository. I would also recommend to use https://central.owncloud.org/ for discussing such concepts.
