### ISSUE TITLE
After viewing a video in browser, the list of files resets to the beginning

### ISSUE THREAD

**Issue by UnitedMarsupials** [owncloud/ios#849]
### Steps to reproduce
1. Open an oC folder with lots of media files.
2. Scroll down to the bottom half of the list.
3. Click on a video-file to view it.
4. Close the video.

### Expected behaviour
The list of files should remain just as it was before you clicked on the video.

### Actual behaviour
The list of files jumps back all the way up to the beginning, making it difficult to resume one's work.

### Client
I observed this with Firefox. Maybe, other browsers don't do that...

**Comment by michaelstingl** [comment]
Unrelated to the ownCloud iOS app, possible duplicate for https://github.com/owncloud/core/issues/26318.
