### ISSUE TITLE
Client throws error: No connection to server. Server in maintanance mode.

### ISSUE THREAD

**Issue by IngoEF** [owncloud/ios#860]
The IOS client doesn't work in our environment while PC and Android-clients are working properly.
When opening the client and typing in server name the client refuses to work and throws the error shown in the title.
We are using LDAP for authentication.
The user "reddoxx maildepot" shown in the owncloud-log is a contact object in our active directory.
Such sort of objects shouldn't have any relevance for authentication at all.
Even after deleting or moving the object from AD the error remains the same. Where is the wrong information pulled from?

How can I debug requests/responses in this case?

### Steps to reproduce
1. invoke newest owncloud IOS client on iPad
2. type in server name
3. client immediatly throws the error message shown in the title (I don't see it in english, my devices use german language)

### Expected behaviour
No error message but establish connection to server

### Actual behaviour
client refuses to connect and says something like "authentication to server not possible" (translated from german language).

### Server configuration
**Web server: Apache 2.4.6
**Database:mariadb 5.5.52
**PHP version:7.0.16
**ownCloud version:9.1.4.2
**Storage backend (external storage): none

### Client
**iOS version:10.1.1
**ownCloud app version:3.5.3
**Device model: iPad / iPhone

#### Web server error log
xx.xx.xx.xx - "" [22/Mar/2017:12:55:26 +0100] "HEAD /remote.php/webdav/ HTTP/1.1" 503 -

#### ownCloud log (data/owncloud.log)
{"reqId":"WNJmLl3X4oF@AdkgomP9XwAAAAQ","remoteAddr":"xx.xx.xx.xx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 InvalidArgumentException: uid for 'cn=reddoxx maildepot,cn=users,dc=mydom,dc=de' must not be an empty string!\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(163): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":153,\"User\":false}","level":4,"time":"2017-03-22T12:55:26+01:00","method":"HEAD","url":"\/remote.php\/webdav\/","user":"--"}

### Tell us what could be improved:
it seems to me as if the authentication procedure validates too many AD objects.

**Comment by IngoEF** [comment]
May I ask for some meanings from the specialists?

**Comment by jesmrec** [comment]
@IngoEF could you tell us your LDAP configuration? which attribute uses the server to authenticate the LDAP users? if you do not want to post in here, you can address it yo apps@owncloud.com.

for the moment, i can not reproduce this.

**Comment by IngoEF** [comment]
Seems to have reasons in LDAP.

**Comment by nasli** [comment]
Thanks for the update @IngoEF !

**Comment by weckmann** [comment]
we do have the same problem, running a 9.1.5 installation connected with LDAP...

@IngoEF  can you please provide some more details how you solved the problem?

Thanks!

**Comment by IngoEF** [comment]
Hi,

sorry for my late answer.
In my case there was a config error hidden in the owncloud group setup which only influenced the IOS-owncloud-client.
After rebuilding the whole LDAP configuration in owncloud using the right group for authentication, the error went away.
My experience was best with the defaults offered by owncloud.

- IngoEF

**Comment by andyoakeley** [comment]
Having exactly the same issue. I have blown the LDAP configuration away and reset it more times than I can count. Somehow it worked once or twice, but then failed again.

**Comment by andyoakeley** [comment]
figured it out.
triple checked the LDAP settings
Cleared the username-LDAP mapping in expert ldap settings

**Comment by nasli** [comment]
Thanks for the update @IngoEF , @andyoakeley
