### ISSUE TITLE
[UI] Change symbol of 'Shared links' section

### ISSUE THREAD

**Issue by pmaier1** [owncloud/ios#862]
Please exchange the current 'general' sharing symbol of the 'Shared links' section with the link share symbol to arrive at better consistency

![image006](https://cloud.githubusercontent.com/assets/21193500/24263164/addf9bd2-0ffc-11e7-9148-c968701ef385.jpg)

=> ![image005](https://cloud.githubusercontent.com/assets/21193500/24263043/43d90674-0ffc-11e7-85ce-bc2d07c12214.png)

**Comment by jesmrec** [comment]
@pmaier1 we will include it in the following version.

**Comment by jesmrec** [comment]
The wording should be changed from "Shared links" to "Public links"

**Comment by pmaier1** [comment]
> The wording should be changed from "Shared links" to "Public links"

Yes, thanks!

**Comment by davivel** [comment]
Directly in release_3.6.0 branch; on it.

**Comment by jesmrec** [comment]
Done and approved. It will be available within next version.
