### ISSUE TITLE
App icon in iPads does not fit the screen width

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#868]
In iPads, the app icon does not fit with the frame width:

![a6280434-7e6f-11e6-8d3c-f85df20f918b](https://cloud.githubusercontent.com/assets/14894746/24460413/86c62394-149e-11e7-913a-ad7ed6adff8c.png)

**Comment by MathPlayer** [comment]
This appears to be fixed

**Comment by jesmrec** [comment]
which device? unfortunately, i can still reproduce this bug

**Comment by MathPlayer** [comment]
You're right, I was checking with a device with a bigger resolution
