### ISSUE TITLE
Different background color login button

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#870]
In login view, the "Log in" button background color should be the same as the icon color 

![screen shot 2017-03-29 at 16 43 31](https://cloud.githubusercontent.com/assets/14894746/24460555/e9bb50c8-149e-11e7-8388-9cc1a45be3f8.png)

having the same colours makes the app a better appearance

**Comment by nasli** [comment]
Fixed https://github.com/owncloud/ios/pull/876
