### ISSUE TITLE
[UX] Make login page more intuitive

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#877]
I found some minor glitches on the login page of the 3.5.3 ownCloud iOS app:

![ios login button](https://cloud.githubusercontent.com/assets/214010/25022469/496d8d30-2096-11e7-9d5d-46bfdbd2f540.gif)

### 1) "Done" Button?

The 3 input fields on the login page feels like a form, and a "`Next`" button to navigate to the next input field would be more convenient.

![ios login button - 1](https://cloud.githubusercontent.com/assets/214010/25023734/51d0384c-209b-11e7-9dea-6dcdcbc46736.png)

### 2) Field Focus

A click on the "`Username`" field should place the cursor in the field.

![ios login button - 2](https://cloud.githubusercontent.com/assets/214010/25023747/5e2af30c-209b-11e7-8028-03a72c531c35.png)

### 3) Scroll Down?

I moved the page upwards 5 Seconds ago, why does it scroll down now?

### 4) Button Inactive

After entering the first character in the "`Password`" field, the "`Log in`" button should be activated and clickable.

![ios login button - 4](https://cloud.githubusercontent.com/assets/214010/25023754/64d6ce88-209b-11e7-9ca4-a34978a6efe4.png)

### 5) Click?

A click to activate the "`Log in`" button shouldn't be necessary. It should immediately send the login request to the ownCloud server.

### 6) Click Again?

… wouldn't be necessary.

![ios login button - 6](https://cloud.githubusercontent.com/assets/214010/25023764/6a682720-209b-11e7-812f-053c121c9406.png)

Tested on iPhone 5s running iOS 10.3.1.

00007354

**Comment by mmattel** [comment]
:+1: really needs improvment

**Comment by nasli** [comment]
All the login view is going to be refactored in next versions. We keep in mind for the new login view thanks @michaelstingl !

**Comment by nasli** [comment]
Fixed via https://github.com/owncloud/ios/pull/919
