### ISSUE TITLE
As an ownCloud iOS user, I want better upload feedback

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#88]
Currently, uploading a bunch of files on iOS will give me feedback in form of the blocking »Loading« overlay and the current folder behind that. When the loading overlay vanishes, it’s very probable that my files are out of view. And even when scrolling to check them out, I probably won’t remember.

To fix that I see 2 necessary things:
1. Non-blocking loading message: Instead of the overlay, the entries should be directly inserted into their place in the list, with a loading bar as second line.
2. Slight highlight: Newly added files should be slightly highlighted. Like a very slight yellow background for the row.

What do you think?

**Comment by enoch85** [comment]
3. Show upload progress when pictures are taken with the camera - Instant Upload.

**Comment by nasli** [comment]
@enoch85, if you enter on the app, when new photos are being uploaded you can see their progress on the uploads view

**Comment by enoch85** [comment]
@nasli Thanks for the info!

What I meant was a progress bar in the top-background, like on the Android app.

**Comment by nasli** [comment]
@enoch85 iOS app does not work the same way on this case

**Comment by michaelstingl** [comment]
The ownCloud iOS team started to write a new iOS app from scratch. This version is deprecated and won't see major improvements.

Here you can find more information:
https://owncloud.org/news/working-brand-new-ios-app-sdk/
(Link to free TestFlight beta in the article)

Roadmap of new iOS app:
https://github.com/owncloud/ios-app/issues/94
