### ISSUE TITLE
Default export folder

### ISSUE THREAD

**Issue by patoperro** [owncloud/ios#881]
Feature request:

Our university uses OwnCloud and I frequently make use of it on my iPad to mark student's
papers. When I am done annotating them I export them to the OwnCloud app, where I
am then required to select where to put them. 

This destination defaults to the root OwnCloud directory, but 9 times out of 10 I am saving files
to the same location as the last file. Thus, I waste a lot of time performing tedious,
repetitive actions (drilling down 7 or 8 levels in my file tree each time).

Perhaps you could offer users the choice of saving to the most recently-used directory or
the OwnCloud base directory in preferences. If not, I'd prefer the most recent
directory by default, navigating to a new folder for that 1 time out of 10.

Regards,
Pato

**Comment by michaelstingl** [comment]
@patoperro Which app are you using to annotate? I use PDF Expert, and it allows me to access my ownCloud files directly using the Locations feature.

**Comment by patoperro** [comment]
I also use PDF Expert, but am not sure what you mean by Locations? In the Network locations settings I don't see a way of adding an OwnCloud account. 

![img_0944](https://cloud.githubusercontent.com/assets/6922244/25191137/f472f7d2-252e-11e7-8672-09d0593ef888.PNG)

Could you be a bit more specific?

Thanks,
Pato

**Comment by nasli** [comment]
If I understand correctly @patoperro, what you suggest it's to uploads items to the latest folder used to upload.

You upload to /A/B/C and next time you want the folder C be predefined as a destination folder, right?

This is in our backlog and already supported for Android.

Please, keep tracking here https://github.com/owncloud/ios/issues/800

Closed as duplicated, if not please reopen with more details thanks!

**Comment by michaelstingl** [comment]
You need to add ownCloud as "Location":

<img width="1158" alt="napkin 19 04 17 6 44 41 pm" src="https://cloud.githubusercontent.com/assets/214010/25191624/84d295c0-2530-11e7-8632-7d5a9d5918da.png">

From this, you can open the document from any subfolder, and when you save it, it saves to the same location.
