### ISSUE TITLE
Custom groups are shown with prefix "customgroup_"

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#883]
#Custom groups created in server side v10 shows a "customgroup_" prefix:

![screen shot 2017-04-27 at 12 26 51](https://cloud.githubusercontent.com/assets/14894746/25479357/d5d99134-2b44-11e7-9830-a7d2df5b3885.png)

the display name does not contain the prefix, and should be displayed instead of the group name

`<share_with>customgroup_groupchen</share_with>
 <share_with_displayname>groupchen</share_with_displayname>`

CC @nasli

**Comment by davivel** [comment]
Ready to test in release_3.6.0 branch.

**Comment by jesmrec** [comment]
Fixed. Available in 3.6.0
