### ISSUE TITLE
Switching account makes the app crash

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#884]
### Steps to reproduce
1. Add an account
2. Add another account
3. In settings, select the second account and tap on "Files". 
4. Tap on "Settings" and select the first account.
5. Tap on "Files"

### Expected behaviour
Files view of the first account displayed

### Current behaviour
App crashes

iOS 9 and 10.

**Comment by jesmrec** [comment]
No, this problem is in the latest versions also.

**Comment by davivel** [comment]
After the crash and reopening the app, is everything OK?

**Comment by jesmrec** [comment]
yes, all ok.

**Comment by jesmrec** [comment]
Fixed in 3.7.0
