### ISSUE TITLE
Write-only share link for folders

### ISSUE THREAD

**Issue by davivel** [owncloud/ios#895]
AC:
 - [x] rename "allow uploads" option in public shares of folders as "allow editing" 
 - [x] add checkbox "show file listing" checked by default if '"allow editing" is checked 
 - [x] Disable checkbox if "allow editing" is unchecked
- [x] Show option only if capability 'supports_upload_only' is set (OC 10.0.1) 
- [X] Create share in server according to new show file listing switch state
- [x] Update share in server according to new show file listing switch state
- [x] Clean up
- [x] Design test plan @jesmrec
- [x] Validate test plan @jesmrec

PR: https://github.com/owncloud/ios/pull/916
Library PR: https://github.com/owncloud/ios-library/pull/158

**Comment by nasli** [comment]
Related permissions in core https://github.com/owncloud/core/blob/7b7dfbcaf7360c88125d6ce5365146623d6c7195/apps/files_sharing/lib/API/Share20OCS.php#L361
