### ISSUE TITLE
Private link

### ISSUE THREAD

**Issue by davivel** [owncloud/ios#896]
Add 'link' icon to share view, next to the right border of the header (with file thumbnail and name), to copy to clipboard or share with other apps a permanent link to the file that can be shared with other users in the server.

On tap, show list of apps to share (including clipboard), as with public links

Related: owncloud/core#11732, owncloud/enterprise#2015, https://github.com/owncloud/android/issues/1970

_____

BUGS & IMPROVEMENTS

- [X] (1) Crash when tapping on private link on iPad https://github.com/owncloud/ios/issues/896#issuecomment-307017960 [FIXED] @nasli
- [X] (2) Long file names overlaps on the private link icon https://github.com/owncloud/ios/issues/896#issuecomment-307065481 [FIXED] @nasli

**Comment by michaelstingl** [comment]
Name should be "private link" according to @pmaier1 in https://github.com/owncloud/documentation/issues/2986

**Comment by jesmrec** [comment]
### (1) Bug

In an iPad, tap on private link of a file or a folder

Current: Crash
Expected: Dialog to get the link

Tested with iPad mini iOS 10.1.1

@nasli

**Comment by jesmrec** [comment]
### (2) Bug

1. Set a long file name without blanks
2. Open share view

Current: In share view, the long name overlaps on the private link icon
Expected: Private link icon is not overlapped by anything

Tested with iPhone 6S Plus v9.3.2

**Comment by nasli** [comment]
This https://github.com/owncloud/ios/issues/896#issuecomment-307017960 also affect multiple share links on ipad with version 10. First approach fixed too.

**Comment by jesmrec** [comment]
Approved.
