### ISSUE TITLE
OCCapabilities.h file not found, even when following the SETUP.md file

### ISSUE THREAD

**Issue by FeliceMente** [owncloud/ios#913]
Hi. I'm trying to build ownCloud iOS after downloading ios zip (version 3.6.2) and ios-library zip (2.1.0) and followed the procedure using sub-projects (import the ios-library project, add to the targets, add link binary with libraries, leave the "-ObjC" flag (not "-Obj-C") and finally add the path to library headers) but always got these two messages:
- [...]/UserDto.h:16:9: 'OCCapabilities.h' file not found
- Failed to import bridging header '[...]/ios-version_3.6.2/Owncloud iOs Client/OCExtensions-Bridging-Header.h'
I also whatched this issue, without success: https://github.com/owncloud/ios/issues/653

PS. The folders for the ios client and the ios library are on the Desktop.

Thanx

**Comment by nasli** [comment]
Hi @FeliceMente , please try to clone and init the library following next commands:

```
git clone git@github.com:owncloud/ios.git
git submodule init
git submodule update
```

**Comment by FeliceMente** [comment]
Thanx a lot. It was actually much easier than I thought, both with git cloning and directly using zip files :-P

**Comment by nasli** [comment]
You are welcome!
