### ISSUE TITLE
Forbidden reshare not reflected in the UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#915]
I have disabled resharing in the oC server settings, but if I create a new share in the iOS UI, it still shows the option "Can share". In the web UI or desktop UI this option isn't shown in the same case.

<img width="726" alt="oc_sharing" src="https://user-images.githubusercontent.com/214010/27550141-dd8e5872-5a9e-11e7-8987-e0b73055f8b6.png">

![2017-06-26_18_25_09](https://user-images.githubusercontent.com/214010/27550140-dd7bb1e0-5a9e-11e7-86d5-8d54b864ac09.png)

### Steps to reproduce
1. Disable "Allow reshare" in Admin settings
2. Create share in iOS app

### Expected behaviour
"Can share" should be hidden if resharing has been disabled

### Actual behaviour
"Can share" is visible

### Server configuration

**ownCloud version:**
9.1.6, 10.0.2

### Client
**iOS version:**
10.3.2

**ownCloud app version:**
3.6.2

**Device model:**
iPhone 7 Plus

00007837

Sibling: https://github.com/owncloud/android/issues/2004

**Comment by nasli** [comment]
This capability is not in use on the iOS client @michaelstingl 
We should consider to include this issue too https://github.com/owncloud/ios/issues/621

**Comment by michaelstingl** [comment]
@nasli @jesmrec If ownCloud iOS app respects the capability, will it disable sharing option if I'm the recipient of the share and try to re-share?

**Comment by jesmrec** [comment]
Yes @michaelstingl 

We can get the capability:

`"resharing": false` 

and from the PROPFIND, get the 'S' permission

`<oc:permissions>SDNVCK</oc:permissions>`

if both conditions are met, we should hide the share button.

**Comment by nasli** [comment]
Yes, we could hide the share in the slider
