### ISSUE TITLE
Can't connect with iOS app to Owncloud 10

### ISSUE THREAD

**Issue by chscherrer** [owncloud/ios#918]
## If you found a bug:
--> Can't connect to owncloud server after upgrade from 9.1.5 to 10.0.2
### Steps to reproduce
Don't know whether its reproducable

### Expected behaviour
Should log in

### Actual behaviour
Doesn't log in

### Server configuration
**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** php5.6

**ownCloud version:** 10.0.2

**Storage backend (external storage):**

### Client
**iOS version:** 10.3.2

**ownCloud app version:** 3.6.2

**Device model:** iPhone 6s

#### ownCloud log (data/owncloud.log)
{"reqId":"WV6K6H8AAAEAAEmljB8AAABO","level":4,"time":"2017-07-06T19:09:28+00:00","remoteAddr":"10.0.0.13","user":"my_user","app":"webdav","method":"PROPFIND","url":"\/oc\/remote.php\/webdav\/","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT * FROM `oc_properties` WHERE `fileid` IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) AND `propertyname` in (?, ?) ORDER BY `propertyname`' with params [1152106, 1487506, 7649, 1487234, 7653, 72, 7651, 1051770, 7652, 715226, 1469155, 1152226, 1318322, 7650, \\\"{DAV:}creationdate\\\", \\\"{DAV:}displayname\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'fileid' in 'where clause'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM `...', Array)\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(190): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/CustomPropertiesBackend.php(334): OC\\\\DB\\\\Connection->executeQuery('SELECT * FROM `...', Array, Array)\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/CustomPropertiesBackend.php(139): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CustomPropertiesBackend->loadChildrenProperties(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory), Array)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/PropertyStorage\\\/Plugin.php(91): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CustomPropertiesBackend->propFind('', Object(Sabre\\\\DAV\\\\PropFind))\\n#6 [internal function]: Sabre\\\\DAV\\\\PropertyStorage\\\\Plugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1058): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#9 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(980): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#10 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server::getPropertiesIteratorForPath('', Array, 1)\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#15 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/localh...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71,\"User\":\"ch_scherrer\"}"}
{"reqId":"WV6K6H8AAAEAAEmljB8AAABO","level":3,"time":"2017-07-06T19:09:28+00:00","remoteAddr":"10.0.0.13","user":"my_user","app":"PHP","method":"PROPFIND","url":"\/oc\/remote.php\/webdav\/","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/localhost\/htdocs\/owncloud\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}

**Comment by jesmrec** [comment]
have you checked other clients or web UI? it seems to be a problem in DB

` {"Message":"An exception occurred while executing 'SELECT * FROM oc_properties WHERE fileid IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) AND propertyname in (?, ?) ORDER BY propertyname' with params [1152106, 1487506, 7649, 1487234, 7653, 72, 7651, 1051770, 7652, 715226, 1469155, 1152226, 1318322, 7650, \"{DAV:}creationdate\", \"{DAV:}displayname\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'fileid' in 'where `

we can check it if you send us a test account. You can send it to apps@owncloud.com. In this case, please point this issue in your email.

**Comment by chscherrer** [comment]
Thanks, yes you are right, its about database, not about the app. I place his in the respective forum. You might want to close this threat.

**Comment by jesmrec** [comment]
@chscherrer ok, let's close it.
