### ISSUE TITLE
[Locations] ownCloud as default ==> no other providers can be accessed

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#920]
After choosing ownCloud app as default Location to add Attachments to a new Mail, other Location providers can't be choosen.

![screenflow](https://user-images.githubusercontent.com/214010/28221360-4be4dd32-68c3-11e7-9a6e-2b11eb06ebc4.gif)

### Steps to reproduce
1. Compose new mail
2. Long press in mail body to "Add Attachment"
3. Click "More…" in the Locations list
4. Move ownCloud to the top of the list
5. Choose ownCloud

### Expected behaviour
Button "Locations" should be accessible to choose other Location providers.

### Actual behaviour
When ownCloud is selected as default, button "Locations" isn't there.

### Server configuration

**ownCloud version:**
10.0.2

### Client
**iOS version:**
10.3.2

**ownCloud app version:**
3.6.2

**Device model:**
iPad mini 2

You could argue, this a "Feature, not a bug", but blocking others isn't fair play.

@nasli Can this be fixed?

00007958

**Comment by nasli** [comment]
Yes, it is a bug and should be fixed.
 It is duplicated of https://github.com/owncloud/ios/issues/580, closed the old one for this one with detailed description

**Comment by michaelstingl** [comment]
I think is will become obsolete with the iOS 11 Files app integration…

**Comment by pablocarmu** [comment]
This is a screenshot of how you will see this screen with the files app integration in this usecase. 
![files_app_mail](https://user-images.githubusercontent.com/8929738/33319931-ccfe081a-d440-11e7-8e63-1cd5859fc4c6.PNG)

**Comment by nasli** [comment]
@michaelstingl , @pablocarmu  But, take into account that we will keep supporting iOS 10 for a while.. both extensions need to keep supporting it.
