### ISSUE TITLE
[iOS9] Multitask improved

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#924]
iOS11 will allow to use and view different tasks:

![screen shot 2017-08-03 at 09 48 25](https://user-images.githubusercontent.com/14894746/28911477-ee9f3c58-7830-11e7-8f7d-24fdf13e4e3f.png)

also is posible to set the focus in one of them:

![screen shot 2017-08-03 at 09 49 34](https://user-images.githubusercontent.com/14894746/28911521-1cafd0a8-7831-11e7-9de0-27fac6cc96e2.png)

ownCloud iOS app should be adapted to support this feature.

**Comment by michaelstingl** [comment]
Here you can test an early build of the new iOS app that supports Split View, Slide Over and Picture-in-Picture on iPads: https://testflight.apple.com/join/Oktj0iKv (open link on iOS device) – We'd love to hear your feedback!
