### ISSUE TITLE
Silently refresh OAuth2 access token if expired

### ISSUE THREAD

**Issue by davivel** [owncloud/ios#928]
Default life time of access token in the OAuth2 app for ownCloud is one hour. To prevent the need of requesting the user to log-in again each time, the app needs to use the refresh token delivered with the expired access token to get a new access token silently.

Ideally this should be done whenever a network request to the server ends with an error due to unauthorized access, if a correct access token was used in the request.

This issue is separated from #716 and #919 so that testing on those can start earlier, but a release of #919 should not be done without the implementation of this issue.

PR: #937
PR-lib: https://github.com/owncloud/ios-library/pull/162

**Comment by nasli** [comment]
Closed via https://github.com/owncloud/ios/pull/937
