### ISSUE TITLE
Can not authenticate with this server on iPad App

### ISSUE THREAD

**Issue by stmjhjf** [owncloud/ios#929]
### Steps to reproduce
1. type in the url to the owncloud instance into the ios client window
2. type in ID
3. type is PW (URL & ID, PW is correct and it works well in Safari browser on iPAD)

### Expected behaviour
I expect the iOS client will connect to the owncloud server and show appropriate screen.

### Actual behaviour
The client returns the status "Can not authenticate with this server".

### Client
**iOS version:**
iOS 10.3.3
**ownCloud app version:**
3.6.2
**Device model:**
iPad Pro 10.5

### Further Information :
When I use Safari browser on the same iPad, it works well.
But when I use ownCloud app, cannot connect to OC because of authenticate issue.
It worked well on previous ipad , but I don't know app version at that time.

**Comment by michaelstingl** [comment]
@stmjhjf Could you check your webserver access or error logs and the owncloud.log for suspicious entries at the time of the incident?

**Comment by stmjhjf** [comment]
access.log
115.91.242.69 - - [23/Aug/2017:14:40:56 +0900] "GET /status.php HTTP/2.0" 200 821 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.6.2"
115.91.242.69 - - [23/Aug/2017:14:41:27 +0900] "PROPFIND /remote.php/webdav/ HTTP/2.0" 499 0 "-" "Mozilla/5.0 (iOS) ownCloud-iOS/3.6.2"

I received above text from ownCloud admin ^^*

**Comment by nasli** [comment]
Hi @stmjhjf ,  Are you using nginx proxy? it use SAML authentication or basic? 
could you give us more details about your server? 
Thanks!

**Comment by stmjhjf** [comment]
We using the nginx and do not use special authentication settings.

Web Server:  nginx 1.10.1,2
DB: PostgreSQL 9.5.3
PHP: 5.6.23
ownCloud: 9.0.2
Storage: Local file system

**Comment by stmjhjf** [comment]
Can I receive old version of OwnCloud app ?
Current versions is 3.6.2 but I remember that OC app was not a problem with previous versions.
Please help me, I wanna use iOS app rather than a browser...

**Comment by nasli** [comment]
You can send us a test account to apps@owncloud.com, thanks @stmjhjf
