### ISSUE TITLE
[iOS11] 3.6.2 can‘t display *.HEIC images

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#933]
![6e920008-569d-4cff-9416-c047b527a4ac](https://user-images.githubusercontent.com/214010/29889108-4b17474e-8dc3-11e7-9ac9-dbdeee4723b3.png)

*.HEIC shot with iOS 11 beta camera app, uploaded from oC iOS app (Photo Albums > All Photos)

- ownCloud server 10.0.3 beta
- ownCloud iOS app 3.6.2
- IPad Pro 10.5
- iOS 11 beta (15A5368a)

**Comment by nasli** [comment]
Notice that this format can only be available for devices with Apple’s A9 processor (iPhone 6s, 6s Plus, the iPhone SE, iPhone 7) and can be disabled in Settings>Camera>Formats>Most Compatible.

**Comment by nasli** [comment]
Also make sure Settings>Camera>Formats> Automatic option is selected to transfer as jpg 
![screen shot 2017-09-12 at 15 46 03](https://user-images.githubusercontent.com/6570505/30329123-b2a47b3a-97d1-11e7-9ee2-40eb7cb0a6f9.png)

This are some workarounds meanwhile we have a better approach.

Take into account that this format are not compatible with lot of other systems yet.
Just iOS11 and macOS High Sierra(10.13).

Happens the same with new compress format for video files (HEV)

**Comment by Emil-G** [comment]
Also an issue in [Gallery](https://github.com/owncloud/gallery/issues/737) and Core (previews)

**Comment by chscherrer** [comment]
It’s not really an alternative to use technology of the last millennium - heic support would be highly appreciated by many

**Comment by michaelstingl** [comment]
Just tested the 3.8.0 on iOS 12. It can display *.HEIC and also shows thumbnails from downloaded files. The ownCloud server can't generate thumbnails from *.HEIC, so no thumbnails can be shown for remote files.

![2018-11-03 00 49 15](https://user-images.githubusercontent.com/214010/47945506-c7cf9980-df02-11e8-8eac-3612a9de25d9.jpg)
