### ISSUE TITLE
'AFURLSessionManager.h' file not found

### ISSUE THREAD

**Issue by tessus** [owncloud/ios#934]
I followed the steps described in [SETUP.md](https://github.com/owncloud/ios/blob/master/SETUP.md), but I still got this error:

```
OCURLSessionManager.h:16:9: 'AFURLSessionManager.h' file not found
```

I had the impression that after initializing and updating the submodules all dependencies should have been resolved. Is there something missing?

**Comment by tessus** [comment]
Anyone?

I mean, I can't be the only one who has this problem. If you clone the repo (+ the submodules) and try to build the project, you'll get above error.
So how can I fix this?

**Comment by nasli** [comment]
I'm sorry for the late answer, I hope you have been able to solve, if not please reply and reopen.

This issue will indicate that the OClibrary has not been setting up properly. 
Try follow next steps to init the library after you cloned the repo:

```
git submodule init
git submodule update
```
