### ISSUE TITLE
Passcode/Touch ID required twice during open

### ISSUE THREAD

**Issue by Berzerker** [owncloud/ios#939]
### Steps to reproduce
1. Enable Passcode/Touch ID
2. Close and re-open app

### Expected behaviour
Touch ID once should log into app

### Actual behaviour
After Touch ID authenticates, another passcode screen comes up, forcing user to enter passcode

### Server configuration
**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 7.0

**ownCloud version:** 10

**Storage backend (external storage):** VPS SSD

### Client
**iOS version:** iOS 11 GM

**ownCloud app version:** Latest

**Device model:** iPhone 7+

#### Web server error log
```
Probably not relevant?
```

#### ownCloud log (data/owncloud.log)
```
Also probably not relevant...
```
 
### Tell us what could be improved:

I suspect this my have something race condition issues going on, not 100% sure though.

**Comment by nasli** [comment]
Thanks for report it @Berzerker 
We are currently performance some tests over iOS11 and this was one we already noticed [here](https://github.com/owncloud/ios/issues/905#issuecomment-313678323). 
We are collecting them with label iOS11

If you find any other, please let us know, Thank you!

**Comment by jesmrec** [comment]
already approved in the PR related
