### ISSUE TITLE
Sorting on 'kind' like Mac OS

### ISSUE THREAD

**Issue by CorneelDragon** [owncloud/ios#944]
Hi there,

A colleague of mine (William van Santen from SURF) spoke on the ownCloud Conference last week with app development about sorting of files on kind and was asked to make an issue. 

Now you can sort on date and alphabet, which is great. However, on Mac OS you also have the option to sort on 'kind'. This allows you to not only quickly find files based on their extension, but it also could 'fix' this request: https://github.com/owncloud/ios/issues/481. Since Mac automatically put folders on top when sorting on 'kind' is selected. 

Let me know what you think!

**Comment by jesmrec** [comment]
tIt is interesting for these cases in which a folder contains a huge amount of files/folders. Thanks for reporting!

CC @nasli @pablocarmu @michaelstingl

**Comment by nasli** [comment]
Will be within new 3.7.4 version Thanks to @MathPlayer :)
