### ISSUE TITLE
Send a unique X-Request-ID header to allow tracing requests in apache and owncloud logs

### ISSUE THREAD

**Issue by butonic** [owncloud/ios#950]
https://github.com/owncloud/core/pull/28144 has been merged. It will use the value of a `X-Request-ID` header as the request id in log files to allow linking events on the client to events in the apache and owncloud logs.

- [ ] generate a string to use as unique id.
  - 20-200 chars
  - only `[a-zA-Z0-9-+/_=.:]` allowed
- [ ] use it in the client log
- [ ] send it as `X-Request-ID` header on every request

**Comment by michaelstingl** [comment]
Currently ownCloud iOS app don't store a log. We recommend capture the debug output while the device is connected with Xcode, but there are solutions for Windows too: http://support.blackberry.com/kb/articleDetail?articleNumber=000036986

**Comment by mmattel** [comment]
I agree with @butonic 
Yes, currently the IOS app does not have logging, but this may/will come.
As part of a preperation and harmonisation, this is useful.
Debugging via Xcode is a way, but often a differernt story when intending to track things in core related to a client access...
Adding @nasli

**Comment by nasli** [comment]
This will be great to start using within new SDK  https://github.com/owncloud/ios-sdk

**Comment by michaelstingl** [comment]
Old ownCloud iOS app is deprecated, but new ownCloud iOS app (via SDK) sends `X-Request-ID`'s with every request. (https://github.com/owncloud/ios-sdk/issues/1)
