### ISSUE TITLE
Basic auth cookie handling

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios#956]
Steps

1. In server (basic auth), create a new account
2. Upload several pics to this account in web UI
3. In device, login in the account

### Current behaviour
By checking the "Security" section of the user in webUI , we can notice something like this:

![screen shot 2017-11-13 at 12 38 08](https://user-images.githubusercontent.com/14894746/32723931-972c7ca8-c86f-11e7-81de-c82d1ebf7d97.png)

this is because some of the requests does not include in headers the cookies responsed by the server in previous requests.

Each time the server receives a requests with `Authorization` header and with no cookies, creates a new session. 

### Expected behaviour
Cookies are sent, so only a session is created for each User Agent

Testes with iPhone6Plus v10.0.1
Server 10.0.4

**Comment by nasli** [comment]
Fixed via https://github.com/owncloud/ios-library/pull/168

**Comment by jesmrec** [comment]
Fixed and approved

**Comment by jesmrec** [comment]
In basic auth, each time the app is killed and reopened, a new row is created.

**Comment by nasli** [comment]
Handling of cookies has been refactored here https://github.com/owncloud/ios/pull/962 and now the cookies also going to be stored before the app will be killed
