### ISSUE TITLE
[3.7.0] Loginscreen: Server-URL don't need auto-complete

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios#964]
![img_e0005](https://user-images.githubusercontent.com/33026403/33203441-4f9969ac-d100-11e7-8dfe-10b9c821767b.JPG)

### Steps to reproduce
1. Enter characters in server URL input field

### Expected behavior
No auto-complete and auto-correct visible
BECAUSE: With this features there are higher risk of false input

### Actual behavior
auto-complete and auto-correct visible

### Server configuration
**Web server:**
n/a
**Database:**
n/a
**PHP version:**
n/a
**ownCloud version:**
n/a
**Storage backend (external storage):**
n/a
### Client
**iOS version:**
iOS 11.1.2
**ownCloud app version:**
3.7.0 (branch: release_3.7.0 commit: [c08ff1e](https://github.com/ChrisEdS/ios/commit/c08ff1e4556108a44ebd647d8b6160b206d6a582) 
**Device model:**
iPhone 5s

**Comment by jesmrec** [comment]
Already reported in issue https://github.com/owncloud/ios/issues/923.
