### ISSUE TITLE
[3.7.0] Credential fields are hidden, by keyboard after a valid URL was entered

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios#965]
![img_0006](https://user-images.githubusercontent.com/33026403/33204691-9a417d74-d104-11e7-8832-9a581faf5314.PNG)

### Steps to reproduce
1. Type a valid URL in input field (demo.owncloud.com, basic authentication, no OAuth 2.0)
2. Scroll down and click "Connect"

### Expected behavior
The fields for credentials should be visible

### Actual behavior
Credential fields are hidden by keyboard
Scroll down to credential fields not possible

### Server configuration
**Web server:**
n/a
**Database:**
n/a
**PHP version:**
n/a
**ownCloud version:**
10.0.3.3
**Storage backend (external storage):**
n/a

### Client
**iOS version:**
iOS 11.1.2
**ownCloud app version:**
3.7.0 (branch: release_3.7.0 commit: [c08ff1e](https://github.com/ChrisEdS/ios/commit/c08ff1e4556108a44ebd647d8b6160b206d6a582))
Built with XCode 9.2 Beta
**Device model:**
iPhone 5s

### Tell us what could be improved:
In other Apps there are arrows in the bar over the keyboard to easily switch the credential fields. Would be nice to have this feature in ownCloud.

**Comment by pablocarmu** [comment]
The release branch for 3.7.0 version is being compiled and tested with Xcode 8.3.3. I created an .ipa and tried to reproduce the bug in iOS 11.0.3 and the latest iOS 10 without success. Try to compile it with Xcode 8.3.3 and see if you can reproduce it. I'm going to close this issue, if you can reproduce the bug again with Xcode 8 i'll open it again.
