### ISSUE TITLE
[3.7.0] Crash when trying to log in

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios#966]
### Steps to reproduce
1. Type a valid URL in input field (demo.owncloud.com, basic authentication, no OAuth 2.0)
2. Scroll down and click "Connect"
3. Fill in the credentials (to make this possible simply rotate the device to landscape mode)
4. Try to authenticate

### Expected behavior
App does not crash

### Actual behavior
App crashes

### Server configuration
**Web server:**
n/a
**Database:**
n/a
**PHP version:**
n/a
**ownCloud version:**
10.0.3.3
**Storage backend (external storage):**
n/a

### Client
**iOS version:**
iOS 10.1.2
**ownCloud app version:**
3.7.0 (branch: release_3.7.0 commit: [c08ff1e](https://github.com/ChrisEdS/ios/commit/c08ff1e4556108a44ebd647d8b6160b206d6a582))
**Device model:**
iPhone 5s

**Comment by jesmrec** [comment]
Not built with XCode8, with ios11_support branch not reproducible.

**Comment by TBev0** [comment]
Not sure why this is closed? Has this issue been resolved? I'm experiencing this issue too immediately after updating my app. I installed the Nextcloud app that appears to work fine though as a work around with Owncloud server.
