### ISSUE TITLE
Adapt "public link" permissions to oC server 10.0.4 UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios#967]
UI for "public link" permissions has been improved with oC server 10.0.4:
https://github.com/owncloud/core/pull/29376

![bildschirmfoto vom 2017-10-27 16-30-06](https://user-images.githubusercontent.com/12717530/32109172-3460e192-bb34-11e7-9f91-6f02710c95dc.png)

@nasli @pablocarmu What is the effort to bring this to the iOS client?

**Comment by nasli** [comment]
This should be minor @michaelstingl , instead of setting permissions by default leave the user customize it.

**Comment by jesmrec** [comment]
Done. Will be out in the following release.

**Comment by pmaier1** [comment]
Nice!
