### ISSUE TITLE
As an ownCloud iPad user, I want the sidebar to work in one consistent way

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/ios#97]
The sidebar is a bit strange currently, with different modes of working. One (the only one possible in portrait mode) is this strange long bubble, and the other one is the proper sidebar coming from the left, which is only available in landscape mode – in _addition_ to the overlap bubble.

Instead, there should only be the proper sidebar, and never the overlap bubble:
* in landscape mode, the sidebar should be toggleable. Essentially like now with the arrow. Just cut the ownCloud logo button from that landscape view and hence cut the bubble.
* in portrait mode, the sidebar is a mode and it’s either sidebar or content already. We just need to get rid of the bubble. The sidebar should come in from the left when the button is clicked, overlaying the content (but full-height, no ugly bubble), and dimming the content with a dark transparent overlay. As soon as a file is tapped, the file opens and the sidebar should vanish!

**Comment by rperezb** [comment]
Close via https://github.com/owncloud/ios/pull/360
This will be included on the version 3.4.3

**Comment by jancborchardt** [comment]
Great stuff, finally! :)
