### ISSUE TITLE
Re_design stuff

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios#971]
Had a talk with @pablocarmu yesterday about re-design ideas for the iOS app.
Without going in details too deep: @felixheidecke is currently working on a possible re-design for the ownCloud web UI based on UIKit. Maybe working together would be a good idea to form a consistent look - where possible.
Just wanted to connect the teams for possible synergies.

**Comment by nasli** [comment]
Take into account the new file list view redesign that will be available within next versions at the beginning of next year.  https://github.com/owncloud/ios/issues/927

**Comment by michaelstingl** [comment]
teams are well connected now, thanks 👍
