### ISSUE TITLE
Cannot set custom path for instance photo upload

### ISSUE THREAD

**Issue by MicNeo** [owncloud/ios#979]
I'm using ownCloud apps on Android and iOS. On Android I can set custom path for instance photo upload. I cannot do the same for iOS. It would be nice to have such option on iOS too.

**Comment by michaelstingl** [comment]
@MicNeo What do you mean with “custom path”? On iOS, filesystem is hidden from user. Please elaborate.

**Comment by nasli** [comment]
Closed as duplicated, please follow state https://github.com/owncloud/ios/issues/453 Thanks!
