### ISSUE TITLE
[iOS11] No sharing windows present

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios#980]
Steps to reproduce
1. Open ownCloud-App in iOS11
2. Go to a file (PDF as example)
3. Try to open the file in another app

![img_0007](https://user-images.githubusercontent.com/33026403/34097115-2e58425a-e3d8-11e7-8f00-b297882d43ad.jpg)

### Expected behaviour
The "sharing-window" appears

### Actual behaviour
Nothing appears

### Client
**iOS version:**
11.1.2
**ownCloud app version:**
release_3.7.0_alpha_debug
**Device model:**
iPhone 5s

**Comment by michaelstingl** [comment]
MDM?

**Comment by ChrisEdS** [comment]
The bug has nothing to do with MDM.

**Comment by nasli** [comment]
It is related to iOS11, and could be related with the changes in the open for the MDM MobileIron

**Comment by nasli** [comment]
Could be related with a changes in permissions in iOS 11, the app bundle url we share, maybe we need to use a temporal folder to share it.

**Comment by nasli** [comment]
Yes, it is related the changes for the MDM.

To support the white listed apps through MDM was replaced the UIActivityViewController with UIDocumentInteractionController, and in iOS11 is having this issue. We need to review it.

In other part of the app that we are still using the UIActivityViewController this works fine in iOS11 too. (Check the menu that appears when you share by link)

**Comment by nasli** [comment]
Since this could be tedious for the user have to kill the app to share the recent downloaded file in iOS11, until a fix to use UIDocumentInteractionController properly with iOS11, for this version is better to revert and use UIActivityViewController for iOS11.

New custom variable has been created to decided which one to use depending of the iOS version

**Comment by nasli** [comment]
PR that revert open-with mode to use the previous one with iOS11 https://github.com/owncloud/ios/pull/984
