### ISSUE TITLE
App opens and immediately closes

### ISSUE THREAD

**Issue by paraviz02** [owncloud/ios#990]
### Steps to reproduce
1.  Open up ownCloud 3.7.0 on iOS 11.2.1

### Expected behaviour
App should open up properly.

### Actual behaviour
App immediately closes.

### Server configuration
Tested on multiple server configurations, latest version 8 and 10.

### Client
**iOS version: 10.2.1

**ownCloud app version: 3.7.0

**Device model: iPhone 6s and iPhone 7

Uninstalling app and reinstalling app resolves issue.

**Comment by nasli** [comment]
Thanks for your feedback @paraviz02 ,
Would you like to be a beta tester?
If you send us your Apple email to apps@owncloud.com, we can provide you a new beta version

**Comment by dazedman** [comment]
@paraviz02 Thenk you for posting this. I had the exact same issue and this solved the problem.

**Comment by nasli** [comment]
New version 3.7.1 should be available in a short time today, please try it and give us feedback.
Thank you for your help.

**Comment by paraviz02** [comment]
Ok - we would definitely be interested. Sending email to apps right now.

**Comment by nasli** [comment]
Fixed within 3.7.1 https://github.com/owncloud/ios/tree/version_3.7.1
