### ISSUE TITLE
Join Request

### ISSUE THREAD

**Issue by HassanUsman** [owncloud/ios#997]
Hi, could you invite me to the owncloud GitHub organization?

**Comment by lefherz** [comment]
Hi @HassanUsman,

why do you need access to the github organization? Did anyone recommend you?

Best, Emil

**Comment by HassanUsman** [comment]
Hi,
I just want to share my open source projects in your organization and contribute in your current projects.

**Comment by lefherz** [comment]
Ah, you can do that already :) being in the organization mainly serves for assignment and other GitHub features. If you have contributions, just open a PR or an Issue :)

Thanks for your interest!
